const branches=['Nsawam Branch','Koforidua Branch','Aburi Branch','Adukrom Branch','Mamfe Branch','Madina Branch'];
const DEMO_PASSWORD='Akuapem@2026';
const roles={
 'System Admin':{initials:'SA',global:true,actions:['all']},
 'Head-Office Users':{initials:'HO',global:true,actions:['approve','manage','report']},
 'Branch Manager':{initials:'BM',global:false,actions:['approve','report']},
 'Branch Operations':{initials:'BO',global:false,actions:['create','manage']},
 'Customer Service':{initials:'CS',global:false,actions:['create','view']}
};
const nav=[['dashboard','◫','Dashboard'],['customers','⌕','Customer & Account Search'],['request','＋','Cheque Book Request'],['vault','▦','Vault & Reconciliation'],['inventory','▤','Inventory & Ranges'],['issuance','▣','Issuance & Collection'],['verification','✓','Cheque Verification'],['stop','⊘','Stop / Cancel Cheque'],['returns','↩','Returned Cheques'],['notifications','✉','Customer Alerts'],['authorization','◉','Authorization Queue'],['reports','▥','Reports'],['admin','⚙','Administration'],['audit','◷','Audit Trail']];
let data={
 requests:[['CBR-2026-0841','AC-00129482','Ama Ofori','Nsawam Branch','50 leaves','Pending Authorization','24 Jul, 09:42'],['CBR-2026-0838','AC-00773819','Kwaku Mensah','Koforidua Branch','100 leaves','Authorized','23 Jul, 15:15'],['CBR-2026-0836','AC-00359510','Akosua Frimpong','Aburi Branch','50 leaves','Issued','23 Jul, 11:30'],['CBR-2026-0833','AC-00902811','Bright Logistics Ltd','Madina Branch','100 leaves','Rejected','22 Jul, 16:21']],
 inventory:[['INV-NS-001','Nsawam Branch','ACB Standard','000120001 – 000120500','500','428','Active'],['INV-KF-002','Koforidua Branch','ACB Corporate','000125001 – 000125300','300','112','Active'],['INV-AB-001','Aburi Branch','ACB Standard','000130001 – 000130200','200','0','Archived'],['INV-MD-003','Madina Branch','ACB Standard','000150001 – 000150600','600','390','Active']],
 issuance:[['ISS-02631','CBR-2026-0836','Akosua Frimpong','Aburi Branch','000130042 – 000130091','Issued','23 Jul, 14:10'],['ISS-02629','CBR-2026-0828','Yaw Boateng','Nsawam Branch','000120118 – 000120167','Collected','22 Jul, 10:05'],['ISS-02628','CBR-2026-0826','Abena Nyarko','Koforidua Branch','000125044 – 000125093','Awaiting Collection','21 Jul, 16:22']],
 verifications:[['VFY-19044','000120151','AC-00129482','Ama Ofori','Nsawam Branch','₵8,450.00','Active'],['VFY-19041','000125069','AC-00773819','Kwaku Mensah','Koforidua Branch','₵15,200.00','Stopped'],['VFY-19036','000150288','AC-00902811','Bright Logistics Ltd','Madina Branch','₵4,765.00','Returned']],
 stops:[['STP-0104','000125069','Kwaku Mensah','Koforidua Branch','Lost cheque','Stopped','24 Jul, 08:55'],['CAN-0089','000120094','Nana Addo','Nsawam Branch','Customer request','Pending Authorization','23 Jul, 14:40']],
 returns:[['RET-0058','000150288','Bright Logistics Ltd','Madina Branch','Insufficient funds','₵4,765.00','Returned'],['RET-0057','000130099','Gifty Asante','Aburi Branch','Signature differs','₵2,100.00','Returned']],
 vault:[['VLT-2026-0031','Nsawam Branch','ACB Standard','000121001 – 000121500','500 leaves','Awaiting Confirmation','24 Jul, 16:10'],['VLT-2026-0030','Koforidua Branch','ACB Corporate','000126001 – 000126300','300 leaves','Awaiting Confirmation','24 Jul, 14:02'],['VLT-2026-0029','Madina Branch','ACB Standard','000151001 – 000151400','400 leaves','Awaiting Confirmation','24 Jul, 11:18'],['VLT-2026-0027','Koforidua Branch','ACB Standard','000127001 – 000127200','200 leaves','Pending Authorisation','24 Jul, 08:20'],['VLT-2026-0028','Aburi Branch','ACB Standard','000131001 – 000131200','200 leaves','Accepted','23 Jul, 10:40']],
 vaultMeta:{'VLT-2026-0027':{maker:'Kojo Asare',makerRole:'Branch Operations',submitted:'24 Jul, 08:20'}},
 approvals:[['APR-0445','Cheque book request','CBR-2026-0841','Ama Ofori','Nsawam Branch','Esi Nkrumah','24 Jul, 09:42'],['APR-0444','Cheque cancellation','CAN-0089','Nana Addo','Nsawam Branch','Kwabena Osei','23 Jul, 14:40'],['APR-0441','Range registration','INV-MD-003','Madina Branch','Yaa Serwaa','23 Jul, 09:10']],
 approvalMeta:{'APR-0445':{bucket:'requests',ref:'CBR-2026-0841',statusIdx:5,finalStatus:'Authorized',maker:'Esi Nkrumah',makerRole:'Customer Service'},'APR-0444':{bucket:'stops',ref:'CAN-0089',statusIdx:5,finalStatus:'Cancelled',maker:'Kwabena Osei',makerRole:'Branch Operations'},'APR-0441':{bucket:'inventory',ref:'INV-MD-003',statusIdx:6,finalStatus:'Active',maker:'Yaa Serwaa',makerRole:'Branch Operations'}},
 audit:[['24 Jul, 09:42','Cheque book request created','CBR-2026-0841','Esi Nkrumah','Customer Service','Nsawam Branch','Initial request submitted'],['24 Jul, 08:55','Stop cheque authorised','STP-0104','Kojo Asare','Branch Manager','Koforidua Branch','Lost cheque confirmed'],['23 Jul, 15:15','Cheque book request authorised','CBR-2026-0838','Adwoa Owusu','Branch Manager','Koforidua Branch','Approved for issuance'],['23 Jul, 14:10','Cheque book issued','ISS-02631','Yaw Sarpong','Branch Operations','Aburi Branch','Identity verified']],
 notifications:[['NTF-100231','Akosua Frimpong','AC-00359510','Aburi Branch','SMS','Your cheque book 000130042 – 000130091 is ready for collection at Aburi Branch. Please bring valid photo ID.','Sent','23 Jul, 14:12']]
};
let state={logged:false,role:'Branch Operations',branch:'Nsawam Branch',user:'',perms:[],global:false,initials:'',roleLabel:'',page:'dashboard',toast:'',modal:null,loginError:'',adminTab:'users'};
function has(p){return (state.perms||[]).includes(p)}
function isAdmin(){return has('admin.manage')||has('admin.authorise')}
const app=document.querySelector('#app');
const esc=v=>String(v).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const allowed=row=>state.global ? (state.branch==='All Branches'||row.includes(state.branch)) : row.includes(state.branch);
const badge=s=>`<span class="badge ${String(s).toLowerCase().replaceAll(' ','-')}">${esc(s)}</span>`;
function statusClass(s){return String(s).toLowerCase().replaceAll(' ','-')}
function table(headers,rows,extra=''){const visible=rows.filter(allowed);return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')} ${extra?'<th></th>':''}</tr></thead><tbody>${visible.length?visible.map((r,i)=>`<tr>${r.map((c,j)=>`<td>${['Status','State'].includes(headers[j])?badge(c):esc(c)}</td>`).join('')}${extra?`<td>${extra.replaceAll('{i}',i)}</td>`:''}</tr>`).join(''):`<tr><td colspan="${headers.length+1}" class="empty">No records are available within your branch scope.</td></tr>`}</tbody></table></div>`}
function val(sel){const el=document.querySelector(sel);return el?String(el.value).trim():''}
function permLabel(id){return (state.permCatalog||[]).find(p=>p.id===id)?.label||id}
function effPermsClient(role,groups){const set=new Set();const rc=data.roles||{},gc=data.groups||{};[role,...((groups||[]).flatMap(g=>gc[g]?.roles||[]))].forEach(rn=>{(rc[rn]?.permissions||[]).forEach(p=>set.add(p))});return set}
function sodViolation(set){for(const [a,b] of (data.sodMatrix||[]))if(set.has(a)&&set.has(b))return [a,b];return null}
const adminUsers=[['Akua Boateng','System Admin','All Branches','Active','24 Jul, 10:02'],['Esi Nkrumah','Customer Service','Nsawam Branch','Active','24 Jul, 09:42'],['Adwoa Owusu','Branch Manager','Koforidua Branch','Active','24 Jul, 09:30'],['Yaw Sarpong','Branch Operations','Aburi Branch','Active','23 Jul, 14:10']];
function moduleData(key){const m={request:[['Reference','Account','Customer','Branch','Book size','Status','Created'],data.requests],inventory:[['Reference','Branch','Book type','Serial range','Total','Available','Status'],data.inventory],issuance:[['Reference','Request','Customer','Branch','Serial range','Status','Processed'],data.issuance],verification:[['Reference','Cheque no.','Account','Customer','Branch','Amount','Status'],data.verifications],stop:[['Reference','Cheque no.','Customer','Branch','Reason','Status','Submitted'],data.stops],returns:[['Reference','Cheque no.','Customer','Branch','Reason','Amount','Status'],data.returns],authorization:[['Queue ID','Transaction','Reference','Customer / Subject','Branch','Maker','Submitted'],data.approvals],vault:[['Reference','Destination branch','Book type','Serial range','Quantity','Status','Dispatched'],data.vault||[]],admin:[['User','Role','Assigned branch','Status','Last active'],adminUsers]};return m[key]?{headers:m[key][0],rows:m[key][1]}:null}
function toast(msg){state.toast=msg;render();setTimeout(()=>{state.toast='';render()},2600)}
function login(){return `<section class="login"><div class="login-hero"><div class="seal">ACB</div><div class="login-tag">✦ Secure banking operations</div><h1>Cheque management, with control at every step.</h1><p>One secure workspace for inventory, issuance, verification and authorisation across every Akuapem Community Bank branch.</p></div><div class="login-panel"><div class="login-card"><div class="bank-mark"><div class="mark-icon">ACB</div><div>Akuapem Community Bank PLC<br><span>CHEQUE MANAGEMENT SYSTEM</span></div></div><h2>Welcome back</h2><p class="sub">Sign in to your secure operations workspace.</p>${state.loginError?`<div class="login-error">${esc(state.loginError)}</div>`:''}<div class="field"><label>Staff ID or Email</label><input id="login-staff" value="ops.nsawam@acb.com" autocomplete="username" onkeydown="if(event.key==='Enter')signIn()" /></div><div class="field"><label>Password</label><input id="login-password" type="password" value="${esc(DEMO_PASSWORD)}" autocomplete="current-password" onkeydown="if(event.key==='Enter')signIn()" /></div><button class="primary" onclick="signIn()">Sign in securely →</button><p class="hint">Prototype demo accounts (password <b>${esc(DEMO_PASSWORD)}</b>): admin@acb.com · headoffice@acb.com · manager.koforidua@acb.com · ops.nsawam@acb.com · cs.nsawam@acb.com. MFA/SSO are represented in the production design.</p></div></div></section>`}
function sidebar(){return `<aside class="sidebar"><div class="brand"><div class="brand-logo">ACB</div><div><b>Akuapem Community<br>Bank PLC</b><br><span>CHEQUE MANAGEMENT</span></div></div><div class="nav-label">WORKSPACE</div>${nav.slice(0,-3).map(n=>`<button class="nav-btn ${state.page===n[0]?'active':''}" onclick="go('${n[0]}')"><b>${n[1]}</b><span>${n[2]}</span></button>`).join('')}<div class="nav-label">GOVERNANCE</div>${nav.slice(-3).map(n=>`<button class="nav-btn ${state.page===n[0]?'active':''}" onclick="go('${n[0]}')"><b>${n[1]}</b><span>${n[2]}</span></button>`).join('')}<div class="sidebar-foot">Secure session<br>v1.0 Prototype</div></aside>`}
function topbar(){let global=state.global;return `<header class="topbar"><button class="ghost mobile-menu" onclick="document.querySelector('.sidebar').classList.toggle('open')">☰</button><span class="scope-pill">${global?'Global view · all six branches':`Branch view · ${state.branch}`}</span><div class="top-controls"><select onchange="setBranch(this.value)" ${global?'':'disabled'}>${global?'<option value="All Branches">All branches</option>':''}${branches.map(b=>`<option ${b===state.branch?'selected':''}>${b}</option>`).join('')}</select><div class="user-block"><div class="avatar">${state.initials}</div><div><div class="user-name">${esc(state.user||state.role)}</div><div class="user-role">${esc(state.role)}</div></div></div><button class="ghost" onclick="logout()">Sign out</button></div></header>`}
function shell(content,title,eyebrow='OPERATIONS'){return `<div class="app-shell">${sidebar()}<div class="content">${topbar()}<div class="page-wrap"><div class="title-row"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1></div></div>${content}</div></div></div>${state.modal?modal():''}${state.toast?`<div class="toast">✓ ${state.toast}</div>`:''}`}
function dashboard(){const records=data.requests.filter(allowed);return shell(`<div class="grid kpis"><div class="card kpi"><div><div class="kpi-label">Pending authorisations</div><strong>${has('txn.authorise')?'12':'4'}</strong><small>Requires review</small></div><div class="metric-icon gold">◉</div></div><div class="card kpi"><div><div class="kpi-label">Active cheque books</div><strong>${state.global?'1,284':'214'}</strong><small>Across ${state.global?'six branches':'your branch'}</small></div><div class="metric-icon green">▤</div></div><div class="card kpi"><div><div class="kpi-label">Issued this month</div><strong>${state.global?'326':'47'}</strong><small>Cheque books</small></div><div class="metric-icon">▣</div></div><div class="card kpi"><div><div class="kpi-label">Stop-cheque alerts</div><strong>3</strong><small>Action required</small></div><div class="metric-icon red">⊘</div></div></div><div class="grid dashboard-mid"><section class="card"><div class="card-head"><div><h3>Cheque book issuance trend</h3><small>Last six months</small></div><span class="badge authorized">+12.4%</span></div><div class="chart">${[42,58,47,72,65,89].map((n,i)=>`<div class="bar" style="height:${n}%" data-month="${['Feb','Mar','Apr','May','Jun','Jul'][i]}"></div>`).join('')}</div><div class="chart-note"><i class="dot"></i> Cheque books issued</div></section><section class="card"><div class="card-head"><div><h3>Priority alerts</h3><small>Exceptions needing attention</small></div><button class="ghost" onclick="go('authorization')">View all</button></div><div class="alert"><div class="alert-icon">⚠</div><div><b>4 requests awaiting authorisation</b><p>Oldest request: 1 hour 28 minutes.</p></div></div><div class="alert"><div class="alert-icon">⊘</div><div><b>Stop-cheque request submitted</b><p>Koforidua · Cheque 000125069</p></div></div><div class="alert"><div class="alert-icon">↩</div><div><b>Returned cheque requires review</b><p>Madina · Insufficient funds</p></div></div></section></div><div class="grid bottom-grid"><section class="card wide-card"><div class="card-head"><div><h3>Recent cheque book requests</h3><small>Live activity within your scope</small></div><button class="ghost" onclick="go('request')">Manage requests</button></div>${table(['Reference','Account','Customer','Branch','Book','Status','Created'],records)}</section><section class="card"><div class="card-head"><div><h3>Quick actions</h3><small>Common operations</small></div></div><div class="quick"><button onclick="go('request')">＋ New request<span>Initiate cheque book request</span></button><button onclick="go('verification')">✓ Verify cheque<span>Check live cheque status</span></button><button onclick="go('inventory')">▤ Register range<span>Add inventory serial range</span></button><button onclick="go('authorization')">◉ Review queue<span>Maker-checker approvals</span></button></div></section></div>`,`Overview`)}
function modulePage(key,title,headers,rows,opts={}){const create=opts.create;const action=opts.action;return shell(`<div class="module-toolbar"><div class="filters"><input class="search" placeholder="Search ${title.toLowerCase()}" oninput="filterTable(this.value)"><span class="module-summary">Showing <strong>${rows.filter(allowed).length}</strong> records</span></div>${create&&has(`${key}.create`)?`<button class="primary" onclick="openForm('${key}')">${create.label}</button>`:''}</div><section class="card wide-card"><div class="card-head"><div><h3>${title}</h3><small>${state.global?'All branches':'Your assigned branch only'}</small></div></div>${table(headers,rows,action?`<button class="ghost row-action" onclick="rowAction('${key}',{i})">${action}</button>`:'')}</section>`,title,opts.eyebrow||'CHEQUE OPERATIONS')}
function customers(){return shell(`<div class="card form-card"><div class="card-head"><div><h3>Find a customer or account</h3><small>Search by customer name, account number, or cheque number.</small></div></div><div class="form-grid"><div class="field"><label>Search term</label><input id="customer-search" placeholder="e.g. AC-00129482 or Ama Ofori" /></div><div class="field"><label>Search type</label><select><option>Customer or account</option><option>Cheque number</option></select></div></div><div class="form-actions"><button class="primary" onclick="customerResult()">Search records</button></div></div><div id="customer-result"></div>`,`Customer & Account Search`,'CUSTOMER SERVICE')}
function branchField(){const global=state.global;const current=branches.includes(state.branch)?state.branch:branches[0];return global?`<select data-field="branch">${branches.map(b=>`<option ${b===current?'selected':''}>${b}</option>`).join('')}</select>`:`<input data-field="branch" value="${esc(state.branch)}" readonly>`}
function form(key){const cfg={request:['New Cheque Book Request','Collection branch',[['account','Customer account','AC-00129482'],['customer','Customer name','Ama Ofori'],['book','Book size','50 leaves'],['reason','Reason','New account cheque book']]],inventory:['Register Cheque Range','Branch',[['type','Cheque book type','ACB Standard'],['start','Start serial','000160001'],['end','End serial','000160500'],['supplier','Supplier / batch','SecurePrint Ghana Ltd']]],issuance:['Issue Cheque Book','Issuing branch',[['request','Approved request reference','CBR-2026-0841'],['account','Customer account','AC-00129482'],['range','Cheque serial range','000120151 – 000120200'],['method','Collection method','In-person collection'],['verifier','Identity verified by','Yaw Sarpong']]],stop:['Stop / Cancel Cheque','Branch',[['cheque','Cheque number','000120151'],['account','Customer account','AC-00129482'],['instruction','Instruction type','Stop cheque'],['reason','Reason','Lost cheque'],['remarks','Remarks','Customer instruction recorded.']]],returns:['Record Returned Cheque','Branch',[['cheque','Cheque number','000150288'],['account','Account number','AC-00902811'],['reason','Return reason','Insufficient funds'],['amount','Cheque amount','₵4,765.00'],['remarks','Remarks','Return instrument received.']]]}[key];if(!cfg)return '';const [title,branchLabel,fields]=cfg;return shell(`<section class="card form-card"><div class="card-head"><div><h3>${title}</h3><small>Transactions are captured by a maker and routed for authorisation when required.</small></div></div><div class="notice">You are operating within <b>${state.global?'the selected global scope':state.branch}</b>. All actions will be logged with your role, date and time.</div><form id="txn-form" onsubmit="return false" class="form-grid"><div class="field"><label>${branchLabel}</label>${branchField()}</div>${fields.map(([k,l,v])=>`<div class="field"><label>${l}</label><input data-field="${k}" value="${esc(v)}"></div>`).join('')}</form><div class="form-actions"><button class="ghost" onclick="go('${key}')">Cancel</button><button class="primary" onclick="submitForm('${key}')">Submit ${key==='issuance'?'issuance':key==='returns'?'return record':'for authorisation'} →</button></div></section>`,title,'NEW TRANSACTION')}
function authorization(){if(!has('txn.authorise')) return shell(`<div class="denied"><b>Authorisation queue restricted</b><br>Your ${state.role} profile can submit transactions but cannot approve them. Please contact your Branch Manager or Head Office.</div>`,`Authorization Queue`,'MAKER–CHECKER CONTROL');return modulePage('authorization','Authorization Queue',['Queue ID','Transaction','Reference','Customer / Subject','Branch','Maker','Submitted'],data.approvals,{action:'Review',eyebrow:'MAKER–CHECKER CONTROL'})}
function reports(){return shell(`<div class="grid kpis"><div class="card kpi"><div><div class="kpi-label">Requests processed</div><strong>326</strong><small>July 2026</small></div><div class="metric-icon">▥</div></div><div class="card kpi"><div><div class="kpi-label">Average approval time</div><strong>42m</strong><small>Within target</small></div><div class="metric-icon green">✓</div></div><div class="card kpi"><div><div class="kpi-label">Returned cheque value</div><strong>₵18.6k</strong><small>Month to date</small></div><div class="metric-icon red">↩</div></div><div class="card kpi"><div><div class="kpi-label">Audit events</div><strong>1,942</strong><small>Month to date</small></div><div class="metric-icon gold">◷</div></div></div><section class="card wide-card"><div class="card-head"><div><h3>Operational reports</h3><small>Downloadable reports are filtered to your permitted branch scope.</small></div></div>${table(['Report','Period','Scope','Last generated','State'],[['Cheque book inventory reconciliation','July 2026',state.global?'All branches':state.branch,'24 Jul, 09:00','Ready'],['Pending authorisation ageing','Live',state.global?'All branches':state.branch,'24 Jul, 10:15','Ready'],['Returned cheque register','July 2026',state.global?'All branches':state.branch,'24 Jul, 08:30','Ready'],['Stop-cheque instruction register','July 2026',state.global?'All branches':state.branch,'24 Jul, 09:30','Ready']],`<button class="ghost" onclick="toast('Report download prepared')">Download</button>`)}</section>`,`Reports & Insights`,'MANAGEMENT INFORMATION')}
function setAdminTab(t){state.adminTab=t;render()}
function admin(){if(!isAdmin())return shell(`<div class="denied"><b>Administration restricted</b><br>Only staff with administrative permissions can manage users, roles, groups and controls.</div>`,`Administration`,'SYSTEM GOVERNANCE');const tabs=[['users','Users'],['roles','Roles'],['groups','Groups'],['sod','Segregation of Duties'],['approvals','Admin Approvals'],['audit','Change Audit']];const tab=state.adminTab||'users';const qn=(data.adminQueue||[]).length;const nav=`<div class="admin-tabs">${tabs.map(t=>`<button class="admin-tab ${tab===t[0]?'active':''}" onclick="setAdminTab('${t[0]}')">${t[1]}${t[0]==='approvals'&&qn?` <span class="tab-badge">${qn}</span>`:''}</button>`).join('')}</div>`;const views={users:adminUsersView,roles:adminRolesView,groups:adminGroupsView,sod:adminSodView,approvals:adminApprovalsView,audit:adminAuditView};return shell(nav+(views[tab]||adminUsersView)(),'Administration','SYSTEM GOVERNANCE')}
function adminUsersView(){const manage=has('admin.manage');const rows=Object.entries(data.directory||{}).map(([id,u])=>{const v=sodViolation(effPermsClient(u.role,u.groups));const groups=(u.groups||[]).map(g=>`<span class="chip">${esc(g)}</span>`).join(' ')||'<span class="muted-sm">—</span>';return `<tr><td><b>${esc(u.name)}</b><br><span class="muted-sm">${esc(id)}</span></td><td>${esc(u.role)}${v?` <span class="sod-flag" title="SoD conflict: ${esc(v[0])} vs ${esc(v[1])}">⚠ SoD</span>`:''}</td><td>${groups}</td><td>${esc(u.branch)}</td><td>${badge(u.status)}</td><td>${esc(u.lastReviewed||'—')}</td><td class="admin-actions">${manage?`<button class="ghost xs" onclick="openAdmin('user-role','${esc(id)}')">Role</button><button class="ghost xs" onclick="openAdmin('user-groups','${esc(id)}')">Groups</button><button class="ghost xs" onclick="adminRecertify('${esc(id)}')">Recertify</button>${u.status==='Active'?`<button class="ghost xs danger" onclick="adminDisable('${esc(id)}')">Disable</button>`:`<button class="ghost xs" onclick="adminEnable('${esc(id)}')">Enable</button>`}`:'<span class="muted-sm">View only</span>'}</td></tr>`}).join('');return `<div class="module-toolbar"><span class="module-summary">${Object.keys(data.directory||{}).length} users · privilege grants require a second administrator</span>${manage?`<button class="primary" onclick="openAdmin('add-user')">＋ Add user</button>`:''}</div><section class="card wide-card"><div class="table-wrap"><table><thead><tr><th>User</th><th>Role</th><th>Groups</th><th>Branch</th><th>Status</th><th>Last reviewed</th><th></th></tr></thead><tbody>${rows}</tbody></table></div></section>`}
function adminRolesView(){const manage=has('admin.manage');const rows=Object.entries(data.roles||{}).map(([name,r])=>`<tr><td><b>${esc(r.label||name)}</b>${r.system?' <span class="chip sys">built-in</span>':''}</td><td>${r.global?'Global (all branches)':'Branch-scoped'}</td><td>${(r.permissions||[]).map(p=>`<span class="chip">${esc(permLabel(p))}</span>`).join(' ')||'<span class="muted-sm">none</span>'}</td><td class="admin-actions">${manage?`<button class="ghost xs" onclick="openAdmin('role-edit','${esc(name)}')">Edit</button>${r.system?'':`<button class="ghost xs danger" onclick="adminDeleteRole('${esc(name)}')">Delete</button>`}`:''}</td></tr>`).join('');return `<div class="module-toolbar"><span class="module-summary">Roles are permission bundles. Changes are routed for a second administrator's authorisation.</span>${manage?`<button class="primary" onclick="openAdmin('role-edit')">＋ New role</button>`:''}</div><section class="card wide-card"><div class="table-wrap"><table><thead><tr><th>Role</th><th>Scope</th><th>Permissions</th><th></th></tr></thead><tbody>${rows}</tbody></table></div></section>`}
function adminGroupsView(){const manage=has('admin.manage');const members=g=>Object.values(data.directory||{}).filter(u=>(u.groups||[]).includes(g)).length;const rows=Object.entries(data.groups||{}).map(([name,g])=>`<tr><td><b>${esc(name)}</b><br><span class="muted-sm">${esc(g.description||'')}</span></td><td>${esc(g.branch||'All Branches')}</td><td>${(g.roles||[]).map(r=>`<span class="chip">${esc(r)}</span>`).join(' ')||'<span class="muted-sm">none</span>'}</td><td>${members(name)}</td><td class="admin-actions">${manage?`<button class="ghost xs" onclick="openAdmin('group-edit','${esc(name)}')">Edit</button><button class="ghost xs danger" onclick="adminDeleteGroup('${esc(name)}')">Delete</button>`:''}</td></tr>`).join('');return `<div class="module-toolbar"><span class="module-summary">Groups collect users and grant them roles.</span>${manage?`<button class="primary" onclick="openAdmin('group-edit')">＋ New group</button>`:''}</div><section class="card wide-card"><div class="table-wrap"><table><thead><tr><th>Group</th><th>Branch</th><th>Roles</th><th>Members</th><th></th></tr></thead><tbody>${rows}</tbody></table></div></section>`}
function adminSodView(){const manage=has('admin.manage');const cat=state.permCatalog||[];const pairs=(data.sodMatrix||[]).map((p,i)=>`<div class="sod-pair"><span>${esc(permLabel(p[0]))} <b>⨂</b> ${esc(permLabel(p[1]))}</span>${manage?`<button class="ghost xs danger" onclick="adminRemoveSod('${esc(p[0])}','${esc(p[1])}')">Remove</button>`:''}</div>`).join('')||'<p class="muted-sm">No rules defined.</p>';const opts=cat.map(p=>`<option value="${esc(p.id)}">${esc(p.label)}</option>`).join('');const viol=[];for(const [id,u] of Object.entries(data.directory||{})){const v=sodViolation(effPermsClient(u.role,u.groups));if(v)viol.push(`<tr><td>${esc(u.name)}</td><td>${esc(id)}</td><td>${esc(permLabel(v[0]))} ⨂ ${esc(permLabel(v[1]))}</td></tr>`)}const violTable=viol.length?`<div class="table-wrap"><table><thead><tr><th>User</th><th>Staff ID</th><th>Conflict</th></tr></thead><tbody>${viol.join('')}</tbody></table></div>`:'<p class="ok-note">✓ No users currently hold a conflicting pair of permissions.</p>';return `<div class="grid" style="grid-template-columns:1fr 1fr;gap:18px"><section class="card"><div class="card-head"><div><h3>Mutually-exclusive permissions</h3><small>Static separation of duties — blocked at assignment</small></div></div>${pairs}${manage?`<div class="sod-add"><select id="sod-a">${opts}</select><span>⨂</span><select id="sod-b">${opts}</select><button class="primary" onclick="adminAddSod()">Add rule</button></div>`:''}</section><section class="card"><div class="card-head"><div><h3>Violations report</h3><small>Users holding a conflicting pair right now</small></div></div>${violTable}</section></div>`}
function adminApprovalsView(){const canAuth=has('admin.authorise');const q=data.adminQueue||[];const rows=q.map(c=>{const own=c.submittedBy===state.user;return `<div class="vault-item"><div class="vault-item-info"><b>${esc(c.summary)}</b><span>Submitted by ${esc(c.submittedBy)} · ${esc(c.submittedAt)}</span></div><div class="vault-actions">${!canAuth?'<span class="muted-sm">Awaiting an authoriser</span>':own?'<span class="vault-note">You submitted this — another administrator must authorise.</span>':`<button class="ghost xs danger" onclick="adminRejectChange('${esc(c.id)}')">Reject</button><button class="primary xs" onclick="adminAuthChange('${esc(c.id)}')">Authorise ✓</button>`}</div></div>`}).join('');return `<section class="card"><div class="card-head"><div><h3>Pending administrative changes</h3><small>Every privilege grant needs a second administrator (four-eyes)</small></div></div>${q.length?rows:'<p class="ok-note">✓ Nothing awaiting authorisation.</p>'}</section>`}
function adminAuditView(){return `<section class="card wide-card"><div class="card-head"><div><h3>Administrative change audit</h3><small>Immutable record of every governance action</small></div></div><div class="table-wrap"><table><thead><tr><th>When</th><th>Actor</th><th>Action</th><th>Target</th><th>Detail</th></tr></thead><tbody>${(data.adminAudit||[]).map(a=>`<tr>${a.map(c=>`<td>${esc(c)}</td>`).join('')}</tr>`).join('')||'<tr><td colspan="5" class="empty">No entries.</td></tr>'}</tbody></table></div></section>`}
function openAdmin(kind,ctx){state.modal={type:'admin',kind,ctx:ctx||null};render()}
async function adminPost(path,body,okMsg){try{const r=await fetch('/api/admin/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body||{})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Action failed.');applyState(j);state.modal=null;toast(okMsg)}catch(e){toast(e.message||'Action failed.')}render()}
function adminRecertify(id){return adminPost('user/recertify',{uid:id},'Access recertified.')}
function adminDisable(id){return adminPost('user/disable',{uid:id},'User disabled; sessions ended.')}
function adminEnable(id){return adminPost('user/enable',{uid:id},'Re-enable submitted for authorisation.')}
function adminDeleteRole(name){return adminPost('role/delete',{name},'Role deleted.')}
function adminDeleteGroup(name){return adminPost('group/delete',{name},'Group deleted.')}
function adminRemoveGroup(uid,g){return adminPost('user/groups/remove',{uid,group:g},'Removed from group.')}
function adminAddSod(){return adminPost('sod/add',{a:val('#sod-a'),b:val('#sod-b')},'SoD rule added.')}
function adminRemoveSod(a,b){return adminPost('sod/remove',{a,b},'SoD rule removal submitted for authorisation.')}
function adminAuthChange(id){return adminPost('change/authorise',{id},'Change authorised and applied.')}
function adminRejectChange(id){return adminPost('change/reject',{id},'Change rejected.')}
function submitAddUser(){return adminPost('user/create',{id:val('#au-id'),name:val('#au-name'),branch:val('#au-branch'),role:val('#au-role')},'User creation submitted for authorisation.')}
function submitUserRole(uid){return adminPost('user/role',{uid,role:val('#ur-role')},'Role change submitted for authorisation.')}
function submitAddGroupMember(uid){return adminPost('user/groups/add',{uid,group:val('#ug-add')},'Group assignment submitted for authorisation.')}
function submitRole(){const permissions=[...document.querySelectorAll('.perm-cb:checked')].map(c=>c.value);return adminPost('role/save',{name:val('#role-name'),label:val('#role-label'),global:document.querySelector('#role-global').checked,permissions},'Role change submitted for authorisation.')}
function submitGroup(){const roles=[...document.querySelectorAll('.grole-cb:checked')].map(c=>c.value);return adminPost('group/save',{name:val('#group-name'),description:val('#group-desc'),branch:val('#group-branch'),roles},'Group change submitted for authorisation.')}
function adminModal(){const m=state.modal;const cat=state.permCatalog||[];const roleOpts=Object.keys(data.roles||{}).map(r=>`<option>${esc(r)}</option>`).join('');const branchOpts=['All Branches',...branches].map(b=>`<option>${esc(b)}</option>`).join('');function wrap(title,bodyHtml,actionBtn){return `<div class="modal-backdrop"><div class="modal admin-modal"><h2>${title}</h2>${bodyHtml}<div class="modal-actions"><button class="ghost" onclick="state.modal=null;render()">Cancel</button>${actionBtn}</div></div></div>`}
  if(m.kind==='add-user')return wrap('Add user',`<div class="form-grid"><div class="field"><label>Staff email</label><input id="au-id" placeholder="name@acb.com"></div><div class="field"><label>Full name</label><input id="au-name"></div><div class="field"><label>Role</label><select id="au-role">${roleOpts}</select></div><div class="field"><label>Branch</label><select id="au-branch">${branchOpts}</select></div></div><p class="muted-sm">A default password (${esc(DEMO_PASSWORD)}) is set; creation is queued for a second administrator.</p>`,`<button class="primary" onclick="submitAddUser()">Submit for authorisation</button>`);
  if(m.kind==='user-role'){const u=(data.directory||{})[m.ctx]||{};return wrap(`Change role — ${esc(u.name||m.ctx)}`,`<div class="field"><label>New role</label><select id="ur-role">${Object.keys(data.roles||{}).map(r=>`<option ${r===u.role?'selected':''}>${esc(r)}</option>`).join('')}</select></div><p class="muted-sm">Blocked if it would breach segregation of duties; queued for a second administrator.</p>`,`<button class="primary" onclick="submitUserRole('${esc(m.ctx)}')">Submit</button>`)}
  if(m.kind==='user-groups'){const u=(data.directory||{})[m.ctx]||{};const cur=(u.groups||[]).map(g=>`<div class="vault-item"><span>${esc(g)}</span><button class="ghost xs danger" onclick="adminRemoveGroup('${esc(m.ctx)}','${esc(g)}')">Remove</button></div>`).join('')||'<p class="muted-sm">No groups assigned.</p>';const avail=Object.keys(data.groups||{}).filter(g=>!(u.groups||[]).includes(g));return wrap(`Groups — ${esc(u.name||m.ctx)}`,`${cur}<div class="sod-add">${avail.length?`<select id="ug-add">${avail.map(g=>`<option>${esc(g)}</option>`).join('')}</select><button class="primary" onclick="submitAddGroupMember('${esc(m.ctx)}')">Add (queued)</button>`:'<span class="muted-sm">No more groups to add.</span>'}</div>`,'')}
  if(m.kind==='role-edit'){const r=(data.roles||{})[m.ctx]||{permissions:[],global:false};const byCat={};cat.forEach(p=>{(byCat[p.cat]=byCat[p.cat]||[]).push(p)});const perms=Object.entries(byCat).map(([c,ps])=>`<div class="perm-group"><b>${esc(c)}</b>${ps.map(p=>`<label class="perm-cbl"><input type="checkbox" class="perm-cb" value="${esc(p.id)}" ${(r.permissions||[]).includes(p.id)?'checked':''}> ${esc(p.label)}</label>`).join('')}</div>`).join('');return wrap(m.ctx?`Edit role — ${esc(m.ctx)}`:'New role',`<div class="form-grid"><div class="field"><label>Role key</label><input id="role-name" value="${esc(m.ctx||'')}" ${m.ctx?'readonly':''}></div><div class="field"><label>Display label</label><input id="role-label" value="${esc(r.label||m.ctx||'')}"></div></div><label class="perm-cbl"><input type="checkbox" id="role-global" ${r.global?'checked':''}> Global scope (all branches)</label><div class="perm-catalog">${perms}</div><p class="muted-sm">A role may not combine two segregated permissions. Queued for authorisation.</p>`,`<button class="primary" onclick="submitRole()">Submit for authorisation</button>`)}
  if(m.kind==='group-edit'){const g=(data.groups||{})[m.ctx]||{roles:[]};const roleCbs=Object.keys(data.roles||{}).map(r=>`<label class="perm-cbl"><input type="checkbox" class="grole-cb" value="${esc(r)}" ${(g.roles||[]).includes(r)?'checked':''}> ${esc(r)}</label>`).join('');return wrap(m.ctx?`Edit group — ${esc(m.ctx)}`:'New group',`<div class="form-grid"><div class="field"><label>Group name</label><input id="group-name" value="${esc(m.ctx||'')}" ${m.ctx?'readonly':''}></div><div class="field"><label>Branch</label><select id="group-branch">${['All Branches',...branches].map(b=>`<option ${b===(g.branch||'All Branches')?'selected':''}>${esc(b)}</option>`).join('')}</select></div></div><div class="field"><label>Description</label><input id="group-desc" value="${esc(g.description||'')}"></div><div class="perm-group"><b>Roles granted by this group</b>${roleCbs}</div>`,`<button class="primary" onclick="submitGroup()">Submit for authorisation</button>`)}
  return wrap('Administration','','')}
function applyState(j){if(!j)return;if(j.data)data=j.data;if(Array.isArray(j.perms))state.perms=j.perms;if(typeof j.global==='boolean')state.global=j.global;if(j.role)state.role=j.role;if(j.branch)state.branch=j.branch;if(j.name)state.user=j.name;if(j.roleLabel)state.roleLabel=j.roleLabel;if(j.initials)state.initials=j.initials;if(j.permCatalog)state.permCatalog=j.permCatalog}
function audit(){return modulePage('audit','Complete Audit Trail',['Date & time','Action','Reference','Maker','Role','Branch','Remarks'],data.audit,{eyebrow:'COMPLIANCE & ACCOUNTABILITY'})}
function leaves(v){return parseInt(String(v).replace(/[^0-9]/g,''),10)||0}
function canSubmitVault(){return has('vault.submit')}
function canAuthoriseVault(){return has('vault.authorise')}
function cylinder(fill,cls,pctLabel,side){return `<div class="cylinder ${cls}" role="button" tabindex="0" title="Click to view all ${side==='vault'?'vault batches':'inventory ranges'}" onclick="openStock('${side}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();openStock('${side}')}"><div class="cyl-rim"></div><div class="cyl-glass"><div class="cyl-liquid" style="height:${Math.min(100,Math.max(fill,4))}%"><span class="cyl-surface"></span></div></div><div class="cyl-pct">${pctLabel}</div><div class="cyl-hint">View details</div></div>`}
function openStock(side){state.modal={type:'stock',side};render()}
function stockModal(){const isVault=state.modal.side==='vault';const headers=isVault?['Reference','Destination branch','Book type','Serial range','Quantity','Status','Dispatched']:['Reference','Branch','Book type','Serial range','Total','Available','Status'];const rows=isVault?(data.vault||[]):data.inventory;const title=isVault?'Head-Office Vault — cheque stock':'Branch Inventory — cheque ranges';const sub=isVault?'Every cheque batch held in the vault, with its serial range and reconciliation status.':'Every registered cheque serial range currently available in branch inventory.';const count=rows.filter(allowed).length;return `<div class="modal-backdrop"><div class="modal stock-modal"><h2>${title}</h2><p>${sub} Showing <b>${count}</b> record${count===1?'':'s'} in your scope.</p>${table(headers,rows)}<div class="modal-actions"><button class="ghost" onclick="state.modal=null;render()">Close</button></div></div></div>`}
function vault(){const vaultRows=(data.vault||[]).filter(allowed);const awaiting=vaultRows.filter(v=>v[5]==='Awaiting Confirmation');const pending=vaultRows.filter(v=>v[5]==='Pending Authorisation');const inVault=vaultRows.filter(v=>v[5]!=='Accepted');const invRows=data.inventory.filter(allowed);const vaultLeaves=inVault.reduce((n,v)=>n+leaves(v[4]),0);const invLeaves=invRows.reduce((n,v)=>n+leaves(v[5]),0);const cap=Math.max(vaultLeaves+invLeaves,1);const leftFill=Math.round(vaultLeaves/cap*100);const rightFill=Math.round(invLeaves/cap*100);const canPush=has('vault.dispatch');const transferReady=(canSubmitVault()&&awaiting.length)||(canAuthoriseVault()&&pending.length)||canPush;const stage=`<div class="vault-stage"><div class="vault-side">${cylinder(leftFill,'from-ho',vaultLeaves.toLocaleString(),'vault')}<div class="vault-cap"><b>Head-Office Vault</b><span>${inVault.length} batch${inVault.length===1?'':'es'} in vault${pending.length?` · ${pending.length} pending authorisation`:''}</span></div></div><div class="vault-mid"><button class="vault-transfer" ${transferReady?'':'disabled'} onclick="openVault()" title="Move cheque stock between the vault and inventory">⇄</button><span class="vault-mid-label">Move in / out</span><span class="vault-mid-sub">Vault ↔ Inventory</span></div><div class="vault-side">${cylinder(rightFill,'to-inv',invLeaves.toLocaleString(),'inventory')}<div class="vault-cap"><b>Branch Inventory</b><span>${invRows.length} active range${invRows.length===1?'':'s'} · ${invLeaves.toLocaleString()} leaves available</span></div></div></div>`;const legend=`<div class="vault-legend"><span><i class="swatch gold"></i> In vault — awaiting reconciliation or authorisation</span><span><i class="swatch blue"></i> Reconciled, authorised and accepted into inventory</span></div>`;const toolbar=`<div class="module-toolbar"><span class="module-summary">Showing <strong>${vaultRows.length}</strong> vault batches</span>${transferReady?`<button class="primary" onclick="openVault()">${canPush?'＋ Dispatch to vault':'Reconcile / authorise'}</button>`:''}</div>`;const list=`<section class="card wide-card"><div class="card-head"><div><h3>Vault batches</h3><small>Cheque stock dispatched from head office to ${state.global?'all branch vaults':'your branch vault'}</small></div></div>${table(['Reference','Destination branch','Book type','Serial range','Quantity','Status','Dispatched'],data.vault||[],`<button class="ghost row-action" onclick="rowAction('vault',{i})">View</button>`)}</section>`;return shell(stage+legend+toolbar+list,'Vault & Reconciliation','SECURE STOCK CONTROL')}
function vaultModal(){const canPush=has('vault.dispatch');const canSubmit=canSubmitVault();const canAuth=canAuthoriseVault();const meta=data.vaultMeta||{};const scoped=(data.vault||[]).filter(allowed);const awaiting=scoped.filter(v=>v[5]==='Awaiting Confirmation');const pending=scoped.filter(v=>v[5]==='Pending Authorisation');const branchSel=state.global?`<select data-field="branch">${branches.map(b=>`<option ${b===(branches.includes(state.branch)?state.branch:branches[0])?'selected':''}>${b}</option>`).join('')}</select>`:`<input data-field="branch" value="${esc(state.branch)}" readonly>`;
  const submit=canSubmit?`<div class="vault-section"><h4>① Reconcile &amp; submit</h4><p class="sub">Reconcile the physical hard copies against each vault record, then submit it for second-officer authorisation.</p>${awaiting.length?awaiting.map(v=>`<div class="vault-item"><div class="vault-item-info"><b>${esc(v[0])}</b><span>${esc(v[1])} · ${esc(v[2])} · ${esc(v[3])} · ${esc(v[4])}</span></div><label class="vault-chk"><input type="checkbox" onchange="this.closest('.vault-item').querySelector('.act-btn').disabled=!this.checked"> Hard copies received &amp; reconciled</label><button class="primary act-btn" disabled onclick="submitVault('${esc(v[0])}')">Submit →</button></div>`).join(''):`<p class="empty-note">No batches are awaiting reconciliation in your scope.</p>`}</div>`:'';
  const authorise=canAuth?`<div class="vault-section"><h4>② Authorise into inventory</h4><p class="sub">A second officer confirms the reconciliation and releases the stock into branch inventory. The submitting officer cannot authorise their own batch.</p>${pending.length?pending.map(v=>{const m=meta[v[0]]||{};const ownMaker=m.maker&&m.maker===state.user;return `<div class="vault-item"><div class="vault-item-info"><b>${esc(v[0])}</b><span>${esc(v[1])} · ${esc(v[3])} · ${esc(v[4])}</span><span class="vault-maker">Submitted by ${esc(m.maker||'—')}${m.submitted?` · ${esc(m.submitted)}`:''}</span></div><div class="vault-actions">${ownMaker?`<span class="vault-note">You submitted this — a different officer must authorise.</span>`:`<button class="ghost" onclick="rejectVault('${esc(v[0])}')">Reject</button><button class="primary" onclick="authoriseVault('${esc(v[0])}')">Authorise ✓</button>`}</div></div>`}).join(''):`<p class="empty-note">No batches are pending authorisation in your scope.</p>`}</div>`:'';
  const dispatch=canPush?`<div class="vault-section"><h4>⬆ Dispatch from head office</h4><p class="sub">Register printed cheque stock and push it to a branch vault for confirmation.</p><form id="vault-push-form" onsubmit="return false" class="form-grid"><div class="field"><label>Destination branch</label>${branchSel}</div><div class="field"><label>Cheque book type</label><input data-field="type" value="ACB Standard"></div><div class="field"><label>Start serial</label><input data-field="start" value="000180001"></div><div class="field"><label>End serial</label><input data-field="end" value="000180500"></div></form><div class="form-actions"><button class="primary" onclick="pushVault()">Push to branch vault →</button></div></div>`:'';
  return `<div class="modal-backdrop"><div class="modal vault-modal"><h2>Vault transfer</h2><p>Cheque stock moves from vault to inventory under maker–checker control. Every step is recorded in the audit trail.</p>${submit}${authorise}${dispatch}${!submit&&!authorise&&!dispatch?'<p class="empty-note">Your role has no vault transfer permissions.</p>':''}<div class="modal-actions"><button class="ghost" onclick="state.modal=null;render()">Close</button></div></div></div>`}
function notifications(){if(!has('notifications.view'))return shell(`<div class="denied"><b>Customer alerts restricted</b><br>Your profile does not include permission to view customer alerts.</div>`,'Customer Alerts','CUSTOMER ENGAGEMENT');const rows=(data.notifications||[]);const scoped=rows.filter(allowed);return shell(`<div class="notice">Alerts are dispatched automatically when cheque stock is accepted into a branch and when a cheque book is issued and ready for collection. These are recorded here; connect an SMS/email gateway to deliver them to customers.</div><div class="module-toolbar"><span class="module-summary">Showing <strong>${scoped.length}</strong> customer alert${scoped.length===1?'':'s'} within your scope</span></div><section class="card wide-card"><div class="card-head"><div><h3>Customer alert log</h3><small>Automated ready-for-collection and stock-arrival notifications</small></div></div>${table(['Reference','Customer','Account','Branch','Channel','Message','Status','Sent'],rows)}</section>`,'Customer Alerts','CUSTOMER ENGAGEMENT')}
function page(){if(state.page==='notifications')return notifications();if(state.page==='vault')return vault();if(state.page==='dashboard')return dashboard();if(state.page.endsWith('-new')&&['request','inventory','issuance','stop','returns'].includes(state.page.replace('-new','')))return form(state.page.replace('-new',''));const maps={request:['Cheque Book Requests',['Reference','Account','Customer','Branch','Book size','Status','Created'],data.requests,{create:{label:'＋ New request'},action:'View'}],inventory:['Cheque Book Inventory & Ranges',['Reference','Branch','Book type','Serial range','Total','Available','Status'],data.inventory,{create:{label:'＋ Register range'},action:'View'}],issuance:['Issuance & Collection',['Reference','Request','Customer','Branch','Serial range','Status','Processed'],data.issuance,{create:{label:'＋ Issue cheque book'},action:'View'}],verification:['Cheque Verification',['Reference','Cheque no.','Account','Customer','Branch','Amount','Status'],data.verifications,{}],stop:['Stop / Cancel Cheque Requests',['Reference','Cheque no.','Customer','Branch','Reason','Status','Submitted'],data.stops,{create:{label:'＋ New instruction'},action:'View'}],returns:['Returned / Dishonoured Cheques',['Reference','Cheque no.','Customer','Branch','Reason','Amount','Status'],data.returns,{create:{label:'＋ Record return'},action:'View'}]};if(maps[state.page])return modulePage(state.page,...maps[state.page]);if(state.page==='customers')return customers();if(state.page==='authorization')return authorization();if(state.page==='reports')return reports();if(state.page==='admin')return admin();if(state.page==='audit')return audit();return dashboard()}
function modal(){const m=state.modal;if(m.type==='admin')return adminModal();if(m.type==='vault')return vaultModal();if(m.type==='stock')return stockModal();if(m.type==='detail'){const rows=m.headers.map((h,i)=>`<div class="detail-row"><span>${esc(h)}</span><b>${['Status','State'].includes(h)?badge(m.row[i]):esc(m.row[i])}</b></div>`).join('');return `<div class="modal-backdrop"><div class="modal"><h2>${esc(m.row[0])}</h2><p>Read-only record detail within your permitted branch scope.</p><div class="detail-list">${rows}</div><div class="modal-actions"><button class="primary" onclick="state.modal=null;render()">Close</button></div></div></div>`}if(m.type==='approveTxn'){const it=m.item;const meta=(data.approvalMeta||{})[it[0]]||{};const own=meta.maker&&meta.maker===state.user;const rows=[['Queue ID',it[0]],['Transaction',it[1]],['Reference',it[2]],['Customer / Subject',it[3]],['Branch',it[4]],['Maker',it[5]],['Submitted',it[6]]].map(([h,v])=>`<div class="detail-row"><span>${h}</span><b>${esc(v)}</b></div>`).join('');return `<div class="modal-backdrop"><div class="modal"><h2>Review transaction</h2><p>Confirm the maker's submission. Authorising applies the transaction; rejecting returns it. Both are recorded in the audit trail.</p><div class="detail-list">${rows}</div>${own?`<div class="vault-note" style="margin-top:12px;max-width:none">You submitted this transaction — a different officer with approval rights must authorise it.</div>`:''}<div class="modal-actions"><button class="ghost" onclick="state.modal=null;render()">Cancel</button>${own?'':`<button class="ghost" onclick="rejectTxn('${esc(it[0])}')">Reject</button><button class="primary" onclick="authoriseTxn('${esc(it[0])}')">Authorise ✓</button>`}</div></div></div>`}return `<div class="modal-backdrop"><div class="modal"><h2>Confirm submission</h2><p>This transaction will be captured and routed for maker-checker authorisation, and recorded in the audit trail.</p><div class="field"><label>Remarks (optional)</label><textarea rows="3" placeholder="Add a comment for the audit record"></textarea></div><div class="modal-actions"><button class="ghost" onclick="state.modal=null;render()">Cancel</button><button class="primary" onclick="confirmModal()">Confirm submission</button></div></div></div>`}
function render(){app.innerHTML=state.logged?page():login()}
function go(p){state.page=p;render()}
async function signIn(){const staffId=document.querySelector('#login-staff').value.trim();const password=document.querySelector('#login-password').value;if(location.protocol==='file:'){state.role='Branch Operations';state.branch='Nsawam Branch';state.user='Yaw Sarpong';state.perms=['request.create','inventory.create','issuance.create','stop.create','returns.create','vault.submit'];state.global=false;state.initials='YS';state.logged=true;return render()}try{const r=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({staffId,password})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Sign-in failed.');applyState(j);state.loginError='';state.logged=true;render()}catch(e){state.loginError=e.message||'Unable to sign in.';render()}}
async function logout(){try{if(location.protocol!=='file:')await fetch('/api/logout',{method:'POST'})}catch(e){}state.logged=false;state.modal=null;state.user='';render()}
function setBranch(v){state.branch=v==='All Branches'?'All Branches':v;render()}
function openForm(k){state.page=k+'-new';render()}
function submitForm(k){const fields={};document.querySelectorAll('#txn-form [data-field]').forEach(el=>{fields[el.dataset.field]=el.value.trim()});state.modal={type:'submit',key:k,fields};render()}
function rowAction(k,i){const md=moduleData(k);if(!md)return;const row=md.rows.filter(allowed)[i];if(!row)return;if(k==='authorization'){state.modal={type:'approveTxn',item:row};render();return}state.modal={type:'detail',key:k,headers:md.headers,row};render()}
async function confirmModal(){const m=state.modal;const k=m.key;const fields=m.fields||{};state.modal=null;try{if(location.protocol!=='file:'){const result=await fetch('/api/transactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({module:k,fields})});const json=await result.json().catch(()=>({}));if(!result.ok)throw new Error(json.error||'The request was rejected.');data=json.data}toast('Transaction submitted for authorisation.');state.page=k}catch(error){toast(error.message||'Unable to save. Please try again.')}render()}
async function approvalAction(path,id,okMsg){try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref:id})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Action failed.');data=j.data;state.modal=null;toast(okMsg)}catch(e){toast(e.message||'Action failed.')}render()}
function authoriseTxn(id){return approvalAction('/api/authorizations/authorise',id,'Transaction authorised and applied.')}
function rejectTxn(id){return approvalAction('/api/authorizations/reject',id,'Transaction rejected and returned.')}
function openVault(){state.modal={type:'vault'};render()}
async function vaultAction(path,ref,okMsg){try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ref})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Action failed.');data=j.data;state.modal=null;toast(okMsg)}catch(e){toast(e.message||'Action failed.')}render()}
function submitVault(ref){return vaultAction('/api/vault/submit',ref,'Batch reconciled and submitted for authorisation.')}
function authoriseVault(ref){return vaultAction('/api/vault/authorise',ref,'Batch authorised and moved into branch inventory.')}
function rejectVault(ref){return vaultAction('/api/vault/reject',ref,'Batch returned for re-reconciliation.')}
async function pushVault(){const fields={};document.querySelectorAll('#vault-push-form [data-field]').forEach(el=>{fields[el.dataset.field]=el.value.trim()});try{const r=await fetch('/api/vault/push',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:state.role,branch:state.branch,fields})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Unable to dispatch batch.');data=j.data;state.modal=null;toast('Cheque stock dispatched to branch vault, awaiting confirmation.')}catch(e){toast(e.message||'Unable to dispatch batch.')}render()}
function filterTable(v){document.querySelectorAll('tbody tr').forEach(row=>row.style.display=row.innerText.toLowerCase().includes(v.toLowerCase())?'':'none')}
function customerResult(){const term=document.querySelector('#customer-search').value||'Ama Ofori';document.querySelector('#customer-result').innerHTML=`<section class="card" style="margin-top:18px"><div class="card-head"><div><h3>Customer profile</h3><small>Verified banking profile</small></div>${badge('Active')}</div><div class="form-grid"><div><b>Ama Ofori</b><p class="sub">Account: AC-00129482<br>Branch: Nsawam Branch<br>Customer type: Individual</p></div><div><b>Cheque standing</b><p class="sub">Active book: 000120151 – 000120200<br>Outstanding requests: 1<br>Stop-cheque instructions: 0</p></div></div></section>`}
async function bootstrap(){try{if(location.protocol!=='file:'){const response=await fetch('/api/state');if(response.ok){const j=await response.json();applyState(j);if(j.role)state.logged=true}}}catch(error){console.info('Running with local demonstration data.')}render()}
bootstrap();
