const branches=['Nsawam Branch','Koforidua Branch','Aburi Branch','Adukrom Branch','Mamfe Branch','Madina Branch'];
const roles={
 'System Admin':{initials:'SA',global:true,actions:['all']},
 'Head-Office Users':{initials:'HO',global:true,actions:['approve','manage','report']},
 'Branch Manager':{initials:'BM',global:false,actions:['approve','report']},
 'Branch Operations':{initials:'BO',global:false,actions:['create','manage']},
 'Customer Service':{initials:'CS',global:false,actions:['create','view']}
};
const nav=[['dashboard','◫','Dashboard'],['customers','⌕','Customer & Account Search'],['request','＋','Cheque Book Request'],['vault','▦','Vault & Reconciliation'],['inventory','▤','Inventory & Ranges'],['issuance','▣','Issuance & Collection'],['verification','✓','Cheque Verification'],['stop','⊘','Stop / Cancel Cheque'],['returns','↩','Returned Cheques'],['authorization','◉','Authorization Queue'],['reports','▥','Reports'],['admin','⚙','Administration'],['audit','◷','Audit Trail']];
let data={
 requests:[['CBR-2026-0841','AC-00129482','Ama Ofori','Nsawam Branch','50 leaves','Pending Authorization','24 Jul, 09:42'],['CBR-2026-0838','AC-00773819','Kwaku Mensah','Koforidua Branch','100 leaves','Authorized','23 Jul, 15:15'],['CBR-2026-0836','AC-00359510','Akosua Frimpong','Aburi Branch','50 leaves','Issued','23 Jul, 11:30'],['CBR-2026-0833','AC-00902811','Bright Logistics Ltd','Madina Branch','100 leaves','Rejected','22 Jul, 16:21']],
 inventory:[['INV-NS-001','Nsawam Branch','ACB Standard','000120001 – 000120500','500','428','Active'],['INV-KF-002','Koforidua Branch','ACB Corporate','000125001 – 000125300','300','112','Active'],['INV-AB-001','Aburi Branch','ACB Standard','000130001 – 000130200','200','0','Archived'],['INV-MD-003','Madina Branch','ACB Standard','000150001 – 000150600','600','390','Active']],
 issuance:[['ISS-02631','CBR-2026-0836','Akosua Frimpong','Aburi Branch','000130042 – 000130091','Issued','23 Jul, 14:10'],['ISS-02629','CBR-2026-0828','Yaw Boateng','Nsawam Branch','000120118 – 000120167','Collected','22 Jul, 10:05'],['ISS-02628','CBR-2026-0826','Abena Nyarko','Koforidua Branch','000125044 – 000125093','Awaiting Collection','21 Jul, 16:22']],
 verifications:[['VFY-19044','000120151','AC-00129482','Ama Ofori','Nsawam Branch','₵8,450.00','Active'],['VFY-19041','000125069','AC-00773819','Kwaku Mensah','Koforidua Branch','₵15,200.00','Stopped'],['VFY-19036','000150288','AC-00902811','Bright Logistics Ltd','Madina Branch','₵4,765.00','Returned']],
 stops:[['STP-0104','000125069','Kwaku Mensah','Koforidua Branch','Lost cheque','Stopped','24 Jul, 08:55'],['CAN-0089','000120094','Nana Addo','Nsawam Branch','Customer request','Pending Authorization','23 Jul, 14:40']],
 returns:[['RET-0058','000150288','Bright Logistics Ltd','Madina Branch','Insufficient funds','₵4,765.00','Returned'],['RET-0057','000130099','Gifty Asante','Aburi Branch','Signature differs','₵2,100.00','Returned']],
 vault:[['VLT-2026-0031','Nsawam Branch','ACB Standard','000121001 – 000121500','500 leaves','Awaiting Confirmation','24 Jul, 16:10'],['VLT-2026-0030','Koforidua Branch','ACB Corporate','000126001 – 000126300','300 leaves','Awaiting Confirmation','24 Jul, 14:02'],['VLT-2026-0029','Madina Branch','ACB Standard','000151001 – 000151400','400 leaves','Awaiting Confirmation','24 Jul, 11:18'],['VLT-2026-0028','Aburi Branch','ACB Standard','000131001 – 000131200','200 leaves','Accepted','23 Jul, 10:40']],
 approvals:[['APR-0445','Cheque book request','CBR-2026-0841','Ama Ofori','Nsawam Branch','Customer Service','24 Jul, 09:42'],['APR-0444','Cheque cancellation','CAN-0089','Nana Addo','Nsawam Branch','Branch Operations','23 Jul, 14:40'],['APR-0441','Range registration','INV-MD-003','Madina Branch','Madina Branch','Branch Operations','23 Jul, 09:10']],
 audit:[['24 Jul, 09:42','Cheque book request created','CBR-2026-0841','Esi Nkrumah','Customer Service','Nsawam Branch','Initial request submitted'],['24 Jul, 08:55','Stop cheque authorised','STP-0104','Kojo Asare','Branch Manager','Koforidua Branch','Lost cheque confirmed'],['23 Jul, 15:15','Cheque book request authorised','CBR-2026-0838','Adwoa Owusu','Branch Manager','Koforidua Branch','Approved for issuance'],['23 Jul, 14:10','Cheque book issued','ISS-02631','Yaw Sarpong','Branch Operations','Aburi Branch','Identity verified']]
};
let state={logged:false,role:'Branch Operations',branch:'Nsawam Branch',page:'dashboard',toast:'',modal:null};
const app=document.querySelector('#app');
const esc=v=>String(v).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const allowed=row=>roles[state.role].global ? (state.branch==='All Branches'||row.includes(state.branch)) : row.includes(state.branch);
const badge=s=>`<span class="badge ${String(s).toLowerCase().replaceAll(' ','-')}">${esc(s)}</span>`;
function statusClass(s){return String(s).toLowerCase().replaceAll(' ','-')}
function table(headers,rows,extra=''){const visible=rows.filter(allowed);return `<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')} ${extra?'<th></th>':''}</tr></thead><tbody>${visible.length?visible.map((r,i)=>`<tr>${r.map((c,j)=>`<td>${['Status','State'].includes(headers[j])?badge(c):esc(c)}</td>`).join('')}${extra?`<td>${extra.replaceAll('{i}',i)}</td>`:''}</tr>`).join(''):`<tr><td colspan="${headers.length+1}" class="empty">No records are available within your branch scope.</td></tr>`}</tbody></table></div>`}
function can(action){return roles[state.role].actions.includes('all')||roles[state.role].actions.includes(action)}
const adminUsers=[['Akua Boateng','System Admin','All Branches','Active','24 Jul, 10:02'],['Esi Nkrumah','Customer Service','Nsawam Branch','Active','24 Jul, 09:42'],['Adwoa Owusu','Branch Manager','Koforidua Branch','Active','24 Jul, 09:30'],['Yaw Sarpong','Branch Operations','Aburi Branch','Active','23 Jul, 14:10']];
function moduleData(key){const m={request:[['Reference','Account','Customer','Branch','Book size','Status','Created'],data.requests],inventory:[['Reference','Branch','Book type','Serial range','Total','Available','Status'],data.inventory],issuance:[['Reference','Request','Customer','Branch','Serial range','Status','Processed'],data.issuance],verification:[['Reference','Cheque no.','Account','Customer','Branch','Amount','Status'],data.verifications],stop:[['Reference','Cheque no.','Customer','Branch','Reason','Status','Submitted'],data.stops],returns:[['Reference','Cheque no.','Customer','Branch','Reason','Amount','Status'],data.returns],authorization:[['Queue ID','Transaction','Reference','Customer / Subject','Branch','Maker','Submitted'],data.approvals],vault:[['Reference','Destination branch','Book type','Serial range','Quantity','Status','Dispatched'],data.vault||[]],admin:[['User','Role','Assigned branch','Status','Last active'],adminUsers]};return m[key]?{headers:m[key][0],rows:m[key][1]}:null}
function toast(msg){state.toast=msg;render();setTimeout(()=>{state.toast='';render()},2600)}
function login(){return `<section class="login"><div class="login-hero"><div class="seal">ACB</div><div class="login-tag">✦ Secure banking operations</div><h1>Cheque management, with control at every step.</h1><p>One secure workspace for inventory, issuance, verification and authorisation across every Akuapem Community Bank branch.</p></div><div class="login-panel"><div class="login-card"><div class="bank-mark"><div class="mark-icon">ACB</div><div>Akuapem Community Bank PLC<br><span>CHEQUE MANAGEMENT SYSTEM</span></div></div><h2>Welcome back</h2><p class="sub">Sign in to your secure operations workspace.</p><div class="field"><label>Staff ID or Email</label><input value="ops.nsawam@acb.com" /></div><div class="field"><label>Role for prototype</label><select id="login-role">${Object.keys(roles).map(r=>`<option ${r===state.role?'selected':''}>${r}</option>`).join('')}</select></div><div class="field"><label>Assigned branch</label><select id="login-branch">${branches.map(b=>`<option ${b===state.branch?'selected':''}>${b}</option>`).join('')}</select></div><button class="primary" onclick="signIn()">Sign in securely →</button><p class="hint">Prototype access only · MFA and SSO are represented in the production design.</p></div></div></section>`}
function sidebar(){return `<aside class="sidebar"><div class="brand"><div class="brand-logo">ACB</div><div><b>Akuapem Community<br>Bank PLC</b><br><span>CHEQUE MANAGEMENT</span></div></div><div class="nav-label">WORKSPACE</div>${nav.slice(0,-3).map(n=>`<button class="nav-btn ${state.page===n[0]?'active':''}" onclick="go('${n[0]}')"><b>${n[1]}</b><span>${n[2]}</span></button>`).join('')}<div class="nav-label">GOVERNANCE</div>${nav.slice(-3).map(n=>`<button class="nav-btn ${state.page===n[0]?'active':''}" onclick="go('${n[0]}')"><b>${n[1]}</b><span>${n[2]}</span></button>`).join('')}<div class="sidebar-foot">Secure session<br>v1.0 Prototype</div></aside>`}
function topbar(){let global=roles[state.role].global;return `<header class="topbar"><button class="ghost mobile-menu" onclick="document.querySelector('.sidebar').classList.toggle('open')">☰</button><span class="scope-pill">${global?'Global view · all six branches':`Branch view · ${state.branch}`}</span><div class="top-controls"><select onchange="setBranch(this.value)" ${global?'':'disabled'}>${global?'<option value="All Branches">All branches</option>':''}${branches.map(b=>`<option ${b===state.branch?'selected':''}>${b}</option>`).join('')}</select><div class="user-block"><div class="avatar">${roles[state.role].initials}</div><div><div class="user-name">${state.role==='Branch Operations'?'Yaw Sarpong':state.role}</div><div class="user-role">${state.role}</div></div></div><button class="ghost" onclick="logout()">Sign out</button></div></header>`}
function shell(content,title,eyebrow='OPERATIONS'){return `<div class="app-shell">${sidebar()}<div class="content">${topbar()}<div class="page-wrap"><div class="title-row"><div><div class="eyebrow">${eyebrow}</div><h1>${title}</h1></div></div>${content}</div></div></div>${state.modal?modal():''}${state.toast?`<div class="toast">✓ ${state.toast}</div>`:''}`}
function dashboard(){const records=data.requests.filter(allowed);return shell(`<div class="grid kpis"><div class="card kpi"><div><div class="kpi-label">Pending authorisations</div><strong>${can('approve')?'12':'4'}</strong><small>Requires review</small></div><div class="metric-icon gold">◉</div></div><div class="card kpi"><div><div class="kpi-label">Active cheque books</div><strong>${roles[state.role].global?'1,284':'214'}</strong><small>Across ${roles[state.role].global?'six branches':'your branch'}</small></div><div class="metric-icon green">▤</div></div><div class="card kpi"><div><div class="kpi-label">Issued this month</div><strong>${roles[state.role].global?'326':'47'}</strong><small>Cheque books</small></div><div class="metric-icon">▣</div></div><div class="card kpi"><div><div class="kpi-label">Stop-cheque alerts</div><strong>3</strong><small>Action required</small></div><div class="metric-icon red">⊘</div></div></div><div class="grid dashboard-mid"><section class="card"><div class="card-head"><div><h3>Cheque book issuance trend</h3><small>Last six months</small></div><span class="badge authorized">+12.4%</span></div><div class="chart">${[42,58,47,72,65,89].map((n,i)=>`<div class="bar" style="height:${n}%" data-month="${['Feb','Mar','Apr','May','Jun','Jul'][i]}"></div>`).join('')}</div><div class="chart-note"><i class="dot"></i> Cheque books issued</div></section><section class="card"><div class="card-head"><div><h3>Priority alerts</h3><small>Exceptions needing attention</small></div><button class="ghost" onclick="go('authorization')">View all</button></div><div class="alert"><div class="alert-icon">⚠</div><div><b>4 requests awaiting authorisation</b><p>Oldest request: 1 hour 28 minutes.</p></div></div><div class="alert"><div class="alert-icon">⊘</div><div><b>Stop-cheque request submitted</b><p>Koforidua · Cheque 000125069</p></div></div><div class="alert"><div class="alert-icon">↩</div><div><b>Returned cheque requires review</b><p>Madina · Insufficient funds</p></div></div></section></div><div class="grid bottom-grid"><section class="card wide-card"><div class="card-head"><div><h3>Recent cheque book requests</h3><small>Live activity within your scope</small></div><button class="ghost" onclick="go('request')">Manage requests</button></div>${table(['Reference','Account','Customer','Branch','Book','Status','Created'],records)}</section><section class="card"><div class="card-head"><div><h3>Quick actions</h3><small>Common operations</small></div></div><div class="quick"><button onclick="go('request')">＋ New request<span>Initiate cheque book request</span></button><button onclick="go('verification')">✓ Verify cheque<span>Check live cheque status</span></button><button onclick="go('inventory')">▤ Register range<span>Add inventory serial range</span></button><button onclick="go('authorization')">◉ Review queue<span>Maker-checker approvals</span></button></div></section></div>`,`Overview`)}
function modulePage(key,title,headers,rows,opts={}){const create=opts.create;const action=opts.action;return shell(`<div class="module-toolbar"><div class="filters"><input class="search" placeholder="Search ${title.toLowerCase()}" oninput="filterTable(this.value)"><span class="module-summary">Showing <strong>${rows.filter(allowed).length}</strong> records</span></div>${create&&can(create.permission||'create')?`<button class="primary" onclick="openForm('${key}')">${create.label}</button>`:''}</div><section class="card wide-card"><div class="card-head"><div><h3>${title}</h3><small>${roles[state.role].global?'All branches':'Your assigned branch only'}</small></div></div>${table(headers,rows,action?`<button class="ghost row-action" onclick="rowAction('${key}',{i})">${action}</button>`:'')}</section>`,title,opts.eyebrow||'CHEQUE OPERATIONS')}
function customers(){return shell(`<div class="card form-card"><div class="card-head"><div><h3>Find a customer or account</h3><small>Search by customer name, account number, or cheque number.</small></div></div><div class="form-grid"><div class="field"><label>Search term</label><input id="customer-search" placeholder="e.g. AC-00129482 or Ama Ofori" /></div><div class="field"><label>Search type</label><select><option>Customer or account</option><option>Cheque number</option></select></div></div><div class="form-actions"><button class="primary" onclick="customerResult()">Search records</button></div></div><div id="customer-result"></div>`,`Customer & Account Search`,'CUSTOMER SERVICE')}
function branchField(){const global=roles[state.role].global;const current=branches.includes(state.branch)?state.branch:branches[0];return global?`<select data-field="branch">${branches.map(b=>`<option ${b===current?'selected':''}>${b}</option>`).join('')}</select>`:`<input data-field="branch" value="${esc(state.branch)}" readonly>`}
function form(key){const cfg={request:['New Cheque Book Request','Collection branch',[['account','Customer account','AC-00129482'],['customer','Customer name','Ama Ofori'],['book','Book size','50 leaves'],['reason','Reason','New account cheque book']]],inventory:['Register Cheque Range','Branch',[['type','Cheque book type','ACB Standard'],['start','Start serial','000160001'],['end','End serial','000160500'],['supplier','Supplier / batch','SecurePrint Ghana Ltd']]],issuance:['Issue Cheque Book','Issuing branch',[['request','Approved request reference','CBR-2026-0841'],['account','Customer account','AC-00129482'],['range','Cheque serial range','000120151 – 000120200'],['method','Collection method','In-person collection'],['verifier','Identity verified by','Yaw Sarpong']]],stop:['Stop / Cancel Cheque','Branch',[['cheque','Cheque number','000120151'],['account','Customer account','AC-00129482'],['instruction','Instruction type','Stop cheque'],['reason','Reason','Lost cheque'],['remarks','Remarks','Customer instruction recorded.']]],returns:['Record Returned Cheque','Branch',[['cheque','Cheque number','000150288'],['account','Account number','AC-00902811'],['reason','Return reason','Insufficient funds'],['amount','Cheque amount','₵4,765.00'],['remarks','Remarks','Return instrument received.']]]}[key];if(!cfg)return '';const [title,branchLabel,fields]=cfg;return shell(`<section class="card form-card"><div class="card-head"><div><h3>${title}</h3><small>Transactions are captured by a maker and routed for authorisation when required.</small></div></div><div class="notice">You are operating within <b>${roles[state.role].global?'the selected global scope':state.branch}</b>. All actions will be logged with your role, date and time.</div><form id="txn-form" onsubmit="return false" class="form-grid"><div class="field"><label>${branchLabel}</label>${branchField()}</div>${fields.map(([k,l,v])=>`<div class="field"><label>${l}</label><input data-field="${k}" value="${esc(v)}"></div>`).join('')}</form><div class="form-actions"><button class="ghost" onclick="go('${key}')">Cancel</button><button class="primary" onclick="submitForm('${key}')">Submit ${key==='issuance'?'issuance':key==='returns'?'return record':'for authorisation'} →</button></div></section>`,title,'NEW TRANSACTION')}
function authorization(){if(!can('approve')) return shell(`<div class="denied"><b>Authorisation queue restricted</b><br>Your ${state.role} profile can submit transactions but cannot approve them. Please contact your Branch Manager or Head Office.</div>`,`Authorization Queue`,'MAKER–CHECKER CONTROL');return modulePage('authorization','Authorization Queue',['Queue ID','Transaction','Reference','Customer / Subject','Branch','Maker','Submitted'],data.approvals,{action:'Review',eyebrow:'MAKER–CHECKER CONTROL'})}
function reports(){return shell(`<div class="grid kpis"><div class="card kpi"><div><div class="kpi-label">Requests processed</div><strong>326</strong><small>July 2026</small></div><div class="metric-icon">▥</div></div><div class="card kpi"><div><div class="kpi-label">Average approval time</div><strong>42m</strong><small>Within target</small></div><div class="metric-icon green">✓</div></div><div class="card kpi"><div><div class="kpi-label">Returned cheque value</div><strong>₵18.6k</strong><small>Month to date</small></div><div class="metric-icon red">↩</div></div><div class="card kpi"><div><div class="kpi-label">Audit events</div><strong>1,942</strong><small>Month to date</small></div><div class="metric-icon gold">◷</div></div></div><section class="card wide-card"><div class="card-head"><div><h3>Operational reports</h3><small>Downloadable reports are filtered to your permitted branch scope.</small></div></div>${table(['Report','Period','Scope','Last generated','State'],[['Cheque book inventory reconciliation','July 2026',roles[state.role].global?'All branches':state.branch,'24 Jul, 09:00','Ready'],['Pending authorisation ageing','Live',roles[state.role].global?'All branches':state.branch,'24 Jul, 10:15','Ready'],['Returned cheque register','July 2026',roles[state.role].global?'All branches':state.branch,'24 Jul, 08:30','Ready'],['Stop-cheque instruction register','July 2026',roles[state.role].global?'All branches':state.branch,'24 Jul, 09:30','Ready']],`<button class="ghost" onclick="toast('Report download prepared')">Download</button>`)}</section>`,`Reports & Insights`,'MANAGEMENT INFORMATION')}
function admin(){if(!can('manage'))return shell(`<div class="denied"><b>Administration restricted</b><br>Only System Administrators and authorized Head-Office users can manage users, roles, branches and configurations.</div>`,`Administration`,'SYSTEM GOVERNANCE');return modulePage('admin','Users, Roles & Branches',['User','Role','Assigned branch','Status','Last active'],adminUsers,{create:{label:'＋ Add user',permission:'manage'},action:'Manage',eyebrow:'SYSTEM GOVERNANCE'})}
function audit(){return modulePage('audit','Complete Audit Trail',['Date & time','Action','Reference','Maker','Role','Branch','Remarks'],data.audit,{eyebrow:'COMPLIANCE & ACCOUNTABILITY'})}
function leaves(v){return parseInt(String(v).replace(/[^0-9]/g,''),10)||0}
function canAcceptVault(){return roles[state.role].global||['Branch Manager','Branch Operations'].includes(state.role)}
function cylinder(fill,cls,pctLabel,side){return `<div class="cylinder ${cls}" role="button" tabindex="0" title="Click to view all ${side==='vault'?'vault batches':'inventory ranges'}" onclick="openStock('${side}')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();openStock('${side}')}"><div class="cyl-rim"></div><div class="cyl-glass"><div class="cyl-liquid" style="height:${Math.min(100,Math.max(fill,4))}%"><span class="cyl-surface"></span></div></div><div class="cyl-pct">${pctLabel}</div><div class="cyl-hint">View details</div></div>`}
function openStock(side){state.modal={type:'stock',side};render()}
function stockModal(){const isVault=state.modal.side==='vault';const headers=isVault?['Reference','Destination branch','Book type','Serial range','Quantity','Status','Dispatched']:['Reference','Branch','Book type','Serial range','Total','Available','Status'];const rows=isVault?(data.vault||[]):data.inventory;const title=isVault?'Head-Office Vault — cheque stock':'Branch Inventory — cheque ranges';const sub=isVault?'Every cheque batch held in the vault, with its serial range and reconciliation status.':'Every registered cheque serial range currently available in branch inventory.';const count=rows.filter(allowed).length;return `<div class="modal-backdrop"><div class="modal stock-modal"><h2>${title}</h2><p>${sub} Showing <b>${count}</b> record${count===1?'':'s'} in your scope.</p>${table(headers,rows)}<div class="modal-actions"><button class="ghost" onclick="state.modal=null;render()">Close</button></div></div></div>`}
function vault(){const vaultRows=(data.vault||[]).filter(allowed);const awaiting=vaultRows.filter(v=>v[5]==='Awaiting Confirmation');const invRows=data.inventory.filter(allowed);const awaitingLeaves=awaiting.reduce((n,v)=>n+leaves(v[4]),0);const invLeaves=invRows.reduce((n,v)=>n+leaves(v[5]),0);const cap=Math.max(awaitingLeaves+invLeaves,1);const leftFill=Math.round(awaitingLeaves/cap*100);const rightFill=Math.round(invLeaves/cap*100);const canPush=roles[state.role].global;const transferReady=(canAcceptVault()&&awaiting.length)||canPush;const stage=`<div class="vault-stage"><div class="vault-side">${cylinder(leftFill,'from-ho',awaitingLeaves.toLocaleString(),'vault')}<div class="vault-cap"><b>Head-Office Vault</b><span>${awaiting.length} batch${awaiting.length===1?'':'es'} · ${awaitingLeaves.toLocaleString()} leaves awaiting confirmation</span></div></div><div class="vault-mid"><button class="vault-transfer" ${transferReady?'':'disabled'} onclick="openVault()" title="Move cheque stock between the vault and inventory">⇄</button><span class="vault-mid-label">Move in / out</span><span class="vault-mid-sub">Vault ↔ Inventory</span></div><div class="vault-side">${cylinder(rightFill,'to-inv',invLeaves.toLocaleString(),'inventory')}<div class="vault-cap"><b>Branch Inventory</b><span>${invRows.length} active range${invRows.length===1?'':'s'} · ${invLeaves.toLocaleString()} leaves available</span></div></div></div>`;const legend=`<div class="vault-legend"><span><i class="swatch gold"></i> Awaiting branch confirmation — hard copies not yet reconciled</span><span><i class="swatch blue"></i> Reconciled and accepted into branch inventory</span></div>`;const toolbar=`<div class="module-toolbar"><span class="module-summary">Showing <strong>${vaultRows.length}</strong> vault batches</span>${canPush?`<button class="primary" onclick="openVault()">＋ Dispatch to vault</button>`:canAcceptVault()&&awaiting.length?`<button class="primary" onclick="openVault()">Reconcile &amp; accept</button>`:''}</div>`;const list=`<section class="card wide-card"><div class="card-head"><div><h3>Vault batches</h3><small>Cheque stock dispatched from head office to ${roles[state.role].global?'all branch vaults':'your branch vault'}</small></div></div>${table(['Reference','Destination branch','Book type','Serial range','Quantity','Status','Dispatched'],data.vault||[],`<button class="ghost row-action" onclick="rowAction('vault',{i})">View</button>`)}</section>`;return shell(stage+legend+toolbar+list,'Vault & Reconciliation','SECURE STOCK CONTROL')}
function vaultModal(){const canPush=roles[state.role].global;const canAccept=canAcceptVault();const awaiting=(data.vault||[]).filter(allowed).filter(v=>v[5]==='Awaiting Confirmation');const branchSel=roles[state.role].global?`<select data-field="branch">${branches.map(b=>`<option ${b===(branches.includes(state.branch)?state.branch:branches[0])?'selected':''}>${b}</option>`).join('')}</select>`:`<input data-field="branch" value="${esc(state.branch)}" readonly>`;const receive=canAccept?`<div class="vault-section"><h4>⬇ Receive into branch inventory</h4><p class="sub">Reconcile the physical hard copies against each vault record, then accept it into inventory.</p>${awaiting.length?awaiting.map(v=>`<div class="vault-item"><div class="vault-item-info"><b>${esc(v[0])}</b><span>${esc(v[1])} · ${esc(v[2])} · ${esc(v[3])} · ${esc(v[4])}</span></div><label class="vault-chk"><input type="checkbox" onchange="this.closest('.vault-item').querySelector('.accept-btn').disabled=!this.checked"> Hard copies received &amp; reconciled</label><button class="primary accept-btn" disabled onclick="acceptVault('${esc(v[0])}')">Accept →</button></div>`).join(''):`<p class="empty-note">No batches are awaiting confirmation in your scope.</p>`}</div>`:'';const dispatch=canPush?`<div class="vault-section"><h4>⬆ Dispatch from head office</h4><p class="sub">Register printed cheque stock and push it to a branch vault for confirmation.</p><form id="vault-push-form" onsubmit="return false" class="form-grid"><div class="field"><label>Destination branch</label>${branchSel}</div><div class="field"><label>Cheque book type</label><input data-field="type" value="ACB Standard"></div><div class="field"><label>Start serial</label><input data-field="start" value="000180001"></div><div class="field"><label>End serial</label><input data-field="end" value="000180500"></div></form><div class="form-actions"><button class="primary" onclick="pushVault()">Push to branch vault →</button></div></div>`:'';return `<div class="modal-backdrop"><div class="modal vault-modal"><h2>Vault transfer</h2><p>Move cheque stock between the head-office vault and branch inventory. Every movement is recorded in the audit trail.</p>${receive}${dispatch}${!receive&&!dispatch?'<p class="empty-note">Your role has no vault transfer permissions.</p>':''}<div class="modal-actions"><button class="ghost" onclick="state.modal=null;render()">Close</button></div></div></div>`}
function page(){if(state.page==='vault')return vault();if(state.page==='dashboard')return dashboard();if(state.page.endsWith('-new')&&['request','inventory','issuance','stop','returns'].includes(state.page.replace('-new','')))return form(state.page.replace('-new',''));const maps={request:['Cheque Book Requests',['Reference','Account','Customer','Branch','Book size','Status','Created'],data.requests,{create:{label:'＋ New request'},action:'View'}],inventory:['Cheque Book Inventory & Ranges',['Reference','Branch','Book type','Serial range','Total','Available','Status'],data.inventory,{create:{label:'＋ Register range'},action:'View'}],issuance:['Issuance & Collection',['Reference','Request','Customer','Branch','Serial range','Status','Processed'],data.issuance,{create:{label:'＋ Issue cheque book'},action:'View'}],verification:['Cheque Verification',['Reference','Cheque no.','Account','Customer','Branch','Amount','Status'],data.verifications,{}],stop:['Stop / Cancel Cheque Requests',['Reference','Cheque no.','Customer','Branch','Reason','Status','Submitted'],data.stops,{create:{label:'＋ New instruction'},action:'View'}],returns:['Returned / Dishonoured Cheques',['Reference','Cheque no.','Customer','Branch','Reason','Amount','Status'],data.returns,{create:{label:'＋ Record return'},action:'View'}]};if(maps[state.page])return modulePage(state.page,...maps[state.page]);if(state.page==='customers')return customers();if(state.page==='authorization')return authorization();if(state.page==='reports')return reports();if(state.page==='admin')return admin();if(state.page==='audit')return audit();return dashboard()}
function modal(){const m=state.modal;if(m.type==='vault')return vaultModal();if(m.type==='stock')return stockModal();if(m.type==='detail'){const rows=m.headers.map((h,i)=>`<div class="detail-row"><span>${esc(h)}</span><b>${['Status','State'].includes(h)?badge(m.row[i]):esc(m.row[i])}</b></div>`).join('');return `<div class="modal-backdrop"><div class="modal"><h2>${esc(m.row[0])}</h2><p>Read-only record detail within your permitted branch scope.</p><div class="detail-list">${rows}</div><div class="modal-actions"><button class="primary" onclick="state.modal=null;render()">Close</button></div></div></div>`}const approve=m.type==='approve';return `<div class="modal-backdrop"><div class="modal"><h2>${approve?'Authorise transaction?':'Confirm submission'}</h2><p>${approve?'This will authorise the oldest transaction in the queue. The approval will be recorded with your name, role, branch, and timestamp.':'This transaction will be captured and routed for maker-checker authorisation, and recorded in the audit trail.'}</p><div class="field"><label>${approve?'Authorisation remarks':'Remarks (optional)'}</label><textarea rows="3" placeholder="Add a comment for the audit record"></textarea></div><div class="modal-actions"><button class="ghost" onclick="state.modal=null;render()">Cancel</button><button class="primary" onclick="confirmModal()">${approve?'Confirm authorisation':'Confirm submission'}</button></div></div></div>`}
function render(){app.innerHTML=state.logged?page():login()}
function go(p){state.page=p;render()}
async function signIn(){const role=document.querySelector('#login-role').value;const branch=document.querySelector('#login-branch').value;if(location.protocol==='file:'){state.role=role;state.branch=branch;state.logged=true;return render()}try{const r=await fetch('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role,branch})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Sign-in failed.');data=j.data;state.role=j.role;state.branch=j.branch;state.logged=true;render()}catch(e){alert(e.message||'Unable to sign in.')}}
async function logout(){try{if(location.protocol!=='file:')await fetch('/api/logout',{method:'POST'})}catch(e){}state.logged=false;state.modal=null;render()}
function setBranch(v){state.branch=v==='All Branches'?'All Branches':v;render()}
function openForm(k){state.page=k+'-new';render()}
function submitForm(k){const fields={};document.querySelectorAll('#txn-form [data-field]').forEach(el=>{fields[el.dataset.field]=el.value.trim()});state.modal={type:'submit',key:k,fields};render()}
function rowAction(k,i){if(k==='authorization'){state.modal={type:'approve',key:k,index:i};render();return}const md=moduleData(k);if(!md)return;const row=md.rows.filter(allowed)[i];if(!row)return;state.modal={type:'detail',key:k,headers:md.headers,row};render()}
async function confirmModal(){const m=state.modal;const k=m.key;const fields=m.fields||{};state.modal=null;try{if(location.protocol!=='file:'){const endpoint=k==='authorization'?'/api/authorizations/approve':'/api/transactions';const payload=k==='authorization'?{role:state.role,branch:state.branch}:{module:k,role:state.role,branch:state.branch,fields};const result=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const json=await result.json().catch(()=>({}));if(!result.ok)throw new Error(json.error||'The request was rejected.');data=json.data}else if(k==='authorization'){data.approvals.shift()}toast(k==='authorization'?'Transaction authorised and recorded in audit trail.':'Transaction submitted for authorisation.');if(k!=='authorization')state.page=k}catch(error){toast(error.message||'Unable to save. Please try again.')}render()}
function openVault(){state.modal={type:'vault'};render()}
async function acceptVault(ref){try{const r=await fetch('/api/vault/accept',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:state.role,branch:state.branch,ref})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Unable to accept batch.');data=j.data;state.modal=null;toast('Batch reconciled and moved into branch inventory.')}catch(e){toast(e.message||'Unable to accept batch.')}render()}
async function pushVault(){const fields={};document.querySelectorAll('#vault-push-form [data-field]').forEach(el=>{fields[el.dataset.field]=el.value.trim()});try{const r=await fetch('/api/vault/push',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({role:state.role,branch:state.branch,fields})});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||'Unable to dispatch batch.');data=j.data;state.modal=null;toast('Cheque stock dispatched to branch vault, awaiting confirmation.')}catch(e){toast(e.message||'Unable to dispatch batch.')}render()}
function filterTable(v){document.querySelectorAll('tbody tr').forEach(row=>row.style.display=row.innerText.toLowerCase().includes(v.toLowerCase())?'':'none')}
function customerResult(){const term=document.querySelector('#customer-search').value||'Ama Ofori';document.querySelector('#customer-result').innerHTML=`<section class="card" style="margin-top:18px"><div class="card-head"><div><h3>Customer profile</h3><small>Verified banking profile</small></div>${badge('Active')}</div><div class="form-grid"><div><b>Ama Ofori</b><p class="sub">Account: AC-00129482<br>Branch: Nsawam Branch<br>Customer type: Individual</p></div><div><b>Cheque standing</b><p class="sub">Active book: 000120151 – 000120200<br>Outstanding requests: 1<br>Stop-cheque instructions: 0</p></div></div></section>`}
async function bootstrap(){try{if(location.protocol!=='file:'){const response=await fetch('/api/state');if(response.ok){const j=await response.json();data=j.data;if(j.role){state.role=j.role;state.branch=j.branch;state.logged=true}}}}catch(error){console.info('Running with local demonstration data.')}render()}
bootstrap();
