const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const db = require('./db.js');

const root = __dirname;
const PERMISSIONS = [
  { id: 'request.create', label: 'Create cheque book request', cat: 'Transactions' },
  { id: 'inventory.create', label: 'Register inventory range', cat: 'Transactions' },
  { id: 'issuance.create', label: 'Issue cheque book', cat: 'Transactions' },
  { id: 'txn.authorise', label: 'Authorise transactions', cat: 'Transactions' },
  { id: 'vault.dispatch', label: 'Dispatch stock to branch vault', cat: 'Vault' },
  { id: 'vault.submit', label: 'Reconcile & submit vault stock', cat: 'Vault' },
  { id: 'vault.authorise', label: 'Authorise vault into inventory', cat: 'Vault' },
  { id: 'notifications.view', label: 'View customer alerts', cat: 'Customer' },
  { id: 'customers.view', label: 'Search customer database', cat: 'Customer' },
  { id: 'customers.manage', label: 'Import & manage customer database', cat: 'Customer' },
  { id: 'reports.view', label: 'View reports', cat: 'Reporting' },
  { id: 'audit.view', label: 'View audit trail', cat: 'Reporting' },
  { id: 'logs.view', label: 'View system & security logs', cat: 'Reporting' },
  { id: 'admin.manage', label: 'Manage users, roles & groups', cat: 'Administration' },
  { id: 'admin.authorise', label: 'Authorise administrative changes', cat: 'Administration' }
];
const PERM_IDS = PERMISSIONS.map(p => p.id);
const seed = {
  requests: [['CBR-2026-0841','AC-00129482','Ama Ofori','Nsawam Branch','50 leaves','Pending Authorization','24 Jul, 09:42'],['CBR-2026-0838','AC-00773819','Kwaku Mensah','Koforidua Branch','100 leaves','Authorized','23 Jul, 15:15'],['CBR-2026-0836','AC-00359510','Akosua Frimpong','Aburi Branch','50 leaves','Issued','23 Jul, 11:30'],['CBR-2026-0833','AC-00902811','Bright Logistics Ltd','Madina Branch','100 leaves','Rejected','22 Jul, 16:21']],
  inventory: [['INV-NS-001','Nsawam Branch','ACB Standard','000120001 – 000120500','500','428','Active'],['INV-KF-002','Koforidua Branch','ACB Corporate','000125001 – 000125300','300','112','Active'],['INV-AB-001','Aburi Branch','ACB Standard','000130001 – 000130200','200','0','Archived'],['INV-MD-003','Madina Branch','ACB Standard','000150001 – 000150600','600','390','Active']],
  issuance: [['ISS-02631','CBR-2026-0836','Akosua Frimpong','Aburi Branch','000130042 – 000130091','Issued','23 Jul, 14:10'],['ISS-02629','CBR-2026-0828','Yaw Boateng','Nsawam Branch','000120118 – 000120167','Collected','22 Jul, 10:05'],['ISS-02628','CBR-2026-0826','Abena Nyarko','Koforidua Branch','000125044 – 000125093','Awaiting Collection','21 Jul, 16:22']],
  verifications: [], stops: [], returns: [], destructions: [],
  vault: [['VLT-2026-0031','Nsawam Branch','ACB Standard','000121001 – 000121500','500 leaves','Awaiting Confirmation','24 Jul, 16:10'],['VLT-2026-0030','Koforidua Branch','ACB Corporate','000126001 – 000126300','300 leaves','Awaiting Confirmation','24 Jul, 14:02'],['VLT-2026-0029','Madina Branch','ACB Standard','000151001 – 000151400','400 leaves','Awaiting Confirmation','24 Jul, 11:18'],['VLT-2026-0027','Koforidua Branch','ACB Standard','000127001 – 000127200','200 leaves','Pending Authorisation','24 Jul, 08:20'],['VLT-2026-0028','Aburi Branch','ACB Standard','000131001 – 000131200','200 leaves','Accepted','23 Jul, 10:40']],
  vaultMeta: {'VLT-2026-0027':{maker:'Kojo Asare',makerRole:'Branch Operations','submitted':'24 Jul, 08:20'}},
  approvals: [['APR-0445','Cheque book request','CBR-2026-0841','Ama Ofori','Nsawam Branch','Esi Nkrumah','24 Jul, 09:42'],['APR-0444','Cheque cancellation','CAN-0089','Nana Addo','Nsawam Branch','Kwabena Osei','23 Jul, 14:40'],['APR-0441','Range registration','INV-MD-003','Madina Branch','Yaa Serwaa','23 Jul, 09:10']],
  approvalMeta: {'APR-0445':{bucket:'requests',ref:'CBR-2026-0841',statusIdx:5,finalStatus:'Authorized',maker:'Esi Nkrumah',makerRole:'Customer Service'},'APR-0444':{bucket:'stops',ref:'CAN-0089',statusIdx:5,finalStatus:'Cancelled',maker:'Kwabena Osei',makerRole:'Branch Operations'},'APR-0441':{bucket:'inventory',ref:'INV-MD-003',statusIdx:6,finalStatus:'Active',maker:'Yaa Serwaa',makerRole:'Branch Operations'}},
  audit: [['24 Jul, 09:42','Cheque book request created','CBR-2026-0841','Esi Nkrumah','Customer Service','Nsawam Branch','Initial request submitted'],['24 Jul, 08:55','Stop cheque authorised','STP-0104','Kojo Asare','Branch Manager','Koforidua Branch','Lost cheque confirmed'],['23 Jul, 15:15','Cheque book request authorised','CBR-2026-0838','Adwoa Owusu','Branch Manager','Koforidua Branch','Approved for issuance'],['23 Jul, 14:10','Cheque book issued','ISS-02631','Yaw Sarpong','Branch Operations','Aburi Branch','Identity verified']],
  roles: {
    'System Admin': { label: 'System Admin', global: true, system: true, permissions: ['admin.manage','admin.authorise','audit.view','logs.view','reports.view','customers.view','customers.manage'] },
    'Head-Office Users': { label: 'Head-Office Users', global: true, system: true, permissions: ['txn.authorise','vault.dispatch','vault.authorise','reports.view','audit.view','logs.view','notifications.view','customers.view','customers.manage','admin.authorise'] },
    'Branch Manager': { label: 'Branch Manager', global: false, system: true, permissions: ['txn.authorise','vault.authorise','reports.view','audit.view','notifications.view','customers.view'] },
    'Branch Operations': { label: 'Branch Operations', global: false, system: true, permissions: ['request.create','inventory.create','issuance.create','vault.submit','notifications.view','customers.view'] },
    'Customer Service': { label: 'Customer Service', global: false, system: true, permissions: ['request.create','reports.view','notifications.view','customers.view'] }
  },
  groups: {
    'Koforidua Operations': { description: 'Koforidua branch operations team', branch: 'Koforidua Branch', roles: ['Branch Operations'] },
    'Head Office Controllers': { description: 'Head-office transaction authorisers', branch: 'All Branches', roles: ['Head-Office Users'] }
  },
  directory: {
    'admin@acb.com': { name: 'Akua Boateng', branch: 'All Branches', role: 'System Admin', groups: [], status: 'Active', lastReviewed: '01 Jul, 09:00' },
    'headoffice@acb.com': { name: 'Kofi Mensah', branch: 'All Branches', role: 'Head-Office Users', groups: [], status: 'Active', lastReviewed: '01 Jul, 09:00' },
    'manager.koforidua@acb.com': { name: 'Adwoa Owusu', branch: 'Koforidua Branch', role: 'Branch Manager', groups: [], status: 'Active', lastReviewed: '01 Jul, 09:00' },
    'ops.nsawam@acb.com': { name: 'Yaw Sarpong', branch: 'Nsawam Branch', role: 'Branch Operations', groups: [], status: 'Active', lastReviewed: '01 Jul, 09:00' },
    'cs.nsawam@acb.com': { name: 'Esi Nkrumah', branch: 'Nsawam Branch', role: 'Customer Service', groups: [], status: 'Active', lastReviewed: '01 Jul, 09:00' }
  },
  branches: ['Nsawam Branch','Koforidua Branch','Aburi Branch','Adukrom Branch','Mamfe Branch','Madina Branch'],
  sodMatrix: [['request.create','txn.authorise'],['inventory.create','txn.authorise'],['issuance.create','txn.authorise'],['vault.submit','vault.authorise']],
  adminQueue: [],
  adminAudit: [['01 Jul, 09:00','System','Directory seeded','—','5 users, 5 roles, 2 groups provisioned']],
  notifications: [['NTF-100231','Akosua Frimpong','AC-00359510','Aburi Branch','SMS','Your cheque book 000130042 – 000130091 is ready for collection at Aburi Branch. Please bring valid photo ID.','Sent','23 Jul, 14:12'],['NTF-100228','Kwaku Mensah','AC-00773819','Koforidua Branch','SMS','Cheque stock has arrived at Koforidua Branch — your requested cheque book is being prepared for collection.','Sent','22 Jul, 10:06']],
  requestPhones: {'CBR-2026-0841':'233244000111','CBR-2026-0838':'233201234567','CBR-2026-0836':'233209876543'},
  vaultItems: [['VIT-2026-0012','Kwaku Mensah','AC-00773819','233201234567','Koforidua Branch','CBR-2026-0838','Awaiting Confirmation','24 Jul, 15:00'],['VIT-2026-0009','Akosua Frimpong','AC-00359510','233209876543','Aburi Branch','CBR-2026-0836','Ready for Collection','23 Jul, 12:20']]
};

// ---- App state (the operational buckets) stored as one JSONB row ----
async function load(){
  const rows = await db.query('select data from app_state where id=1');
  if(!rows.length){ await db.query('insert into app_state(id,data) values(1,$1) on conflict(id) do nothing',[JSON.stringify(seed)]); return JSON.parse(JSON.stringify(seed)); }
  const data = rows[0].data; let changed=false;
  for(const k in seed) if(data[k]===undefined){ data[k]=seed[k]; changed=true; }
  if(changed) await save(data);
  return data;
}
async function save(data){
  await db.query('insert into app_state(id,data) values(1,$1) on conflict(id) do update set data=excluded.data',[JSON.stringify(data)]);
}

const securityHeaders={'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Permissions-Policy':'geolocation=(), microphone=(), camera=(), payment=()','Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Resource-Policy':'same-origin','Strict-Transport-Security':'max-age=31536000; includeSubDomains','Content-Security-Policy':"default-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self' 'unsafe-inline'; connect-src 'self'"};
function clientIp(req){return (req.headers['x-forwarded-for']||'').split(',')[0].trim()||req.socket.remoteAddress||'unknown'}
function send(res,status,body){res.writeHead(status,{...securityHeaders,'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(body))}
const MAX_BODY=32*1024;
function collect(req){if(req.body!==undefined&&req.body!==null){const b=req.body;if(typeof b==='object'&&!Buffer.isBuffer(b))return Promise.resolve(b);try{return Promise.resolve(JSON.parse((Buffer.isBuffer(b)?b.toString('utf8'):String(b))||'{}'))}catch{return Promise.reject(new Error('Malformed JSON'))}}return new Promise((resolve,reject)=>{let raw='';let size=0;let over=false;req.on('data',c=>{if(over)return;size+=c.length;if(size>MAX_BODY){over=true;reject(new Error('Payload too large'))}else raw+=c});req.on('end',()=>{if(over)return;try{resolve(JSON.parse(raw||'{}'))}catch{reject(new Error('Malformed JSON'))}});req.on('error',()=>{if(!over)reject(new Error('Stream error'))})})}
function collectText(req,maxBytes){if(req.body!==undefined&&req.body!==null){const b=req.body;return Promise.resolve(Buffer.isBuffer(b)?b.toString('utf8'):(typeof b==='string'?b:JSON.stringify(b)))}return new Promise((resolve,reject)=>{const chunks=[];let size=0,over=false;req.on('data',c=>{if(over)return;size+=c.length;if(size>maxBytes){over=true;reject(new Error('too large'))}else chunks.push(c)});req.on('end',()=>{if(!over)resolve(Buffer.concat(chunks).toString('utf8'))});req.on('error',()=>{if(!over)reject(new Error('stream'))})})}
const rateHits=new Map();
function rateLimited(ip){const now=Date.now(),windowMs=60000,max=120;const arr=(rateHits.get(ip)||[]).filter(t=>now-t<windowMs);arr.push(now);rateHits.set(ip,arr);if(rateHits.size>5000)for(const[k,v]of rateHits)if(!v.some(t=>now-t<windowMs))rateHits.delete(k);return arr.length>max}
const publicFiles={'index.html':'text/html','app.js':'application/javascript','styles.css':'text/css','logo.png':'image/png','logo.svg':'image/svg+xml'};

// ---- Sessions: stateless signed cookie (serverless-safe) ----
const SESSION_TTL=8*3600*1000;
const SESSION_SECRET=process.env.SESSION_SECRET||crypto.randomBytes(32).toString('hex');
if(!process.env.SESSION_SECRET) console.warn('[warn] SESSION_SECRET not set — using an ephemeral secret (sessions drop on restart). Set SESSION_SECRET in production.');
function cookies(req){const out={};(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=p.slice(i+1).trim()});return out}
function hmac(s){return crypto.createHmac('sha256',SESSION_SECRET).update(s).digest('hex')}
function signSession(uid){const payload=Buffer.from(JSON.stringify({uid,ts:Date.now()})).toString('base64url');return `${payload}.${hmac(payload)}`}
function readSession(req){const raw=cookies(req)['acb_session'];if(!raw)return null;const i=raw.lastIndexOf('.');if(i<1)return null;const payload=raw.slice(0,i),sig=raw.slice(i+1);const expect=hmac(payload);if(sig.length!==expect.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expect)))return null;let obj;try{obj=JSON.parse(Buffer.from(payload,'base64url').toString())}catch{return null}if(!obj||typeof obj.ts!=='number'||Date.now()-obj.ts>SESSION_TTL)return null;return {uid:obj.uid}}
function sessionCookie(token,maxAge){return `acb_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAge}${process.env.SECURE_COOKIES?'; Secure':''}`}

// ---- Credentials (salted scrypt hashes) ----
function genPassword(){return crypto.randomBytes(9).toString('base64').replace(/[+/=]/g,'').slice(0,12)}
async function seedUsers(){
  const n=(await db.query('select count(*)::int n from credentials'))[0].n;
  if(n>0) return;
  const ids=['admin@acb.com','headoffice@acb.com','manager.koforidua@acb.com','ops.nsawam@acb.com','cs.nsawam@acb.com'];const shown=[];
  for(const id of ids){const fromEnv=id==='admin@acb.com'&&process.env.ADMIN_PASSWORD;const pw=fromEnv?process.env.ADMIN_PASSWORD:genPassword();const salt=crypto.randomBytes(16).toString('hex');const hash=crypto.scryptSync(pw,salt,64).toString('hex');await db.query('insert into credentials(id,salt,hash) values($1,$2,$3) on conflict(id) do nothing',[id,salt,hash]);shown.push([id,pw,fromEnv?'(from ADMIN_PASSWORD env)':''])}
  console.log('\n=== Initial staff passwords (shown once — store securely, then change on first sign-in) ===');for(const[id,pw,note]of shown)console.log(`  ${id.padEnd(30)} ${pw} ${note}`);console.log('=== Not persisted in plaintext anywhere ===\n');
}
async function setPassword(id,pw){const salt=crypto.randomBytes(16).toString('hex');const hash=crypto.scryptSync(String(pw),salt,64).toString('hex');await db.query('insert into credentials(id,salt,hash) values($1,$2,$3) on conflict(id) do update set salt=excluded.salt,hash=excluded.hash',[id,salt,hash]);return true}
async function verifyUser(staffId,password){const id=String(staffId||'').toLowerCase().trim();const rows=await db.query('select salt,hash from credentials where id=$1',[id]);if(!rows.length)return null;let calc;try{calc=crypto.scryptSync(String(password||''),rows[0].salt,64)}catch{return null}const stored=Buffer.from(rows[0].hash,'hex');if(calc.length!==stored.length||!crypto.timingSafeEqual(calc,stored))return null;return id}
const loginFails=new Map();const LOCK_MAX=8,LOCK_MS=15*60000;
function loginLocked(id){const e=loginFails.get(id);if(!e)return false;if(Date.now()>e.until){loginFails.delete(id);return false}return e.count>=LOCK_MAX}
function noteFail(id){const t=Date.now();let e=loginFails.get(id);if(!e||t>e.until)e={count:0,until:0};e.count++;e.until=t+LOCK_MS;loginFails.set(id,e)}
function clearFails(id){loginFails.delete(id)}
// ---- Password-reset OTP (DB-backed so it survives across serverless instances) ----
const OTP_TTL=10*60*1000, OTP_MAX_ATTEMPTS=5, OTP_RESEND_MS=60*1000;
function otpHash(uid,code){return hmac(String(uid)+':'+String(code));}
async function otpRow(uid){const rows=await db.query('select uid,code_hash,expires,attempts,created_at from password_reset where uid=$1',[uid]);return rows[0]||null;}
async function otpPut(uid,code){const t=Date.now();await db.query('insert into password_reset(uid,code_hash,expires,attempts,created_at) values($1,$2,$3,0,$4) on conflict(uid) do update set code_hash=excluded.code_hash,expires=excluded.expires,attempts=0,created_at=excluded.created_at',[uid,otpHash(uid,code),t+OTP_TTL,t]);}
async function otpBump(uid){await db.query('update password_reset set attempts=attempts+1 where uid=$1',[uid]);}
async function otpClear(uid){await db.query('delete from password_reset where uid=$1',[uid]);}

// ---- SMS gateway config (config table) ----
async function loadSms(){const r=await db.query("select value from config where key='sms'");return r.length?r[0].value:{provider:'arkesel',senderId:'',apiKey:'',enabled:false}}
async function saveSms(cfg){await db.query("insert into config(key,value) values('sms',$1) on conflict(key) do update set value=excluded.value",[JSON.stringify(cfg)])}
function maskKey(k){k=String(k||'');return k?('•'.repeat(Math.max(2,k.length-4))+k.slice(-4)):''}
function normPhone(p){let d=String(p||'').replace(/[^0-9]/g,'');if(d.startsWith('233'))return d;if(d.startsWith('0'))return '233'+d.slice(1);if(d.length===9)return '233'+d;return d}
async function sendSms(cfg,phone,message){if(!cfg||!cfg.enabled)return{ok:false,detail:'SMS gateway disabled'};if(!cfg.apiKey||!cfg.senderId)return{ok:false,detail:'SMS gateway not configured'};const to=normPhone(phone);if(to.length<11||to.length>15)return{ok:false,detail:'Invalid phone number'};try{const ctrl=new AbortController();const t=setTimeout(()=>ctrl.abort(),12000);const r=await fetch('https://sms.arkesel.com/api/v2/sms/send',{method:'POST',headers:{'api-key':cfg.apiKey,'Content-Type':'application/json'},body:JSON.stringify({sender:cfg.senderId,message,recipients:[to]}),signal:ctrl.signal});clearTimeout(t);let j={};try{j=await r.json()}catch{}if(r.ok&&(j.status==='success'||j.code==='ok'||j.status===true))return{ok:true,detail:'Accepted by gateway'};return{ok:false,detail:(j&&(j.message||j.status))||`Gateway error ${r.status}`}}catch(e){return{ok:false,detail:e.name==='AbortError'?'Gateway timeout':'Gateway unreachable'}}}

// ---- Customer database (dedicated indexed table) ----
function custName(first,middle,surname,company){const parts=[first,middle,surname].map(s=>String(s||'').trim()).filter(Boolean);const dd=[];for(const p of parts)if(dd[dd.length-1]!==p)dd.push(p);return dd.join(' ')||String(company||'').trim()}
async function upsertCustomer(rec){const acct=String(rec.account||'').trim();if(!acct)return 'skip';const name=rec.name||'';const r=await db.query(
  `insert into customers(account,name,name_lc,phone,branch,type,status,source,updated) values($1,$2,$3,$4,$5,$6,$7,$8,$9)
   on conflict(account) do update set
     name=coalesce(nullif(excluded.name,''),customers.name),
     name_lc=coalesce(nullif(excluded.name_lc,''),customers.name_lc),
     phone=coalesce(nullif(excluded.phone,''),customers.phone),
     branch=coalesce(nullif(excluded.branch,''),customers.branch),
     type=coalesce(nullif(excluded.type,''),customers.type),
     status=coalesce(nullif(excluded.status,''),customers.status),
     source=coalesce(nullif(excluded.source,''),customers.source),
     updated=excluded.updated
   returning (xmax=0) as inserted`,
  [acct,name,name.toLowerCase(),rec.phone||'',rec.branch||'',rec.type||'',rec.status||'',rec.source||'import',now()]);
  return r[0]&&r[0].inserted?'insert':'update';
}
async function customerExists(acct){return (await db.query('select 1 from customers where account=$1',[String(acct)])).length>0}
async function searchCustomers(rawQ,limit){const raw=String(rawQ||'').trim();const q=raw.toLowerCase();limit=limit||25;if(q.length<2)return[];const like='%'+q+'%';const rows=await db.query(
  `select account,name,phone,branch,type,status from customers
   where lower(account)=$1 or lower(account) like $2 or name_lc like $2
   order by (lower(account)=$1) desc, name_lc limit $3`,[q,like,limit]);
  return rows.map(r=>({account:r.account,name:r.name,phone:r.phone,branch:r.branch,type:r.type,status:r.status}));
}
async function customerStats(){const n=(await db.query('select count(*)::int n from customers'))[0].n;const m=await db.query("select value from config where key='customers_meta'");return {total:n,lastImport:m.length?(m[0].value.lastImport||''):''}}
function parseCsvLine(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(q){if(ch==='"'){if(line[i+1]==='"'){cur+='"';i++}else q=false}else cur+=ch}else{if(ch==='"')q=true;else if(ch===','){out.push(cur);cur=''}else cur+=ch}}out.push(cur);return out}
async function importCustomersCsv(text){
  const lines=text.split(/\r?\n/);if(lines.length<2)return{error:'The file is empty or has no data rows.'};
  const headers=parseCsvLine(lines[0]).map(h=>h.trim());const idx=n=>headers.indexOf(n);const iA=idx('Account Number');if(iA<0)return{error:'Missing an "Account Number" column.'};
  const iF=idx('First Name'),iM=idx('Middle Name'),iS=(idx('Surname')>=0?idx('Surname'):idx('Last Name')),iC=idx('Company Name'),iMob=idx('Mobile Phone Number'),iMain=idx('Main Phone Number'),iMomo=idx('Mobile Money Number'),iT=idx('Account Type'),iSt=idx('Status Of Account'),iB=idx('Account Branch');
  const byAcct=new Map();let skip=0;
  for(let li=1;li<lines.length;li++){if(!lines[li].trim())continue;const c=parseCsvLine(lines[li]);const acct=String(c[iA]||'').trim();if(!acct){skip++;continue}const phoneRaw=(iMob>=0&&c[iMob])||(iMain>=0&&c[iMain])||(iMomo>=0&&c[iMomo])||'';byAcct.set(acct,{account:acct,name:custName(c[iF],c[iM],c[iS],c[iC]),phone:phoneRaw?normPhone(phoneRaw):'',branch:String(c[iB]||'').trim(),type:String(c[iT]||'').trim(),status:String(c[iSt]||'').trim()})}
  const uniq=[...byAcct.values()];const ts=now();
  const before=(await db.query('select count(*)::int n from customers'))[0].n;
  const BATCH=1000;
  await db.tx(async q=>{
    for(let i=0;i<uniq.length;i+=BATCH){
      const chunk=uniq.slice(i,i+BATCH);const ph=[];const vals=[];
      chunk.forEach((r,j)=>{const b=j*9;ph.push(`($${b+1},$${b+2},$${b+3},$${b+4},$${b+5},$${b+6},$${b+7},$${b+8},$${b+9})`);vals.push(r.account,r.name,(r.name||'').toLowerCase(),r.phone,r.branch,r.type,r.status,'import',ts)});
      await q(`insert into customers(account,name,name_lc,phone,branch,type,status,source,updated) values ${ph.join(',')}
        on conflict(account) do update set name=coalesce(nullif(excluded.name,''),customers.name),name_lc=coalesce(nullif(excluded.name_lc,''),customers.name_lc),phone=coalesce(nullif(excluded.phone,''),customers.phone),branch=coalesce(nullif(excluded.branch,''),customers.branch),type=coalesce(nullif(excluded.type,''),customers.type),status=coalesce(nullif(excluded.status,''),customers.status),updated=excluded.updated`, vals);
    }
  });
  const after=(await db.query('select count(*)::int n from customers'))[0].n;
  await db.query("insert into config(key,value) values('customers_meta',$1) on conflict(key) do update set value=excluded.value",[JSON.stringify({lastImport:ts})]);
  const inserted=after-before;
  return {inserted,updated:uniq.length-inserted,skipped:skip,total:after,lastImport:ts};
}

// ---- System / security event log (dedicated table) ----
async function logSys(level,event,actor,ip,detail){try{await db.query('insert into system_log(level,event,actor,ip,detail) values($1,$2,$3,$4,$5)',[level,event,actor||null,ip||null,detail?String(detail).slice(0,500):null])}catch(e){}}
async function systemLogQuery(f){const where=[];const params=[];let i=1;if(f.level){where.push(`level=$${i++}`);params.push(f.level)}if(f.q){where.push(`(actor ilike $${i} or event ilike $${i} or detail ilike $${i})`);params.push('%'+f.q+'%');i++}if(f.from){where.push(`ts>=$${i++}`);params.push(f.from)}if(f.to){where.push(`ts<=$${i++}`);params.push(f.to)}const lim=Math.min(Math.max(parseInt(f.limit||500,10)||500,1),2000);return db.query(`select to_char(ts,'YYYY-MM-DD HH24:MI:SS') ts,level,event,actor,ip,detail from system_log ${where.length?'where '+where.join(' and '):''} order by ts desc, id desc limit ${lim}`,params)}
function now(){return new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date())}
const seedBranches=['Nsawam Branch','Koforidua Branch','Aburi Branch','Adukrom Branch','Mamfe Branch','Madina Branch'];
function branchesOf(data){return (data&&Array.isArray(data.branches)&&data.branches.length)?data.branches:seedBranches;}
// TEMP (setup/training): four-eyes authorisation is waived for System Administrators
// (accounts holding BOTH admin.manage and admin.authorise) so a single admin can
// operate directly. Set REQUIRE_FOUR_EYES = true and redeploy before go-live to
// restore mandatory two-administrator authorisation on all administrative changes.
const REQUIRE_FOUR_EYES = false;
// ---- Cheque production pipeline helpers ----
function pad6(n){return String(n).padStart(6,'0');}
function leavesOf(size){const m=String(size||'').match(/\d+/);return m?parseInt(m[0],10):0;}
function batchLog(b,actor,event){b.log=b.log||[];b.log.unshift([now(),actor,event]);}
function ref(prefix){return `${prefix}-${Date.now().toString().slice(-6)}`}
function need(fields,keys){for(const k of keys)if(!String(fields[k]||'').trim())return `The "${k}" field is required.`;return null}
const PENDING='Pending Authorization';

function ensureGov(data){data.directory=data.directory||{};data.roles=data.roles||{};data.groups=data.groups||{};data.sodMatrix=data.sodMatrix||[];data.adminQueue=data.adminQueue||[];data.adminAudit=data.adminAudit||[]}
function effPerms(data,role,groups){const set=new Set();const rc=data.roles||{},gc=data.groups||{};const names=[role,...((groups||[]).flatMap(g=>gc[g]?.roles||[]))];for(const rn of names){const r=rc[rn];if(r)(r.permissions||[]).forEach(x=>set.add(x))}return set}
function isGlobal(data,role,groups){const rc=data.roles||{},gc=data.groups||{};const names=[role,...((groups||[]).flatMap(g=>gc[g]?.roles||[]))];return names.some(n=>rc[n]?.global)}
function sodConflict(data,set){for(const [a,b] of (data.sodMatrix||[]))if(set.has(a)&&set.has(b))return [a,b];return null}
function principal(data,uid){const u=(data.directory||{})[uid];if(!u||u.status!=='Active')return null;return{uid,name:u.name,branch:u.branch,role:u.role,groups:u.groups||[],perms:effPerms(data,u.role,u.groups),global:isGlobal(data,u.role,u.groups)}}
function has(p,perm){return !!p&&p.perms.has(perm)}
function inScope(p,itemBranch){return !!p&&(p.global||p.branch===itemBranch)}
function initialsOf(name){return String(name||'').split(/\s+/).map(w=>w[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'AC'}
function notify(data,customer,account,branch,message,channel,status){data.notifications=data.notifications||[];data.notifications.unshift([ref('NTF'),customer||'Customer',account||'—',branch,channel||'SMS',message,status||'Sent',now()]);return data.notifications[0]}
function scope(data,sess){if(!sess||sess.global)return data;const b=sess.branch;const out={};for(const k in data){if(k==='printBatches'&&Array.isArray(data[k]))out[k]=data[k].filter(x=>x&&x.branch===b);else if(Array.isArray(data[k]))out[k]=data[k].filter(r=>Array.isArray(r)&&r.includes(b));else out[k]=data[k]}return out}
async function statePayload(data,me){const scoped=scope(data,me);const admin=has(me,'admin.manage')||has(me,'admin.authorise');if(!admin)for(const k of ['directory','roles','groups','sodMatrix','adminQueue','adminAudit'])delete scoped[k];delete scoped.requestPhones;let sms;if(admin){const c=await loadSms();sms={provider:c.provider||'arkesel',senderId:c.senderId||'',enabled:!!c.enabled,apiKeyMasked:maskKey(c.apiKey),configured:!!(c.apiKey&&c.senderId)}}const cstats=has(me,'customers.manage')?await customerStats():undefined;return{data:scoped,role:me.role,branch:me.branch,name:me.name,perms:[...me.perms],global:me.global,branches:branchesOf(data),adminDirect:(!REQUIRE_FOUR_EYES&&has(me,'admin.manage')&&has(me,'admin.authorise')),initials:initialsOf(me.name),roleLabel:(data.roles?.[me.role]?.label)||me.role,permCatalog:admin?PERMISSIONS:undefined,sms,customerStats:cstats}}

const builders={
  request(f,branch){const e=need(f,['account','customer','book']);if(e)return{error:e};const r=ref('CBR');return{bucket:'requests',label:'Cheque book request',ref:r,subject:f.customer,statusIdx:5,finalStatus:'Authorized',entry:[r,f.account,f.customer,branch,f.book,PENDING,now()]}},
  inventory(f,branch){const e=need(f,['type','start','end']);if(e)return{error:e};const start=parseInt(f.start,10),end=parseInt(f.end,10);if(!Number.isFinite(start)||!Number.isFinite(end))return{error:'Start and end serials must be numeric.'};if(end<start)return{error:'End serial cannot be lower than the start serial.'};const width=Math.max(String(f.start).trim().length,String(f.end).trim().length);const pad=n=>String(n).padStart(width,'0');const total=String(end-start+1);const r=ref('INV');return{bucket:'inventory',label:'Range registration',ref:r,subject:f.type,statusIdx:6,finalStatus:'Active',entry:[r,branch,f.type,`${pad(start)} – ${pad(end)}`,total,total,PENDING]}},
  issuance(f,branch){const e=need(f,['request','account','range']);if(e)return{error:e};const r=ref('ISS');return{bucket:'issuance',label:'Cheque book issuance',ref:r,subject:f.account,statusIdx:5,finalStatus:'Issued',entry:[r,f.request,f.account,branch,f.range,PENDING,now()]}}
};
function applyChange(data,chg){const p=chg.payload;switch(chg.type){
  case 'user/create':{if(data.directory[p.id])return 'A user with that staff ID already exists.';data.directory[p.id]={name:p.name,branch:p.branch,role:p.role,phone:p.phone||'',groups:[],status:'Active',lastReviewed:now()};return null}
  case 'user/phone':{const u=data.directory[p.uid];if(!u)return 'User not found.';u.phone=p.phone;return null}
  case 'branch/create':{if(!Array.isArray(data.branches)||!data.branches.length)data.branches=[...seedBranches];if(data.branches.some(b=>String(b).toLowerCase()===String(p.name).toLowerCase()))return 'That branch already exists.';data.branches.push(p.name);return null}
  case 'user/role':{const u=data.directory[p.uid];if(!u)return 'User not found.';if(!data.roles[p.role])return 'Role not found.';const c=sodConflict(data,effPerms(data,p.role,u.groups));if(c)return `Segregation-of-duties conflict: ${c[0]} vs ${c[1]}.`;u.role=p.role;return null}
  case 'user/groups/add':{const u=data.directory[p.uid];if(!u)return 'User not found.';if(!data.groups[p.group])return 'Group not found.';const groups=[...new Set([...(u.groups||[]),p.group])];const c=sodConflict(data,effPerms(data,u.role,groups));if(c)return `Segregation-of-duties conflict: ${c[0]} vs ${c[1]}.`;u.groups=groups;return null}
  case 'user/enable':{const u=data.directory[p.uid];if(!u)return 'User not found.';u.status='Active';return null}
  case 'role/save':{const c=sodConflict(data,new Set(p.permissions));if(c)return `A role cannot combine ${c[0]} and ${c[1]}.`;data.roles[p.name]={label:p.label,global:!!p.global,permissions:p.permissions,system:!!p.system};return null}
  case 'group/save':{const set=new Set((p.roles||[]).flatMap(r=>data.roles[r]?.permissions||[]));const c=sodConflict(data,set);if(c)return `A group cannot combine ${c[0]} and ${c[1]}.`;data.groups[p.name]={description:p.description,branch:p.branch,roles:p.roles};return null}
  case 'sod/remove':{data.sodMatrix=(data.sodMatrix||[]).filter(pair=>!((pair[0]===p.a&&pair[1]===p.b)||(pair[0]===p.b&&pair[1]===p.a)));return null}
  default:return 'Unknown change type.';
}}

let _ready;
function ready(){if(!_ready)_ready=(async()=>{await db.init();await seedUsers();await load();})();return _ready}
const handler=async(req,res)=>{try{await ready();const url=new URL(req.url,'http://localhost');
  if(url.pathname.startsWith('/api/')&&rateLimited(clientIp(req)))return send(res,429,{error:'Too many requests. Please slow down.'});
  if(req.method==='POST'&&url.pathname==='/api/session'){try{const ip=clientIp(req);const body=await collect(req);const idKey=String(body.staffId||'').toLowerCase().trim();if(loginLocked(idKey)){await logSys('SECURITY','login.lockout',idKey,ip,'account temporarily locked after repeated failures');return send(res,429,{error:'Too many failed attempts. Please try again in 15 minutes.'})}const uid=await verifyUser(body.staffId,body.password);if(!uid){noteFail(idKey);await logSys('SECURITY','login.failure',idKey||'unknown',ip,'invalid staff ID or password');return send(res,401,{error:'Invalid staff ID or password.'})}clearFails(idKey);const data=await load();const me=principal(data,uid);if(!me){await logSys('SECURITY','login.disabled',uid,ip,'disabled account attempted sign-in');return send(res,403,{error:'This account is disabled. Contact an administrator.'})}await logSys('SECURITY','login.success',uid,ip,`signed in as ${me.role}`);res.writeHead(200,{...securityHeaders,'Content-Type':'application/json','Cache-Control':'no-store','Set-Cookie':sessionCookie(signSession(uid),SESSION_TTL/1000)});return res.end(JSON.stringify(await statePayload(data,me)))}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/logout'){const s=readSession(req);if(s)await logSys('INFO','logout',s.uid,clientIp(req),'signed out');res.writeHead(200,{...securityHeaders,'Content-Type':'application/json','Cache-Control':'no-store','Set-Cookie':sessionCookie('',0)});return res.end(JSON.stringify({ok:true}))}
  if(req.method==='POST'&&url.pathname==='/api/forgot'){try{const ip=clientIp(req);const body=await collect(req);const uid=String(body.staffId||'').toLowerCase().trim();const generic={ok:true,message:'If the staff ID matches an active account with a phone number on file, a 6-digit reset code has been sent to that number.'};if(!uid)return send(res,200,generic);const data=await load();const u=data.directory[uid];if(!u||u.status!=='Active'||!u.phone){await logSys('SECURITY','password.otp.request',uid,ip,'reset requested for unknown or ineligible account');return send(res,200,generic)}const existing=await otpRow(uid);if(existing&&Date.now()-Number(existing.created_at)<OTP_RESEND_MS)return send(res,429,{error:'A code was just sent. Please wait a minute before requesting another.'});const code=String(crypto.randomInt(0,1000000)).padStart(6,'0');await otpPut(uid,code);const cfg=await loadSms();const outcome=await sendSms(cfg,u.phone,`Akuapem Community Bank: your password reset code is ${code}. It expires in 10 minutes. Do not share it with anyone.`);await logSys(outcome.ok?'SECURITY':'ERROR','password.otp.request',uid,ip,outcome.ok?`reset code sent to ${maskKey(u.phone)}`:`reset code NOT delivered (${outcome.detail})`);return send(res,200,generic)}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/reset'){try{const ip=clientIp(req);const body=await collect(req);const uid=String(body.staffId||'').toLowerCase().trim();const code=String(body.code||'').replace(/[^0-9]/g,'');const np=String(body.newPassword||'');const row=uid?await otpRow(uid):null;if(!row||Date.now()>Number(row.expires)){if(row)await otpClear(uid);return send(res,400,{error:'This reset code is invalid or has expired. Please request a new one.'})}if(row.attempts>=OTP_MAX_ATTEMPTS){await otpClear(uid);await logSys('SECURITY','password.reset.blocked',uid,ip,'too many invalid reset attempts');return send(res,429,{error:'Too many invalid attempts. Please request a new code.'})}if(np.length<10)return send(res,400,{error:'New password must be at least 10 characters.'});const expect=row.code_hash,got=otpHash(uid,code);if(expect.length!==got.length||!crypto.timingSafeEqual(Buffer.from(expect),Buffer.from(got))){await otpBump(uid);return send(res,400,{error:'That code is not correct. Please check and try again.'})}await setPassword(uid,np);await otpClear(uid);clearFails(uid);const data=await load();const u=data.directory[uid]||{};data.audit.unshift([now(),'Password reset via OTP',uid,u.name||uid,u.role||'',u.branch||'','Self-service reset with SMS one-time code']);await save(data);await logSys('SECURITY','password.reset',uid,ip,'password reset via SMS one-time code');return send(res,200,{ok:true})}catch{return send(res,400,{error:'Invalid request.'})}}
  const rawSess=readSession(req);
  if(url.pathname.startsWith('/api/')&&!rawSess)return send(res,401,{error:'Not authenticated. Please sign in.'});
  const sess=rawSess?principal(await load(),rawSess.uid):null;
  if(url.pathname.startsWith('/api/')&&!sess){if(rawSess)await logSys('SECURITY','session.invalid',rawSess.uid,clientIp(req),'session rejected (expired or account disabled)');return send(res,401,{error:'Your session is no longer valid. Please sign in again.'})}
  if(req.method==='GET'&&url.pathname==='/api/state')return send(res,200,await statePayload(await load(),sess));
  if(req.method==='GET'&&url.pathname==='/api/reports/system-log'){if(!has(sess,'logs.view')){await logSys('WARN','authz.denied',sess.name,clientIp(req),'attempted to view system logs');return send(res,403,{error:'You do not have permission to view system logs.'})}const rows=await systemLogQuery({level:url.searchParams.get('level'),q:url.searchParams.get('q'),from:url.searchParams.get('from'),to:url.searchParams.get('to'),limit:url.searchParams.get('limit')});return send(res,200,{rows})}
  if(req.method==='GET'&&url.pathname==='/api/customers/search'){if(!has(sess,'customers.view'))return send(res,403,{error:'You do not have permission to search customers.'});return send(res,200,{results:await searchCustomers(url.searchParams.get('q')||'',25)})}
  if(req.method==='POST'&&url.pathname==='/api/customers/import'){if(!has(sess,'customers.manage'))return send(res,403,{error:'You do not have permission to import the customer database.'});let text;try{text=await collectText(req,30*1024*1024)}catch(e){return send(res,413,{error:'File exceeds the 30 MB limit or failed to upload.'})}try{const out=await importCustomersCsv(text);if(out.error)return send(res,400,{error:out.error});const data=await load();data.audit.unshift([now(),'Customer database imported',`${out.total} total`,sess.name,sess.role,sess.branch,`${out.inserted} new, ${out.updated} updated, ${out.skipped} skipped`]);await save(data);await logSys('SECURITY','data.import',sess.name,clientIp(req),`customer import: ${out.inserted} new, ${out.updated} updated, ${out.total} total`);return send(res,200,out)}catch(e){return send(res,400,{error:'Could not parse the uploaded file. Ensure it is a CSV export.'})}}
  if(req.method==='POST'&&url.pathname==='/api/users/import'){if(!has(sess,'admin.manage'))return send(res,403,{error:'You do not have permission to import users.'});let text;try{text=await collectText(req,2*1024*1024)}catch(e){return send(res,413,{error:'File exceeds the size limit or failed to upload.'})}try{const lines=text.split(/\r?\n/).filter(l=>l.trim());if(lines.length<2)return send(res,400,{error:'No data rows found in the file.'});const headers=parseCsvLine(lines[0]).map(h=>h.trim().toLowerCase());const col=(...names)=>{for(const n of names){const i=headers.indexOf(n);if(i>=0)return i}return -1};const iName=col('full name','name'),iEmail=col('staff email','email','staff id'),iPhone=col('mobile phone','phone'),iRole=col('role'),iBranch=col('branch');if(iName<0||iEmail<0||iRole<0||iBranch<0)return send(res,400,{error:'CSV needs columns: Full Name, Staff Email, Mobile Phone, Role, Branch.'});const data=await load();ensureGov(data);const results=[];let created=0,skipped=0,errs=0;for(let li=1;li<lines.length;li++){const c=parseCsvLine(lines[li]);const name=String(c[iName]||'').trim();const id=String(c[iEmail]||'').toLowerCase().trim();const role=String(c[iRole]||'').trim();const branch=String(c[iBranch]||'').trim();const phone=normPhone(iPhone>=0?c[iPhone]:'');if(!id&&!name)continue;const rec={name,email:id,role,branch};if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(id)){rec.status='error';rec.detail='Invalid email';errs++;results.push(rec);continue}if(data.directory[id]){rec.status='skipped';rec.detail='Already exists';skipped++;results.push(rec);continue}if(!name){rec.status='error';rec.detail='Missing name';errs++;results.push(rec);continue}if(!data.roles[role]){rec.status='error';rec.detail='Unknown role';errs++;results.push(rec);continue}if(branch!=='All Branches'&&!branchesOf(data).includes(branch)){rec.status='error';rec.detail='Unknown branch';errs++;results.push(rec);continue}if(phone.length<11||phone.length>15){rec.status='error';rec.detail='Invalid phone';errs++;results.push(rec);continue}data.directory[id]={name,branch,role,phone,groups:[],status:'Active',lastReviewed:now()};const pw=genPassword();await setPassword(id,pw);rec.status='created';rec.tempPassword=pw;created++;results.push(rec);data.adminAudit.unshift([now(),sess.name,'User created (bulk import)',id,`${name} — ${role} @ ${branch}`])}await save(data);await logSys('SECURITY','users.import',sess.name,clientIp(req),`bulk user import: ${created} created, ${skipped} skipped, ${errs} errors`);return send(res,200,{...(await statePayload(data,principal(data,sess.uid))),importResults:results,imported:{created,skipped,errors:errs}})}catch(e){return send(res,400,{error:'Could not parse the file. Ensure it is a CSV.'})}}
  if(req.method==='POST'&&url.pathname==='/api/password'){try{const body=await collect(req);if(await verifyUser(sess.uid,body.currentPassword)!==sess.uid)return send(res,403,{error:'Your current password is incorrect.'});const np=String(body.newPassword||'');if(np.length<10)return send(res,400,{error:'New password must be at least 10 characters.'});if(np===String(body.currentPassword||''))return send(res,400,{error:'Choose a password different from the current one.'});await setPassword(sess.uid,np);const data=await load();data.audit.unshift([now(),'Password changed',sess.uid,sess.name,sess.role,sess.branch,'Self-service password update']);await save(data);await logSys('SECURITY','password.change',sess.uid,clientIp(req),'self-service password update');return send(res,200,{ok:true})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/transactions'){try{const body=await collect(req);const builder=builders[body.module];if(!builder)return send(res,400,{error:'Invalid transaction type.'});if(!has(sess,`${body.module}.create`))return send(res,403,{error:'You do not have permission to create this transaction.'});const fields=body.fields||{};const data=await load();const targetBranch=String(fields.branch||sess.branch||'').trim();if(!branchesOf(data).includes(targetBranch))return send(res,400,{error:'A valid branch must be selected.'});if(!sess.global&&targetBranch!==sess.branch)return send(res,403,{error:'You can only create records for your own branch.'});if(body.module==='request'){const acct=String(fields.account||'').trim().toLowerCase();if(acct){const open=(data.requests||[]).find(r=>String(r[1]||'').trim().toLowerCase()===acct&&!/^(issued|collected|rejected|cancelled|destroyed)$/i.test(String(r[5]||'')));if(open)return send(res,409,{error:`This customer already has a cheque book awaiting issuance — ${open[0]} at ${open[3]} (${open[5]}). A new request cannot be raised until it is issued or cancelled.`})}}const built=builder(fields,targetBranch);if(built.error)return send(res,400,{error:built.error});if(!data.approvalMeta)data.approvalMeta={};if(body.module==='request'){const ph=normPhone(fields.phone);if(ph.length<11)return send(res,400,{error:'A valid customer phone number is required.'});data.requestPhones=data.requestPhones||{};data.requestPhones[built.ref]=ph}data[built.bucket].unshift(built.entry);const queueId=ref('APR');data.approvals.unshift([queueId,built.label,built.ref,built.subject,targetBranch,sess.name,now()]);data.approvalMeta[queueId]={bucket:built.bucket,ref:built.ref,statusIdx:built.statusIdx,finalStatus:built.finalStatus,maker:sess.name,makerRole:sess.role};data.audit.unshift([now(),`${built.label} submitted`,built.ref,sess.name,sess.role,targetBranch,'Submitted for maker-checker approval']);await save(data);return send(res,201,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&(url.pathname==='/api/authorizations/authorise'||url.pathname==='/api/authorizations/reject')){try{if(!has(sess,'txn.authorise'))return send(res,403,{error:'Authorisation permission required.'});const reject=url.pathname.endsWith('/reject');const body=await collect(req);const data=await load();if(!data.approvalMeta)data.approvalMeta={};const idx=data.approvals.findIndex(a=>a[0]===body.ref);if(idx<0)return send(res,404,{error:'This item is no longer in the authorisation queue.'});const item=data.approvals[idx];if(!inScope(sess,item[4]))return send(res,403,{error:'This item is outside your branch scope.'});const meta=data.approvalMeta[item[0]]||{};if(meta.maker&&meta.maker===sess.name)return send(res,403,{error:'The submitting officer cannot authorise their own transaction.'});const rec=meta.bucket&&data[meta.bucket]?data[meta.bucket].find(r=>r[0]===meta.ref):null;if(rec&&typeof meta.statusIdx==='number')rec[meta.statusIdx]=reject?'Rejected':meta.finalStatus;data.approvals.splice(idx,1);delete data.approvalMeta[item[0]];data.audit.unshift([now(),reject?'Transaction rejected':'Transaction authorised',item[2],sess.name,sess.role,item[4],reject?`Rejected by checker (maker ${meta.maker||'n/a'})`:`Authorised by checker (maker ${meta.maker||'n/a'})`]);if(!reject&&rec&&meta.bucket==='issuance'){const rq=(data.requests||[]).find(r=>r[0]===rec[1]);const customer=rq?rq[2]:rec[2];notify(data,customer,rec[2],rec[3],`Your cheque book ${rec[4]} is ready for collection at ${rec[3]}. Please bring valid photo ID.`,'SMS');data.audit.unshift([now(),'Customer alert sent',rec[0],'System','Notification',rec[3],'Cheque book ready-for-collection alert issued'])}if(!reject&&rec&&meta.bucket==='requests'){const acct=String(rec[1]),nm=rec[2],br=rec[3],ph=(data.requestPhones||{})[rec[0]]||'';const before=await customerExists(acct);await upsertCustomer({account:acct,name:nm,phone:ph,branch:br,status:'Active',source:'requisition'});if(!before)data.audit.unshift([now(),'Customer added to database',acct,'System','Customer DB',br,`New customer ${nm} from requisition ${rec[0]}`])}await save(data);return send(res,200,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/vault/push'){try{if(!has(sess,'vault.dispatch'))return send(res,403,{error:'You do not have permission to dispatch cheque stock to a branch vault.'});const body=await collect(req);const f=body.fields||{};const data=await load();const dest=String(f.branch||'').trim();if(!branchesOf(data).includes(dest))return send(res,400,{error:'Select a valid destination branch.'});const e=need(f,['type','start','end']);if(e)return send(res,400,{error:e});const start=parseInt(f.start,10),end=parseInt(f.end,10);if(!Number.isFinite(start)||!Number.isFinite(end))return send(res,400,{error:'Start and end serials must be numeric.'});if(end<start)return send(res,400,{error:'End serial cannot be lower than the start serial.'});const width=Math.max(String(f.start).trim().length,String(f.end).trim().length);const pad=n=>String(n).padStart(width,'0');const total=end-start+1;if(!data.vault)data.vault=[];const r=ref('VLT');data.vault.unshift([r,dest,f.type,`${pad(start)} – ${pad(end)}`,`${total} leaves`,'Awaiting Confirmation',now()]);data.audit.unshift([now(),'Cheque stock dispatched to vault',r,sess.role,sess.role,dest,'Awaiting branch reconciliation and confirmation']);await save(data);return send(res,201,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/vault/submit'){try{if(!has(sess,'vault.submit'))return send(res,403,{error:'You do not have permission to submit vault stock for authorisation.'});const body=await collect(req);const data=await load();if(!data.vault)data.vault=[];if(!data.vaultMeta)data.vaultMeta={};const item=data.vault.find(v=>v[0]===body.ref&&v[5]==='Awaiting Confirmation');if(!item)return send(res,404,{error:'Batch not found or not awaiting confirmation.'});if(!inScope(sess,item[1]))return send(res,403,{error:'This batch belongs to another branch vault.'});item[5]='Pending Authorisation';data.vaultMeta[item[0]]={maker:sess.name,makerRole:sess.role,submitted:now()};data.audit.unshift([now(),'Vault acceptance submitted',item[0],sess.name,sess.role,item[1],'Hard copies reconciled; awaiting second-officer authorisation']);await save(data);return send(res,200,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/vault/authorise'){try{if(!has(sess,'vault.authorise'))return send(res,403,{error:'Authorisation permission required.'});const body=await collect(req);const data=await load();if(!data.vault)data.vault=[];if(!data.vaultMeta)data.vaultMeta={};const item=data.vault.find(v=>v[0]===body.ref&&v[5]==='Pending Authorisation');if(!item)return send(res,404,{error:'Batch not found or not pending authorisation.'});if(!inScope(sess,item[1]))return send(res,403,{error:'This batch belongs to another branch vault.'});const meta=data.vaultMeta[item[0]]||{};if(meta.maker&&meta.maker===sess.name)return send(res,403,{error:'The submitting officer cannot authorise their own acceptance.'});const total=String(item[4]).replace(/[^0-9]/g,'')||'0';const invRef=ref('INV');data.inventory.unshift([invRef,item[1],item[2],item[3],total,total,'Active']);item[5]='Accepted';data.audit.unshift([now(),'Vault stock authorised and accepted',item[0],sess.name,sess.role,item[1],`Authorised (maker ${meta.maker||'n/a'}); moved to inventory as ${invRef}`]);let alerted=0;(data.requests||[]).forEach(rq=>{if(rq[3]===item[1]&&rq[5]==='Authorized'){notify(data,rq[2],rq[1],item[1],`Cheque stock has arrived at ${item[1]} — your requested cheque book is being prepared for collection. We will notify you when it is ready.`,'SMS');alerted++}});if(alerted)data.audit.unshift([now(),'Customer alerts sent',invRef,'System','Notification',item[1],`${alerted} customer${alerted===1?'':'s'} notified of arriving stock`]);delete data.vaultMeta[item[0]];await save(data);return send(res,200,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/vault/reject'){try{if(!has(sess,'vault.authorise'))return send(res,403,{error:'Authorisation permission required.'});const body=await collect(req);const data=await load();if(!data.vault)data.vault=[];if(!data.vaultMeta)data.vaultMeta={};const item=data.vault.find(v=>v[0]===body.ref&&v[5]==='Pending Authorisation');if(!item)return send(res,404,{error:'Batch not found or not pending authorisation.'});if(!inScope(sess,item[1]))return send(res,403,{error:'This batch belongs to another branch vault.'});const meta=data.vaultMeta[item[0]]||{};item[5]='Awaiting Confirmation';data.audit.unshift([now(),'Vault acceptance rejected',item[0],sess.name,sess.role,item[1],`Returned for re-reconciliation (maker ${meta.maker||'n/a'})`]);delete data.vaultMeta[item[0]];await save(data);return send(res,200,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/vault/dispatch-item'){try{if(!has(sess,'vault.dispatch'))return send(res,403,{error:'You do not have permission to dispatch itemised cheques.'});const body=await collect(req);const data=await load();data.vaultItems=data.vaultItems||[];data.requestPhones=data.requestPhones||{};const reqRef=String(body.requestRef||'').trim();const rq=(data.requests||[]).find(r=>r[0]===reqRef);if(!rq)return send(res,404,{error:'Cheque book request not found.'});const phone=data.requestPhones[reqRef];if(!phone)return send(res,400,{error:'That requisition has no linked telephone number.'});const r=ref('VIT');data.vaultItems.unshift([r,rq[2],rq[1],phone,rq[3],reqRef,'Awaiting Confirmation',now()]);data.audit.unshift([now(),'Itemised cheque dispatched to vault',r,sess.name,sess.role,rq[3],`For ${rq[2]} (${reqRef})`]);await save(data);return send(res,201,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/vault/receive-item'){try{if(!has(sess,'vault.submit')&&!has(sess,'vault.authorise'))return send(res,403,{error:'You do not have permission to receive vault items.'});const body=await collect(req);const data=await load();data.vaultItems=data.vaultItems||[];const item=data.vaultItems.find(v=>v[0]===body.ref&&v[6]==='Awaiting Confirmation');if(!item)return send(res,404,{error:'Item not found or already received.'});if(!inScope(sess,item[4]))return send(res,403,{error:'This item belongs to another branch vault.'});item[6]='Ready for Collection';const msg=`Dear ${item[1]}, your cheque book is ready for collection at ${item[4]}, Akuapem Community Bank. Please bring a valid photo ID.`;const cfg=await loadSms();const outcome=await sendSms(cfg,item[3],msg);const status=outcome.ok?'Sent':(cfg.enabled?'Failed':'Not sent');notify(data,item[1],item[2],item[4],msg,'SMS',status);data.audit.unshift([now(),'Itemised cheque received & customer alerted',item[0],sess.name,sess.role,item[4],`SMS to ${item[3]}: ${outcome.detail}`]);await save(data);return send(res,200,{data:scope(data,sess),sms:{ok:outcome.ok,detail:outcome.detail}})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/aging/destroy'){try{if(!has(sess,'vault.authorise'))return send(res,403,{error:'You do not have permission to authorise cheque-book destruction.'});const body=await collect(req);const data=await load();const rf=String(body.ref||'');const rq=(data.requests||[]).find(r=>r[0]===rf);if(!rq)return send(res,404,{error:'Request not found.'});if(!inScope(sess,rq[3]))return send(res,403,{error:'This item is outside your branch scope.'});if(!/ready for issuance/i.test(String(rq[5])))return send(res,400,{error:'Only uncollected (ready-for-issuance) books can be destroyed.'});let serials='';const b=(data.printBatches||[]).find(x=>(x.items||[]).some(it=>it.reqRef===rf));if(b){const it=(b.items||[]).find(it=>it.reqRef===rf);if(it&&it.serialStart)serials=`${it.serialStart} – ${it.serialEnd}`}const witness=String(body.witness||'').trim();const method=String(body.method||'Shredded').trim();data.destructions=data.destructions||[];const cert=ref('DST');data.destructions.unshift([cert,rf,rq[1],rq[2],rq[3],rq[4],serials||'—',sess.name,witness||'—',now(),method]);rq[5]='Destroyed';data.audit.unshift([now(),'Cheque book destroyed',rf,sess.name,sess.role,rq[3],`Uncollected >1yr; certificate ${cert}${witness?`; witnessed by ${witness}`:''}`]);await logSys('SECURITY','aging.destroy',sess.name,clientIp(req),`destroyed uncollected book ${rf} (${serials||'no serials'}), cert ${cert}`);await save(data);return send(res,200,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(url.pathname.startsWith('/api/batch/')&&req.method==='POST'){const bact=url.pathname.slice('/api/batch/'.length);let body;try{body=await collect(req)}catch{return send(res,400,{error:'Invalid request.'})}const data=await load();if(!Array.isArray(data.printBatches))data.printBatches=[];data.requestPhones=data.requestPhones||{};data.inventory=data.inventory||[];const respond=async()=>{await save(data);return send(res,200,{data:scope(data,sess)})};try{
    if(bact==='submit'){if(!has(sess,'vault.submit'))return send(res,403,{error:'You do not have permission to submit print batches.'});const refs=[...new Set((body.requests||[]).map(String))];if(!refs.length)return send(res,400,{error:'Select at least one authorised requisition.'});const items=[];let branch=null;for(const rf of refs){const rq=(data.requests||[]).find(r=>r[0]===rf);if(!rq)return send(res,404,{error:`Requisition ${rf} not found.`});if(rq[5]!=='Authorized')return send(res,400,{error:`Requisition ${rf} is not authorised (status: ${rq[5]}).`});if(branch&&rq[3]!==branch)return send(res,400,{error:'All requisitions in a batch must be from the same branch.'});branch=rq[3];if(!sess.global&&branch!==sess.branch)return send(res,403,{error:'You can only batch your own branch’s requisitions.'});items.push({reqRef:rq[0],account:rq[1],customer:rq[2],phone:data.requestPhones[rq[0]]||'',size:rq[4],leaves:leavesOf(rq[4]),serialStart:'',serialEnd:''})}const id=ref('PB');const b={id,branch,status:'Submitted to Head Office',items,createdBy:sess.name,createdAt:now(),maker:'',log:[]};batchLog(b,sess.name,'Submitted to head office for printing');data.printBatches.unshift(b);for(const rf of refs){const rq=(data.requests||[]).find(r=>r[0]===rf);if(rq)rq[5]='In Print Batch'}data.audit.unshift([now(),'Print batch submitted',id,sess.name,sess.role,branch,`${items.length} requisition(s) sent to head office`]);return await respond()}
    const b=data.printBatches.find(x=>x.id===body.id);if(!b)return send(res,404,{error:'Batch not found.'});if(['confirm','accept','reject'].includes(bact)&&!inScope(sess,b.branch))return send(res,403,{error:'This batch belongs to another branch.'});
    if(bact==='print'){if(!has(sess,'vault.dispatch'))return send(res,403,{error:'Head-office permission required.'});if(b.status!=='Submitted to Head Office')return send(res,400,{error:'Batch is not awaiting printing.'});b.status='Sent for Printing';batchLog(b,sess.name,'Soft copy exported; sent for printing');data.audit.unshift([now(),'Print batch sent for printing',b.id,sess.name,sess.role,b.branch,'Soft copy exported to printer']);return await respond()}
    if(bact==='receive'){if(!has(sess,'vault.dispatch'))return send(res,403,{error:'Head-office permission required.'});if(!['Sent for Printing','Submitted to Head Office'].includes(b.status))return send(res,400,{error:'Batch is not awaiting serial entry.'});const serials=body.serials||{};const ranges=[];for(const it of b.items){const raw=String(serials[it.reqRef]||'').trim();if(!/^\d{1,6}$/.test(raw))return send(res,400,{error:`Enter a valid start serial (up to 6 digits) for ${it.customer}.`});const start=parseInt(raw,10);const end=start+it.leaves-1;if(end>999999)return send(res,400,{error:`Serial range for ${it.customer} exceeds 6 digits.`});ranges.push([it.reqRef,start,end])}for(let i=0;i<ranges.length;i++)for(let j=i+1;j<ranges.length;j++)if(ranges[i][1]<=ranges[j][2]&&ranges[j][1]<=ranges[i][2])return send(res,400,{error:'Serial ranges overlap between cheque books.'});for(const it of b.items){const start=parseInt(String(serials[it.reqRef]).trim(),10);it.serialStart=pad6(start);it.serialEnd=pad6(start+it.leaves-1)}b.status='In Head-Office Vault';batchLog(b,sess.name,'Serials entered; received into head-office vault');data.audit.unshift([now(),'Cheques received into head-office vault',b.id,sess.name,sess.role,b.branch,`${b.items.length} book(s) serialised`]);return await respond()}
    if(bact==='transfer'){if(!has(sess,'vault.dispatch'))return send(res,403,{error:'Head-office permission required.'});if(b.status!=='In Head-Office Vault')return send(res,400,{error:'Batch is not in the head-office vault.'});b.status='In Transit to Branch';batchLog(b,sess.name,'Transferred to branch');data.audit.unshift([now(),'Batch transferred to branch',b.id,sess.name,sess.role,b.branch,'Sent to branch for acceptance']);return await respond()}
    if(bact==='confirm'){if(!has(sess,'vault.submit'))return send(res,403,{error:'You do not have permission to confirm receipt.'});if(b.status!=='In Transit to Branch')return send(res,400,{error:'Batch is not in transit.'});b.status='Pending Branch Authorisation';b.maker=sess.name;batchLog(b,sess.name,'Receipt confirmed; awaiting authorisation');data.audit.unshift([now(),'Branch confirmed batch receipt',b.id,sess.name,sess.role,b.branch,'Awaiting second-officer authorisation']);return await respond()}
    if(bact==='accept'){if(!has(sess,'vault.authorise'))return send(res,403,{error:'Authorisation permission required.'});if(b.status!=='Pending Branch Authorisation')return send(res,400,{error:'Batch is not pending authorisation.'});if(b.maker&&b.maker===sess.name)return send(res,403,{error:'The confirming officer cannot authorise the same batch.'});b.status='In Branch Vault';batchLog(b,sess.name,'Authorised into branch vault');const cfg=await loadSms();let alerted=0;for(const it of b.items){const invRef=ref('INV');data.inventory.unshift([invRef,b.branch,it.size,`${it.serialStart} – ${it.serialEnd}`,String(it.leaves),String(it.leaves),'Active']);const rq=(data.requests||[]).find(r=>r[0]===it.reqRef);if(rq)rq[5]='Ready for Issuance';if(it.phone){const msg=`Dear ${it.customer}, your cheque book (${it.serialStart}–${it.serialEnd}) has arrived at ${b.branch}, Akuapem Community Bank, and is ready for collection. Please bring valid photo ID.`;const out=await sendSms(cfg,it.phone,msg);notify(data,it.customer,it.account,b.branch,msg,'SMS',out.ok?'Sent':(cfg.enabled?'Failed':'Not sent'));alerted++}}data.audit.unshift([now(),'Batch accepted into branch vault',b.id,sess.name,sess.role,b.branch,`${b.items.length} book(s) added to inventory; ${alerted} customer(s) alerted`]);return await respond()}
    if(bact==='reject'){if(!has(sess,'vault.authorise'))return send(res,403,{error:'Authorisation permission required.'});if(!['Pending Branch Authorisation','In Transit to Branch'].includes(b.status))return send(res,400,{error:'Batch cannot be returned at this stage.'});b.status='In Head-Office Vault';b.maker='';batchLog(b,sess.name,`Returned to head office: ${String(body.reason||'discrepancy on receipt')}`);data.audit.unshift([now(),'Batch returned to head office',b.id,sess.name,sess.role,b.branch,String(body.reason||'Discrepancy on receipt')]);return await respond()}
    return send(res,404,{error:'Unknown batch action.'})}catch(e){return send(res,400,{error:'Invalid request.'})}}
  if(url.pathname.startsWith('/api/admin/')&&req.method==='POST'){const act=url.pathname.slice('/api/admin/'.length);const canManage=has(sess,'admin.manage'),canAuth=has(sess,'admin.authorise');if(!canManage&&!canAuth){await logSys('WARN','authz.denied',sess.name,clientIp(req),`admin ${act}`);return send(res,403,{error:'Administration permission required.'})}await logSys('SECURITY','admin.'+act.replace(/\//g,'.'),sess.name,clientIp(req),'administrative action');let body;try{body=await collect(req)}catch{return send(res,400,{error:'Invalid request.'})}const data=await load();ensureGov(data);const dir=data.directory;const bad=m=>send(res,400,{error:m});const log=(action,target,detail)=>data.adminAudit.unshift([now(),sess.name,action,target||'—',detail||'']);const directAdmin=!REQUIRE_FOUR_EYES&&canManage&&canAuth;let _direct=null;const queueChange=(type,summary,targetUid,payload)=>{if(directAdmin){_direct={type,summary,targetUid:targetUid||'',payload};return}const id=ref('CHG');data.adminQueue.unshift({id,type,summary,targetUid:targetUid||'',submittedBy:sess.name,submittedAt:now(),payload});log('Change submitted for authorisation',targetUid||type,summary)};const done=async()=>{if(_direct){const chg=_direct;_direct=null;const err=applyChange(data,chg);if(err)return bad(err);let tempPassword=null;if(chg.type==='user/create'){tempPassword=genPassword();await setPassword(chg.payload.id,tempPassword)}log('Change applied directly (four-eyes waived for System Admin)',chg.targetUid||chg.type,chg.summary);await logSys('SECURITY','admin.direct',sess.name,clientIp(req),chg.summary);await save(data);const p=await statePayload(data,principal(data,sess.uid));if(tempPassword){p.tempPassword=tempPassword;p.tempUser=chg.payload.id}return send(res,200,p)}await save(data);return send(res,200,await statePayload(data,principal(data,sess.uid)))};
    if(['user/create','user/phone','user/resetpw','user/role','user/groups/add','user/groups/remove','user/disable','user/enable','user/recertify','role/save','role/delete','group/save','group/delete','sod/add','sod/remove','branch/create','sms/save','sms/test'].includes(act)&&!canManage)return send(res,403,{error:'Manage permission required.'});
    if(act==='sms/save'){const cur=await loadSms();const cfg={provider:'arkesel',senderId:String(body.senderId||'').trim(),apiKey:body.apiKey?String(body.apiKey).trim():cur.apiKey,enabled:!!body.enabled};await saveSms(cfg);log('SMS gateway settings updated','SMS',`Sender "${cfg.senderId}", ${cfg.enabled?'enabled':'disabled'}`);await save(data);return send(res,200,await statePayload(data,principal(data,sess.uid)))}
    if(act==='sms/test'){const cfg=await loadSms();const outcome=await sendSms(cfg,body.phone,`Test message from ${cfg.senderId||'Akuapem Community Bank'} — your SMS gateway is working.`);log('SMS test message sent','SMS',`${normPhone(body.phone)}: ${outcome.detail}`);await save(data);return send(res,outcome.ok?200:400,{...(await statePayload(data,principal(data,sess.uid))),smsTest:outcome})}
    try{switch(act){
      case 'user/create':{const id=String(body.id||'').toLowerCase().trim();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(id))return bad('Enter a valid staff email address.');if(dir[id])return bad('A user with that staff ID already exists.');if(!String(body.name||'').trim())return bad('Enter the user name.');if(!data.roles[body.role])return bad('Select a valid role.');const branch=body.branch;if(branch!=='All Branches'&&!branchesOf(data).includes(branch))return bad('Select a valid branch.');const phone=normPhone(body.phone);if(phone.length<11||phone.length>15)return bad('Enter a valid phone number (e.g. 0244000000) so the user can reset their password by SMS.');queueChange('user/create',`Create user ${String(body.name).trim()} (${id}) as ${body.role}`,id,{id,name:String(body.name).trim(),branch,role:body.role,phone});return await done()}
      case 'user/phone':{const u=dir[body.uid];if(!u)return send(res,404,{error:'User not found.'});const phone=normPhone(body.phone);if(phone.length<11||phone.length>15)return bad('Enter a valid phone number (e.g. 0244000000).');queueChange('user/phone',`Set reset phone for ${u.name} to ${maskKey(phone)}`,body.uid,{uid:body.uid,phone});return await done()}
      case 'branch/create':{const name=String(body.name||'').trim().replace(/\s+/g,' ');if(name.length<2||name.length>40)return bad('Enter a branch name between 2 and 40 characters.');if(branchesOf(data).some(b=>String(b).toLowerCase()===name.toLowerCase()))return bad('That branch already exists.');queueChange('branch/create',`Add branch “${name}”`,'',{name});return await done()}
      case 'user/role':{const u=dir[body.uid];if(!u)return send(res,404,{error:'User not found.'});if(!data.roles[body.role])return bad('Select a valid role.');const c=sodConflict(data,effPerms(data,body.role,u.groups));if(c)return bad(`That role would breach segregation of duties (${c[0]} vs ${c[1]}).`);queueChange('user/role',`Role ${u.role} → ${body.role} for ${u.name}`,body.uid,{uid:body.uid,role:body.role});return await done()}
      case 'user/groups/add':{const u=dir[body.uid];if(!u)return send(res,404,{error:'User not found.'});if(!data.groups[body.group])return bad('Select a valid group.');const groups=[...new Set([...(u.groups||[]),body.group])];const c=sodConflict(data,effPerms(data,u.role,groups));if(c)return bad(`That group would breach segregation of duties (${c[0]} vs ${c[1]}).`);queueChange('user/groups/add',`Add ${u.name} to group ${body.group}`,body.uid,{uid:body.uid,group:body.group});return await done()}
      case 'user/groups/remove':{const u=dir[body.uid];if(!u)return send(res,404,{error:'User not found.'});u.groups=(u.groups||[]).filter(g=>g!==body.group);log('Removed from group',body.uid,body.group);return await done()}
      case 'user/disable':{const u=dir[body.uid];if(!u)return send(res,404,{error:'User not found.'});if(body.uid===sess.uid)return bad('You cannot disable your own account.');u.status='Disabled';log('User disabled',body.uid,'Access revoked; sessions invalidated on next request');return await done()}
      case 'user/enable':{const u=dir[body.uid];if(!u)return send(res,404,{error:'User not found.'});queueChange('user/enable',`Re-enable ${u.name}`,body.uid,{uid:body.uid});return await done()}
      case 'user/recertify':{const u=dir[body.uid];if(!u)return send(res,404,{error:'User not found.'});u.lastReviewed=now();log('Access recertified',body.uid,`Role ${u.role}`);return await done()}
      case 'user/resetpw':{const u=dir[body.uid];if(!u)return send(res,404,{error:'User not found.'});if(body.mode==='otp'){if(!u.phone)return bad('This user has no phone on file — use the one-time password option instead.');const code=String(crypto.randomInt(0,1000000)).padStart(6,'0');await otpPut(body.uid,code);const cfg=await loadSms();const outcome=await sendSms(cfg,u.phone,`Akuapem Community Bank: your password reset code is ${code}. It expires in 10 minutes. Do not share it with anyone.`);log('Password reset code sent',body.uid,`SMS to ${maskKey(u.phone)}: ${outcome.detail}`);await logSys('SECURITY','password.admin_reset',sess.name,clientIp(req),`sent reset code to ${body.uid} (${outcome.ok?'delivered':'not delivered'})`);await save(data);return send(res,200,{...(await statePayload(data,principal(data,sess.uid))),resetSms:outcome})}const pw=genPassword();await setPassword(body.uid,pw);log('Password reset — one-time password issued',body.uid,'Admin-issued temporary password (user must change at next sign-in)');await logSys('SECURITY','password.admin_reset',sess.name,clientIp(req),`issued one-time password for ${body.uid}`);await save(data);const p=await statePayload(data,principal(data,sess.uid));p.tempPassword=pw;p.tempUser=body.uid;return send(res,200,p)}
      case 'role/save':{const name=String(body.name||'').trim();if(!name)return bad('Enter a role name.');const perms=(body.permissions||[]).filter(x=>PERM_IDS.includes(x));const c=sodConflict(data,new Set(perms));if(c)return bad(`A role cannot combine ${c[0]} and ${c[1]} (segregation of duties).`);queueChange('role/save',`${data.roles[name]?'Update':'Create'} role ${name}`,name,{name,label:String(body.label||name).trim(),global:!!body.global,permissions:perms,system:!!data.roles[name]?.system});return await done()}
      case 'role/delete':{const r=data.roles[body.name];if(!r)return send(res,404,{error:'Role not found.'});if(r.system)return bad('Built-in roles cannot be deleted.');if(Object.values(dir).some(u=>u.role===body.name)||Object.values(data.groups).some(g=>(g.roles||[]).includes(body.name)))return bad('Role is assigned to users or groups.');delete data.roles[body.name];log('Role deleted',body.name,'');return await done()}
      case 'group/save':{const name=String(body.name||'').trim();if(!name)return bad('Enter a group name.');const gr=(body.roles||[]).filter(r=>data.roles[r]);const c=sodConflict(data,new Set(gr.flatMap(r=>data.roles[r].permissions)));if(c)return bad(`A group cannot combine ${c[0]} and ${c[1]}.`);const branch=body.branch||'All Branches';queueChange('group/save',`${data.groups[name]?'Update':'Create'} group ${name}`,name,{name,description:String(body.description||'').trim(),branch,roles:gr});return await done()}
      case 'group/delete':{if(!data.groups[body.name])return send(res,404,{error:'Group not found.'});if(Object.values(dir).some(u=>(u.groups||[]).includes(body.name)))return bad('Group still has members.');delete data.groups[body.name];log('Group deleted',body.name,'');return await done()}
      case 'sod/add':{const a=body.a,b=body.b;if(!PERM_IDS.includes(a)||!PERM_IDS.includes(b)||a===b)return bad('Choose two different permissions.');if(!(data.sodMatrix||[]).some(p=>(p[0]===a&&p[1]===b)||(p[0]===b&&p[1]===a)))data.sodMatrix.push([a,b]);log('SoD rule added',`${a} ⨂ ${b}`,'');return await done()}
      case 'sod/remove':{queueChange('sod/remove',`Remove SoD rule ${body.a} ⨂ ${body.b}`,'',{a:body.a,b:body.b});return await done()}
      case 'change/authorise':{if(!canAuth)return send(res,403,{error:'Authorisation permission required.'});const i=data.adminQueue.findIndex(c=>c.id===body.id);if(i<0)return send(res,404,{error:'Change not found.'});const chg=data.adminQueue[i];if(!directAdmin){if(chg.submittedBy===sess.name)return send(res,403,{error:'The submitting administrator cannot authorise their own change.'});if(chg.targetUid&&chg.targetUid===sess.uid)return send(res,403,{error:'You cannot authorise a change affecting your own account.'});}const err=applyChange(data,chg);if(err)return bad(err);let tempPassword=null;if(chg.type==='user/create'){tempPassword=genPassword();await setPassword(chg.payload.id,tempPassword)}data.adminQueue.splice(i,1);log('Change authorised & applied',chg.targetUid||chg.type,chg.summary);await save(data);const payload=await statePayload(data,principal(data,sess.uid));if(tempPassword){payload.tempPassword=tempPassword;payload.tempUser=chg.payload.id}return send(res,200,payload)}
      case 'change/reject':{if(!canAuth)return send(res,403,{error:'Authorisation permission required.'});const i=data.adminQueue.findIndex(c=>c.id===body.id);if(i<0)return send(res,404,{error:'Change not found.'});const chg=data.adminQueue[i];data.adminQueue.splice(i,1);log('Change rejected',chg.targetUid||chg.type,chg.summary);return await done()}
      default:return send(res,404,{error:'Unknown administration action.'});
    }}catch{return send(res,400,{error:'Invalid request.'})}
  }
  const file=url.pathname==='/'?'index.html':url.pathname.slice(1);const type=publicFiles[file];
  const fp=path.join(root,'public',file);
  if(req.method!=='GET'||!type||!fs.existsSync(fp)){res.writeHead(404,securityHeaders);return res.end('Not found')}
  const isImg=type.startsWith('image/');res.writeHead(200,{...securityHeaders,'Content-Type':isImg?type:`${type}; charset=utf-8`,'Cache-Control':isImg?'public, max-age=86400':'no-cache'});fs.createReadStream(fp).pipe(res);
  }catch(err){console.error('handler error:',err&&err.message);try{await logSys('ERROR','error','system',clientIp(req),err&&err.message)}catch(e){}if(!res.headersSent)send(res,500,{error:'Server error.'})}};
const server=http.createServer(handler);
if(require.main===module){ready().then(()=>{const port=process.env.PORT||3000;server.listen(port,()=>console.log(`Cheque Management System running on http://localhost:${port} (db: ${db.backend()})`))}).catch(e=>{console.error('startup failed:',e);process.exit(1)})}
// Default export is the request handler itself, so this module is valid as a
// serverless function entry (Vercel requires the default export to be a function).
// The handler/server are also attached as named properties for other callers.
module.exports=handler;
module.exports.handler=handler;
module.exports.server=server;
