const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');

const root = __dirname;
const storePath = path.join(root, 'data', 'records.json');
const roles = {
  'System Admin': { global: true, approvals: true },
  'Head-Office Users': { global: true, approvals: true },
  'Branch Manager': { global: false, approvals: true },
  'Branch Operations': { global: false, approvals: false },
  'Customer Service': { global: false, approvals: false }
};
const seed = {
  requests: [['CBR-2026-0841','AC-00129482','Ama Ofori','Nsawam Branch','50 leaves','Pending Authorization','24 Jul, 09:42'],['CBR-2026-0838','AC-00773819','Kwaku Mensah','Koforidua Branch','100 leaves','Authorized','23 Jul, 15:15'],['CBR-2026-0836','AC-00359510','Akosua Frimpong','Aburi Branch','50 leaves','Issued','23 Jul, 11:30'],['CBR-2026-0833','AC-00902811','Bright Logistics Ltd','Madina Branch','100 leaves','Rejected','22 Jul, 16:21']],
  inventory: [['INV-NS-001','Nsawam Branch','ACB Standard','000120001 – 000120500','500','428','Active'],['INV-KF-002','Koforidua Branch','ACB Corporate','000125001 – 000125300','300','112','Active'],['INV-AB-001','Aburi Branch','ACB Standard','000130001 – 000130200','200','0','Archived'],['INV-MD-003','Madina Branch','ACB Standard','000150001 – 000150600','600','390','Active']],
  issuance: [['ISS-02631','CBR-2026-0836','Akosua Frimpong','Aburi Branch','000130042 – 000130091','Issued','23 Jul, 14:10'],['ISS-02629','CBR-2026-0828','Yaw Boateng','Nsawam Branch','000120118 – 000120167','Collected','22 Jul, 10:05'],['ISS-02628','CBR-2026-0826','Abena Nyarko','Koforidua Branch','000125044 – 000125093','Awaiting Collection','21 Jul, 16:22']],
  verifications: [['VFY-19044','000120151','AC-00129482','Ama Ofori','Nsawam Branch','₵8,450.00','Active'],['VFY-19041','000125069','AC-00773819','Kwaku Mensah','Koforidua Branch','₵15,200.00','Stopped'],['VFY-19036','000150288','AC-00902811','Bright Logistics Ltd','Madina Branch','₵4,765.00','Returned']],
  stops: [['STP-0104','000125069','Kwaku Mensah','Koforidua Branch','Lost cheque','Stopped','24 Jul, 08:55'],['CAN-0089','000120094','Nana Addo','Nsawam Branch','Customer request','Pending Authorization','23 Jul, 14:40']],
  returns: [['RET-0058','000150288','Bright Logistics Ltd','Madina Branch','Insufficient funds','₵4,765.00','Returned'],['RET-0057','000130099','Gifty Asante','Aburi Branch','Signature differs','₵2,100.00','Returned']],
  vault: [['VLT-2026-0031','Nsawam Branch','ACB Standard','000121001 – 000121500','500 leaves','Awaiting Confirmation','24 Jul, 16:10'],['VLT-2026-0030','Koforidua Branch','ACB Corporate','000126001 – 000126300','300 leaves','Awaiting Confirmation','24 Jul, 14:02'],['VLT-2026-0029','Madina Branch','ACB Standard','000151001 – 000151400','400 leaves','Awaiting Confirmation','24 Jul, 11:18'],['VLT-2026-0028','Aburi Branch','ACB Standard','000131001 – 000131200','200 leaves','Accepted','23 Jul, 10:40']],
  approvals: [['APR-0445','Cheque book request','CBR-2026-0841','Ama Ofori','Nsawam Branch','Customer Service','24 Jul, 09:42'],['APR-0444','Cheque cancellation','CAN-0089','Nana Addo','Nsawam Branch','Branch Operations','23 Jul, 14:40'],['APR-0441','Range registration','INV-MD-003','Madina Branch','Madina Branch','Branch Operations','23 Jul, 09:10']],
  audit: [['24 Jul, 09:42','Cheque book request created','CBR-2026-0841','Esi Nkrumah','Customer Service','Nsawam Branch','Initial request submitted'],['24 Jul, 08:55','Stop cheque authorised','STP-0104','Kojo Asare','Branch Manager','Koforidua Branch','Lost cheque confirmed'],['23 Jul, 15:15','Cheque book request authorised','CBR-2026-0838','Adwoa Owusu','Branch Manager','Koforidua Branch','Approved for issuance'],['23 Jul, 14:10','Cheque book issued','ISS-02631','Yaw Sarpong','Branch Operations','Aburi Branch','Identity verified']]
};
function load(){fs.mkdirSync(path.dirname(storePath),{recursive:true});if(!fs.existsSync(storePath))fs.writeFileSync(storePath,JSON.stringify(seed,null,2));const data=JSON.parse(fs.readFileSync(storePath,'utf8'));let changed=false;for(const key in seed)if(!data[key]){data[key]=seed[key];changed=true}if(changed)save(data);return data}
function save(data){fs.writeFileSync(storePath,JSON.stringify(data,null,2))}
const securityHeaders={'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Permissions-Policy':'geolocation=(), microphone=(), camera=(), payment=()','Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Resource-Policy':'same-origin','Content-Security-Policy':"default-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self' 'unsafe-inline'; connect-src 'self'"};
function send(res,status,body){res.writeHead(status,{...securityHeaders,'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(body))}
const MAX_BODY=32*1024;
function collect(req){return new Promise((resolve,reject)=>{let raw='';let size=0;let over=false;req.on('data',c=>{if(over)return;size+=c.length;if(size>MAX_BODY){over=true;reject(new Error('Payload too large'))}else raw+=c});req.on('end',()=>{if(over)return;try{resolve(JSON.parse(raw||'{}'))}catch{reject(new Error('Malformed JSON'))}});req.on('error',()=>{if(!over)reject(new Error('Stream error'))})})}
const rateHits=new Map();
function rateLimited(ip){const now=Date.now(),windowMs=60000,max=120;const arr=(rateHits.get(ip)||[]).filter(t=>now-t<windowMs);arr.push(now);rateHits.set(ip,arr);if(rateHits.size>5000)for(const[k,v]of rateHits)if(!v.some(t=>now-t<windowMs))rateHits.delete(k);return arr.length>max}
const publicFiles={'index.html':'text/html','app.js':'application/javascript','styles.css':'text/css'};
const crypto=require('node:crypto');
const SESSION_TTL=8*3600*1000;
const sessions=new Map();
function cookies(req){const out={};(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=p.slice(i+1).trim()});return out}
function getSession(req){const id=cookies(req)['acb_session'];if(!id)return null;const s=sessions.get(id);if(!s)return null;if(Date.now()-s.ts>SESSION_TTL){sessions.delete(id);return null}return s}
function sessionCookie(id,maxAge){return `acb_session=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAge}`}
function scope(data,sess){if(!sess||roles[sess.role]?.global)return data;const b=sess.branch;const out={};for(const k in data)out[k]=Array.isArray(data[k])?data[k].filter(r=>Array.isArray(r)&&r.includes(b)):data[k];return out}
function now(){return new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date())}
function allowed(role,branch,itemBranch){return roles[role]?.global||branch===itemBranch}
const branchList=['Nsawam Branch','Koforidua Branch','Aburi Branch','Adukrom Branch','Mamfe Branch','Madina Branch'];
function ref(prefix){return `${prefix}-${Date.now().toString().slice(-6)}`}
function need(fields,keys){for(const k of keys)if(!String(fields[k]||'').trim())return `The "${k}" field is required.`;return null}
const builders={
  request(f,branch){const e=need(f,['account','customer','book']);if(e)return{error:e};const r=ref('CBR');return{bucket:'requests',label:'Cheque book request',ref:r,subject:f.customer,entry:[r,f.account,f.customer,branch,f.book,'Pending Authorization',now()]}},
  inventory(f,branch){const e=need(f,['type','start','end']);if(e)return{error:e};const start=parseInt(f.start,10),end=parseInt(f.end,10);if(!Number.isFinite(start)||!Number.isFinite(end))return{error:'Start and end serials must be numeric.'};if(end<start)return{error:'End serial cannot be lower than the start serial.'};const width=Math.max(String(f.start).trim().length,String(f.end).trim().length);const pad=n=>String(n).padStart(width,'0');const total=String(end-start+1);const r=ref('INV');return{bucket:'inventory',label:'Range registration',ref:r,subject:f.type,entry:[r,branch,f.type,`${pad(start)} – ${pad(end)}`,total,total,'Active']}},
  issuance(f,branch){const e=need(f,['request','account','range']);if(e)return{error:e};const r=ref('ISS');return{bucket:'issuance',label:'Cheque book issuance',ref:r,subject:f.account,entry:[r,f.request,f.account,branch,f.range,'Awaiting Collection',now()]}},
  stop(f,branch){const e=need(f,['cheque','account','reason']);if(e)return{error:e};const r=ref(/cancel/i.test(f.instruction||'')?'CAN':'STP');return{bucket:'stops',label:'Stop-cheque instruction',ref:r,subject:f.account,entry:[r,f.cheque,f.account,branch,f.reason,'Pending Authorization',now()]}},
  returns(f,branch){const e=need(f,['cheque','account','reason']);if(e)return{error:e};const r=ref('RET');return{bucket:'returns',label:'Returned cheque record',ref:r,subject:f.account,entry:[r,f.cheque,f.account,branch,f.reason,String(f.amount||'').trim()||'—','Returned']}}
};
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');
  if(url.pathname.startsWith('/api/')&&rateLimited(req.socket.remoteAddress||'unknown'))return send(res,429,{error:'Too many requests. Please slow down.'});
  if(req.method==='POST'&&url.pathname==='/api/session'){try{const body=await collect(req);const role=roles[body.role];if(!role)return send(res,400,{error:'Select a valid role.'});const chosen=String(body.branch||'').trim();if(!role.global&&!branchList.includes(chosen))return send(res,400,{error:'Select a valid branch.'});const branch=role.global?'All Branches':chosen;const id=crypto.randomBytes(18).toString('hex');sessions.set(id,{role:body.role,branch,ts:Date.now()});res.writeHead(200,{...securityHeaders,'Content-Type':'application/json','Cache-Control':'no-store','Set-Cookie':sessionCookie(id,SESSION_TTL/1000)});return res.end(JSON.stringify({role:body.role,branch,data:scope(load(),{role:body.role,branch})}))}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/logout'){const id=cookies(req)['acb_session'];if(id)sessions.delete(id);res.writeHead(200,{...securityHeaders,'Content-Type':'application/json','Cache-Control':'no-store','Set-Cookie':sessionCookie('',0)});return res.end(JSON.stringify({ok:true}))}
  const sess=getSession(req);
  if(url.pathname.startsWith('/api/')&&!sess)return send(res,401,{error:'Not authenticated. Please sign in.'});
  if(req.method==='GET'&&url.pathname==='/api/state')return send(res,200,{data:scope(load(),sess),role:sess.role,branch:sess.branch});
  if(req.method==='POST'&&url.pathname==='/api/transactions'){try{const body=await collect(req);const role=roles[sess.role];const builder=builders[body.module];if(!builder)return send(res,400,{error:'Invalid transaction type.'});const fields=body.fields||{};const targetBranch=String(fields.branch||sess.branch||'').trim();if(!branchList.includes(targetBranch))return send(res,400,{error:'A valid branch must be selected.'});if(!role.global&&targetBranch!==sess.branch)return send(res,403,{error:'You can only create records for your own branch.'});const built=builder(fields,targetBranch);if(built.error)return send(res,400,{error:built.error});const data=load();data[built.bucket].unshift(built.entry);data.approvals.unshift([ref('APR'),built.label,built.ref,built.subject,targetBranch,sess.role,now()]);data.audit.unshift([now(),`${built.label} submitted`,built.ref,sess.role,sess.role,targetBranch,'Submitted for maker-checker approval']);save(data);return send(res,201,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/authorizations/approve'){try{if(!roles[sess.role]?.approvals)return send(res,403,{error:'Approval permission required'});const data=load();const item=data.approvals[0];if(!item)return send(res,404,{error:'Nothing awaiting approval'});if(!allowed(sess.role,sess.branch,item[4]))return send(res,403,{error:'Outside branch scope'});data.approvals.shift();data.audit.unshift([now(),'Transaction authorised',item[2],sess.role,sess.role,item[4],'Authorised through maker-checker workflow']);save(data);return send(res,200,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request'})}}
  if(req.method==='POST'&&url.pathname==='/api/vault/push'){try{const role=roles[sess.role];if(!role.global)return send(res,403,{error:'Only head-office users can dispatch cheque stock to a branch vault.'});const body=await collect(req);const f=body.fields||{};const dest=String(f.branch||'').trim();if(!branchList.includes(dest))return send(res,400,{error:'Select a valid destination branch.'});const e=need(f,['type','start','end']);if(e)return send(res,400,{error:e});const start=parseInt(f.start,10),end=parseInt(f.end,10);if(!Number.isFinite(start)||!Number.isFinite(end))return send(res,400,{error:'Start and end serials must be numeric.'});if(end<start)return send(res,400,{error:'End serial cannot be lower than the start serial.'});const width=Math.max(String(f.start).trim().length,String(f.end).trim().length);const pad=n=>String(n).padStart(width,'0');const total=end-start+1;const data=load();if(!data.vault)data.vault=[];const r=ref('VLT');data.vault.unshift([r,dest,f.type,`${pad(start)} – ${pad(end)}`,`${total} leaves`,'Awaiting Confirmation',now()]);data.audit.unshift([now(),'Cheque stock dispatched to vault',r,sess.role,sess.role,dest,'Awaiting branch reconciliation and confirmation']);save(data);return send(res,201,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/vault/accept'){try{const role=roles[sess.role];const permitted=role.global||['Branch Manager','Branch Operations'].includes(sess.role);if(!permitted)return send(res,403,{error:'You do not have permission to accept vault stock into inventory.'});const body=await collect(req);const data=load();if(!data.vault)data.vault=[];const idx=data.vault.findIndex(v=>v[0]===body.ref&&v[5]==='Awaiting Confirmation');if(idx<0)return send(res,404,{error:'Batch not found or already accepted.'});const item=data.vault[idx];if(!role.global&&item[1]!==sess.branch)return send(res,403,{error:'This batch belongs to another branch vault.'});const total=String(item[4]).replace(/[^0-9]/g,'')||'0';const invRef=ref('INV');data.inventory.unshift([invRef,item[1],item[2],item[3],total,total,'Active']);item[5]='Accepted';data.audit.unshift([now(),'Vault stock reconciled and accepted',item[0],sess.role,sess.role,item[1],`Hard copies reconciled; moved to inventory as ${invRef}`]);save(data);return send(res,200,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  const file=url.pathname==='/'?'index.html':url.pathname.slice(1);const type=publicFiles[file];
  if(req.method!=='GET'||!type){res.writeHead(404,securityHeaders);return res.end('Not found')}
  res.writeHead(200,{...securityHeaders,'Content-Type':`${type}; charset=utf-8`,'Cache-Control':'no-cache'});fs.createReadStream(path.join(root,file)).pipe(res)});
const port=process.env.PORT||3000;server.listen(port,()=>console.log(`Cheque Management System running on http://localhost:${port}`));
