const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');

const root = __dirname;
const dataDir = process.env.DATA_DIR || path.join(root, 'data');
const storePath = path.join(dataDir, 'records.json');
const PERMISSIONS = [
  { id: 'request.create', label: 'Create cheque book request', cat: 'Transactions' },
  { id: 'inventory.create', label: 'Register inventory range', cat: 'Transactions' },
  { id: 'issuance.create', label: 'Issue cheque book', cat: 'Transactions' },
  { id: 'stop.create', label: 'Raise stop / cancel cheque', cat: 'Transactions' },
  { id: 'returns.create', label: 'Record returned cheque', cat: 'Transactions' },
  { id: 'txn.authorise', label: 'Authorise transactions', cat: 'Transactions' },
  { id: 'vault.dispatch', label: 'Dispatch stock to branch vault', cat: 'Vault' },
  { id: 'vault.submit', label: 'Reconcile & submit vault stock', cat: 'Vault' },
  { id: 'vault.authorise', label: 'Authorise vault into inventory', cat: 'Vault' },
  { id: 'notifications.view', label: 'View customer alerts', cat: 'Customer' },
  { id: 'customers.view', label: 'Search customer database', cat: 'Customer' },
  { id: 'customers.manage', label: 'Import & manage customer database', cat: 'Customer' },
  { id: 'reports.view', label: 'View reports', cat: 'Reporting' },
  { id: 'audit.view', label: 'View audit trail', cat: 'Reporting' },
  { id: 'admin.manage', label: 'Manage users, roles & groups', cat: 'Administration' },
  { id: 'admin.authorise', label: 'Authorise administrative changes', cat: 'Administration' }
];
const PERM_IDS = PERMISSIONS.map(p => p.id);
const seed = {
  requests: [['CBR-2026-0841','AC-00129482','Ama Ofori','Nsawam Branch','50 leaves','Pending Authorization','24 Jul, 09:42'],['CBR-2026-0838','AC-00773819','Kwaku Mensah','Koforidua Branch','100 leaves','Authorized','23 Jul, 15:15'],['CBR-2026-0836','AC-00359510','Akosua Frimpong','Aburi Branch','50 leaves','Issued','23 Jul, 11:30'],['CBR-2026-0833','AC-00902811','Bright Logistics Ltd','Madina Branch','100 leaves','Rejected','22 Jul, 16:21']],
  inventory: [['INV-NS-001','Nsawam Branch','ACB Standard','000120001 – 000120500','500','428','Active'],['INV-KF-002','Koforidua Branch','ACB Corporate','000125001 – 000125300','300','112','Active'],['INV-AB-001','Aburi Branch','ACB Standard','000130001 – 000130200','200','0','Archived'],['INV-MD-003','Madina Branch','ACB Standard','000150001 – 000150600','600','390','Active']],
  issuance: [['ISS-02631','CBR-2026-0836','Akosua Frimpong','Aburi Branch','000130042 – 000130091','Issued','23 Jul, 14:10'],['ISS-02629','CBR-2026-0828','Yaw Boateng','Nsawam Branch','000120118 – 000120167','Collected','22 Jul, 10:05'],['ISS-02628','CBR-2026-0826','Abena Nyarko','Koforidua Branch','000125044 – 000125093','Awaiting Collection','21 Jul, 16:22']],
  verifications: [['VFY-19044','000120151','AC-00129482','Ama Ofori','Nsawam Branch','₵8,450.00','Active'],['VFY-19041','000125069','AC-00773819','Kwaku Mensah','Koforidua Branch','₵15,200.00','Stopped'],['VFY-19036','000150288','AC-00902811','Bright Logistics Ltd','Madina Branch','₵4,765.00','Returned']],
  stops: [['STP-0104','000125069','Kwaku Mensah','Koforidua Branch','Lost cheque','Stopped','24 Jul, 08:55'],['CAN-0089','000120094','Nana Addo','Nsawam Branch','Customer request','Pending Authorization','23 Jul, 14:40']],
  returns: [['RET-0058','000150288','Bright Logistics Ltd','Madina Branch','Insufficient funds','₵4,765.00','Returned'],['RET-0057','000130099','Gifty Asante','Aburi Branch','Signature differs','₵2,100.00','Returned']],
  vault: [['VLT-2026-0031','Nsawam Branch','ACB Standard','000121001 – 000121500','500 leaves','Awaiting Confirmation','24 Jul, 16:10'],['VLT-2026-0030','Koforidua Branch','ACB Corporate','000126001 – 000126300','300 leaves','Awaiting Confirmation','24 Jul, 14:02'],['VLT-2026-0029','Madina Branch','ACB Standard','000151001 – 000151400','400 leaves','Awaiting Confirmation','24 Jul, 11:18'],['VLT-2026-0027','Koforidua Branch','ACB Standard','000127001 – 000127200','200 leaves','Pending Authorisation','24 Jul, 08:20'],['VLT-2026-0028','Aburi Branch','ACB Standard','000131001 – 000131200','200 leaves','Accepted','23 Jul, 10:40']],
  vaultMeta: {'VLT-2026-0027':{maker:'Kojo Asare',makerRole:'Branch Operations','submitted':'24 Jul, 08:20'}},
  approvals: [['APR-0445','Cheque book request','CBR-2026-0841','Ama Ofori','Nsawam Branch','Esi Nkrumah','24 Jul, 09:42'],['APR-0444','Cheque cancellation','CAN-0089','Nana Addo','Nsawam Branch','Kwabena Osei','23 Jul, 14:40'],['APR-0441','Range registration','INV-MD-003','Madina Branch','Yaa Serwaa','23 Jul, 09:10']],
  approvalMeta: {'APR-0445':{bucket:'requests',ref:'CBR-2026-0841',statusIdx:5,finalStatus:'Authorized',maker:'Esi Nkrumah',makerRole:'Customer Service'},'APR-0444':{bucket:'stops',ref:'CAN-0089',statusIdx:5,finalStatus:'Cancelled',maker:'Kwabena Osei',makerRole:'Branch Operations'},'APR-0441':{bucket:'inventory',ref:'INV-MD-003',statusIdx:6,finalStatus:'Active',maker:'Yaa Serwaa',makerRole:'Branch Operations'}},
  audit: [['24 Jul, 09:42','Cheque book request created','CBR-2026-0841','Esi Nkrumah','Customer Service','Nsawam Branch','Initial request submitted'],['24 Jul, 08:55','Stop cheque authorised','STP-0104','Kojo Asare','Branch Manager','Koforidua Branch','Lost cheque confirmed'],['23 Jul, 15:15','Cheque book request authorised','CBR-2026-0838','Adwoa Owusu','Branch Manager','Koforidua Branch','Approved for issuance'],['23 Jul, 14:10','Cheque book issued','ISS-02631','Yaw Sarpong','Branch Operations','Aburi Branch','Identity verified']],
  roles: {
    'System Admin': { label: 'System Admin', global: true, system: true, permissions: ['admin.manage','admin.authorise','audit.view','reports.view','customers.view','customers.manage'] },
    'Head-Office Users': { label: 'Head-Office Users', global: true, system: true, permissions: ['txn.authorise','vault.dispatch','vault.authorise','reports.view','audit.view','notifications.view','customers.view','customers.manage','admin.authorise'] },
    'Branch Manager': { label: 'Branch Manager', global: false, system: true, permissions: ['txn.authorise','vault.authorise','reports.view','audit.view','notifications.view','customers.view'] },
    'Branch Operations': { label: 'Branch Operations', global: false, system: true, permissions: ['request.create','inventory.create','issuance.create','stop.create','returns.create','vault.submit','notifications.view','customers.view'] },
    'Customer Service': { label: 'Customer Service', global: false, system: true, permissions: ['request.create','reports.view','notifications.view','customers.view'] }
  },
  groups: {
    'Koforidua Operations': { description: 'Koforidua branch operations team', branch: 'Koforidua Branch', roles: ['Branch Operations'] },
    'Head Office Controllers': { description: 'Head-office transaction authorisers', branch: 'All Branches', roles: ['Head-Office Users'] }
  },
  directory: {
    'admin@acb.com': { name: 'Akua Boateng', branch: 'All Branches', role: 'System Admin', groups: [], status: 'Active', lastReviewed: '01 Jul, 09:00' },
    'headoffice@acb.com': { name: 'Kofi Mensah', branch: 'All Branches', role: 'Head-Office Users', groups: [], status: 'Active', lastReviewed: '01 Jul, 09:00' },
    'manager.koforidua@acb.com': { name: 'Adwoa Owusu', branch: 'Koforidua Branch', role: 'Branch Manager', groups: [], status: 'Active', lastReviewed: '01 Jul, 09:00' },
    'ops.nsawam@acb.com': { name: 'Yaw Sarpong', branch: 'Nsawam Branch', role: 'Branch Operations', groups: [], status: 'Active', lastReviewed: '01 Jul, 09:00' },
    'cs.nsawam@acb.com': { name: 'Esi Nkrumah', branch: 'Nsawam Branch', role: 'Customer Service', groups: [], status: 'Active', lastReviewed: '01 Jul, 09:00' }
  },
  sodMatrix: [['request.create','txn.authorise'],['inventory.create','txn.authorise'],['issuance.create','txn.authorise'],['stop.create','txn.authorise'],['returns.create','txn.authorise'],['vault.submit','vault.authorise']],
  adminQueue: [],
  adminAudit: [['01 Jul, 09:00','System','Directory seeded','—','5 users, 5 roles, 2 groups provisioned']],
  notifications: [['NTF-100231','Akosua Frimpong','AC-00359510','Aburi Branch','SMS','Your cheque book 000130042 – 000130091 is ready for collection at Aburi Branch. Please bring valid photo ID.','Sent','23 Jul, 14:12'],['NTF-100228','Kwaku Mensah','AC-00773819','Koforidua Branch','SMS','Cheque stock has arrived at Koforidua Branch — your requested cheque book is being prepared for collection.','Sent','22 Jul, 10:06']],
  requestPhones: {'CBR-2026-0841':'233244000111','CBR-2026-0838':'233201234567','CBR-2026-0836':'233209876543'},
  vaultItems: [['VIT-2026-0012','Kwaku Mensah','AC-00773819','233201234567','Koforidua Branch','CBR-2026-0838','Awaiting Confirmation','24 Jul, 15:00'],['VIT-2026-0009','Akosua Frimpong','AC-00359510','233209876543','Aburi Branch','CBR-2026-0836','Ready for Collection','23 Jul, 12:20']]
};
function load(){fs.mkdirSync(path.dirname(storePath),{recursive:true});if(!fs.existsSync(storePath))fs.writeFileSync(storePath,JSON.stringify(seed,null,2));const data=JSON.parse(fs.readFileSync(storePath,'utf8'));let changed=false;for(const key in seed)if(!data[key]){data[key]=seed[key];changed=true}if(changed)save(data);return data}
function save(data){fs.writeFileSync(storePath,JSON.stringify(data,null,2))}
const securityHeaders={'X-Content-Type-Options':'nosniff','X-Frame-Options':'DENY','Referrer-Policy':'no-referrer','Permissions-Policy':'geolocation=(), microphone=(), camera=(), payment=()','Cross-Origin-Opener-Policy':'same-origin','Cross-Origin-Resource-Policy':'same-origin','Strict-Transport-Security':'max-age=31536000; includeSubDomains','Content-Security-Policy':"default-src 'self'; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; form-action 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self' 'unsafe-inline'; connect-src 'self'"};
function clientIp(req){return (req.headers['x-forwarded-for']||'').split(',')[0].trim()||req.socket.remoteAddress||'unknown'}
function send(res,status,body){res.writeHead(status,{...securityHeaders,'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(body))}
const MAX_BODY=32*1024;
function collect(req){return new Promise((resolve,reject)=>{let raw='';let size=0;let over=false;req.on('data',c=>{if(over)return;size+=c.length;if(size>MAX_BODY){over=true;reject(new Error('Payload too large'))}else raw+=c});req.on('end',()=>{if(over)return;try{resolve(JSON.parse(raw||'{}'))}catch{reject(new Error('Malformed JSON'))}});req.on('error',()=>{if(!over)reject(new Error('Stream error'))})})}
const rateHits=new Map();
function rateLimited(ip){const now=Date.now(),windowMs=60000,max=120;const arr=(rateHits.get(ip)||[]).filter(t=>now-t<windowMs);arr.push(now);rateHits.set(ip,arr);if(rateHits.size>5000)for(const[k,v]of rateHits)if(!v.some(t=>now-t<windowMs))rateHits.delete(k);return arr.length>max}
const publicFiles={'index.html':'text/html','app.js':'application/javascript','styles.css':'text/css','logo.png':'image/png','logo.svg':'image/svg+xml'};
const crypto=require('node:crypto');
const SESSION_TTL=8*3600*1000;
const sessions=new Map();
function cookies(req){const out={};(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=p.slice(i+1).trim()});return out}
function getSession(req){const id=cookies(req)['acb_session'];if(!id)return null;const s=sessions.get(id);if(!s)return null;if(Date.now()-s.ts>SESSION_TTL){sessions.delete(id);return null}return s}
function sessionCookie(id,maxAge){return `acb_session=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=${maxAge}${process.env.SECURE_COOKIES?'; Secure':''}`}
function ensureGov(data){data.directory=data.directory||{};data.roles=data.roles||{};data.groups=data.groups||{};data.sodMatrix=data.sodMatrix||[];data.adminQueue=data.adminQueue||[];data.adminAudit=data.adminAudit||[]}
function effPerms(data,role,groups){const set=new Set();const rc=data.roles||{},gc=data.groups||{};const names=[role,...((groups||[]).flatMap(g=>gc[g]?.roles||[]))];for(const rn of names){const r=rc[rn];if(r)(r.permissions||[]).forEach(x=>set.add(x))}return set}
function isGlobal(data,role,groups){const rc=data.roles||{},gc=data.groups||{};const names=[role,...((groups||[]).flatMap(g=>gc[g]?.roles||[]))];return names.some(n=>rc[n]?.global)}
function sodConflict(data,set){for(const [a,b] of (data.sodMatrix||[]))if(set.has(a)&&set.has(b))return [a,b];return null}
function principal(data,uid){const u=(data.directory||{})[uid];if(!u||u.status!=='Active')return null;return{uid,name:u.name,branch:u.branch,role:u.role,groups:u.groups||[],perms:effPerms(data,u.role,u.groups),global:isGlobal(data,u.role,u.groups)}}
function has(p,perm){return !!p&&p.perms.has(perm)}
function inScope(p,itemBranch){return !!p&&(p.global||p.branch===itemBranch)}
function initialsOf(name){return String(name||'').split(/\s+/).map(w=>w[0]).filter(Boolean).slice(0,2).join('').toUpperCase()||'AC'}
function notify(data,customer,account,branch,message,channel,status){data.notifications=data.notifications||[];data.notifications.unshift([ref('NTF'),customer||'Customer',account||'—',branch,channel||'SMS',message,status||'Sent',now()]);return data.notifications[0]}
function statePayload(data,me){const scoped=scope(data,me);const admin=has(me,'admin.manage')||has(me,'admin.authorise');if(!admin)for(const k of ['directory','roles','groups','sodMatrix','adminQueue','adminAudit'])delete scoped[k];delete scoped.requestPhones;let sms;if(admin){const c=loadSms();sms={provider:c.provider||'arkesel',senderId:c.senderId||'',enabled:!!c.enabled,apiKeyMasked:maskKey(c.apiKey),configured:!!(c.apiKey&&c.senderId)}}const customerStats=has(me,'customers.manage')?{total:customers().size,lastImport:customersLastImport}:undefined;return{data:scoped,role:me.role,branch:me.branch,name:me.name,perms:[...me.perms],global:me.global,initials:initialsOf(me.name),roleLabel:(data.roles?.[me.role]?.label)||me.role,permCatalog:admin?PERMISSIONS:undefined,sms,customerStats}}
function scope(data,sess){if(!sess||sess.global)return data;const b=sess.branch;const out={};for(const k in data)out[k]=Array.isArray(data[k])?data[k].filter(r=>Array.isArray(r)&&r.includes(b)):data[k];return out}
const usersPath=path.join(dataDir,'users.json');
function genPassword(){return crypto.randomBytes(9).toString('base64').replace(/[+/=]/g,'').slice(0,12)}
function seedUsers(){if(fs.existsSync(usersPath))return;const ids=['admin@acb.com','headoffice@acb.com','manager.koforidua@acb.com','ops.nsawam@acb.com','cs.nsawam@acb.com'];const users={};const shown=[];for(const id of ids){const fromEnv=id==='admin@acb.com'&&process.env.ADMIN_PASSWORD;const pw=fromEnv?process.env.ADMIN_PASSWORD:genPassword();const salt=crypto.randomBytes(16).toString('hex');const hash=crypto.scryptSync(pw,salt,64).toString('hex');users[id]={salt,hash};shown.push([id,pw,fromEnv?'(from ADMIN_PASSWORD env)':''])}fs.mkdirSync(path.dirname(usersPath),{recursive:true});fs.writeFileSync(usersPath,JSON.stringify(users,null,2));console.log('\n=== Initial staff passwords (shown once — store securely, then change on first sign-in) ===');for(const[id,pw,note]of shown)console.log(`  ${id.padEnd(30)} ${pw} ${note}`);console.log('=== Not persisted in plaintext anywhere ===\n')}
function setPassword(id,pw){let users={};try{users=JSON.parse(fs.readFileSync(usersPath,'utf8'))}catch{}const salt=crypto.randomBytes(16).toString('hex');const hash=crypto.scryptSync(String(pw),salt,64).toString('hex');users[id]={salt,hash};fs.mkdirSync(path.dirname(usersPath),{recursive:true});fs.writeFileSync(usersPath,JSON.stringify(users,null,2));return true}
function verifyUser(staffId,password){let users;try{users=JSON.parse(fs.readFileSync(usersPath,'utf8'))}catch{return null}const id=String(staffId||'').toLowerCase().trim();const u=users[id];if(!u)return null;let calc;try{calc=crypto.scryptSync(String(password||''),u.salt,64)}catch{return null}const stored=Buffer.from(u.hash,'hex');if(calc.length!==stored.length||!crypto.timingSafeEqual(calc,stored))return null;return id}
function killSessions(uid){for(const[sid,s]of sessions)if(s.uid===uid)sessions.delete(sid)}
const loginFails=new Map();const LOCK_MAX=8,LOCK_MS=15*60000;
function loginLocked(id){const e=loginFails.get(id);if(!e)return false;if(Date.now()>e.until){loginFails.delete(id);return false}return e.count>=LOCK_MAX}
function noteFail(id){const t=Date.now();let e=loginFails.get(id);if(!e||t>e.until)e={count:0,until:0};e.count++;e.until=t+LOCK_MS;loginFails.set(id,e)}
function clearFails(id){loginFails.delete(id)}
const smsPath=path.join(dataDir,'sms.json');
function loadSms(){try{return JSON.parse(fs.readFileSync(smsPath,'utf8'))}catch{return{provider:'arkesel',senderId:'',apiKey:'',enabled:false}}}
function saveSms(cfg){fs.mkdirSync(path.dirname(smsPath),{recursive:true});fs.writeFileSync(smsPath,JSON.stringify(cfg,null,2))}
function maskKey(k){k=String(k||'');return k?('•'.repeat(Math.max(2,k.length-4))+k.slice(-4)):''}
function normPhone(p){let d=String(p||'').replace(/[^0-9]/g,'');if(d.startsWith('233'))return d;if(d.startsWith('0'))return '233'+d.slice(1);if(d.length===9)return '233'+d;return d}
async function sendSms(cfg,phone,message){if(!cfg||!cfg.enabled)return{ok:false,detail:'SMS gateway disabled'};if(!cfg.apiKey||!cfg.senderId)return{ok:false,detail:'SMS gateway not configured'};const to=normPhone(phone);if(to.length<11||to.length>15)return{ok:false,detail:'Invalid phone number'};try{const ctrl=new AbortController();const t=setTimeout(()=>ctrl.abort(),12000);const r=await fetch('https://sms.arkesel.com/api/v2/sms/send',{method:'POST',headers:{'api-key':cfg.apiKey,'Content-Type':'application/json'},body:JSON.stringify({sender:cfg.senderId,message,recipients:[to]}),signal:ctrl.signal});clearTimeout(t);let j={};try{j=await r.json()}catch{}if(r.ok&&(j.status==='success'||j.code==='ok'||j.status===true))return{ok:true,detail:'Accepted by gateway'};return{ok:false,detail:(j&&(j.message||j.status))||`Gateway error ${r.status}`}}catch(e){return{ok:false,detail:e.name==='AbortError'?'Gateway timeout':'Gateway unreachable'}}}
// ---- Customer database (separate indexed store; NOT part of records.json) ----
const customersPath=path.join(dataDir,'customers.json');
let customersMap=null,customersLastImport='';
function customers(){if(customersMap)return customersMap;customersMap=new Map();try{const raw=JSON.parse(fs.readFileSync(customersPath,'utf8'));const list=Array.isArray(raw)?raw:(raw.list||[]);customersLastImport=raw.lastImport||'';for(const r of list)if(r&&r.account){r.nameLc=(r.name||'').toLowerCase();customersMap.set(String(r.account),r)}}catch{}return customersMap}
function persistCustomers(){const m=customers();const tmp=customersPath+'.tmp';fs.mkdirSync(path.dirname(customersPath),{recursive:true});fs.writeFileSync(tmp,JSON.stringify({lastImport:customersLastImport,list:[...m.values()].map(r=>({account:r.account,name:r.name,phone:r.phone,branch:r.branch,type:r.type,status:r.status,source:r.source,updated:r.updated}))}));fs.renameSync(tmp,customersPath)}
function custName(first,middle,surname,company){const parts=[first,middle,surname].map(s=>String(s||'').trim()).filter(Boolean);const dd=[];for(const p of parts)if(dd[dd.length-1]!==p)dd.push(p);return dd.join(' ')||String(company||'').trim()}
function upsertCustomer(m,rec){const acct=String(rec.account||'').trim();if(!acct)return 'skip';const ex=m.get(acct);const merged={account:acct,name:rec.name||ex?.name||'',phone:rec.phone||ex?.phone||'',branch:rec.branch||ex?.branch||'',type:rec.type||ex?.type||'',status:rec.status||ex?.status||'',source:rec.source||ex?.source||'import',updated:now()};merged.nameLc=(merged.name||'').toLowerCase();m.set(acct,merged);return ex?'update':'insert'}
function searchCustomers(rawQ,limit){const raw=String(rawQ||'').trim();const q=raw.toLowerCase();limit=limit||25;if(q.length<2)return[];const m=customers();const pub=r=>({account:r.account,name:r.name,phone:r.phone,branch:r.branch,type:r.type,status:r.status});const res=[];const exact=m.get(raw);if(exact)res.push(pub(exact));for(const r of m.values()){if(res.length>=limit)break;if(exact&&r.account===raw)continue;if(r.account.toLowerCase().includes(q)||r.nameLc.includes(q))res.push(pub(r))}return res}
function parseCsvLine(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const ch=line[i];if(q){if(ch==='"'){if(line[i+1]==='"'){cur+='"';i++}else q=false}else cur+=ch}else{if(ch==='"')q=true;else if(ch===','){out.push(cur);cur=''}else cur+=ch}}out.push(cur);return out}
function collectText(req,maxBytes){return new Promise((resolve,reject)=>{const chunks=[];let size=0,over=false;req.on('data',c=>{if(over)return;size+=c.length;if(size>maxBytes){over=true;reject(new Error('too large'))}else chunks.push(c)});req.on('end',()=>{if(!over)resolve(Buffer.concat(chunks).toString('utf8'))});req.on('error',()=>{if(!over)reject(new Error('stream'))})})}
function importCustomersCsv(text){const lines=text.split(/\r?\n/);if(lines.length<2)return{error:'The file is empty or has no data rows.'};const headers=parseCsvLine(lines[0]).map(h=>h.trim());const idx=n=>headers.indexOf(n);const iA=idx('Account Number');if(iA<0)return{error:'Missing an "Account Number" column.'};const iF=idx('First Name'),iM=idx('Middle Name'),iS=idx('Surname'),iC=idx('Company Name'),iMob=idx('Mobile Phone Number'),iMain=idx('Main Phone Number'),iMomo=idx('Mobile Money Number'),iT=idx('Account Type'),iSt=idx('Status Of Account'),iB=idx('Account Branch');const m=customers();let ins=0,upd=0,skip=0;for(let li=1;li<lines.length;li++){if(!lines[li].trim())continue;const c=parseCsvLine(lines[li]);const acct=String(c[iA]||'').trim();if(!acct){skip++;continue}const phoneRaw=(iMob>=0&&c[iMob])||(iMain>=0&&c[iMain])||(iMomo>=0&&c[iMomo])||'';const rec={account:acct,name:custName(c[iF],c[iM],c[iS],c[iC]),phone:phoneRaw?normPhone(phoneRaw):'',branch:String(c[iB]||'').trim(),type:String(c[iT]||'').trim(),status:String(c[iSt]||'').trim(),source:'import'};const r=upsertCustomer(m,rec);if(r==='insert')ins++;else if(r==='update')upd++;else skip++}customersLastImport=now();persistCustomers();return{inserted:ins,updated:upd,skipped:skip,total:m.size,lastImport:customersLastImport}}
function now(){return new Intl.DateTimeFormat('en-GB',{dateStyle:'medium',timeStyle:'short'}).format(new Date())}
const branchList=['Nsawam Branch','Koforidua Branch','Aburi Branch','Adukrom Branch','Mamfe Branch','Madina Branch'];
function ref(prefix){return `${prefix}-${Date.now().toString().slice(-6)}`}
function need(fields,keys){for(const k of keys)if(!String(fields[k]||'').trim())return `The "${k}" field is required.`;return null}
const PENDING='Pending Authorization';
const builders={
  request(f,branch){const e=need(f,['account','customer','book']);if(e)return{error:e};const r=ref('CBR');return{bucket:'requests',label:'Cheque book request',ref:r,subject:f.customer,statusIdx:5,finalStatus:'Authorized',entry:[r,f.account,f.customer,branch,f.book,PENDING,now()]}},
  inventory(f,branch){const e=need(f,['type','start','end']);if(e)return{error:e};const start=parseInt(f.start,10),end=parseInt(f.end,10);if(!Number.isFinite(start)||!Number.isFinite(end))return{error:'Start and end serials must be numeric.'};if(end<start)return{error:'End serial cannot be lower than the start serial.'};const width=Math.max(String(f.start).trim().length,String(f.end).trim().length);const pad=n=>String(n).padStart(width,'0');const total=String(end-start+1);const r=ref('INV');return{bucket:'inventory',label:'Range registration',ref:r,subject:f.type,statusIdx:6,finalStatus:'Active',entry:[r,branch,f.type,`${pad(start)} – ${pad(end)}`,total,total,PENDING]}},
  issuance(f,branch){const e=need(f,['request','account','range']);if(e)return{error:e};const r=ref('ISS');return{bucket:'issuance',label:'Cheque book issuance',ref:r,subject:f.account,statusIdx:5,finalStatus:'Issued',entry:[r,f.request,f.account,branch,f.range,PENDING,now()]}},
  stop(f,branch){const e=need(f,['cheque','account','reason']);if(e)return{error:e};const cancel=/cancel/i.test(f.instruction||'');const r=ref(cancel?'CAN':'STP');return{bucket:'stops',label:'Stop-cheque instruction',ref:r,subject:f.account,statusIdx:5,finalStatus:cancel?'Cancelled':'Stopped',entry:[r,f.cheque,f.account,branch,f.reason,PENDING,now()]}},
  returns(f,branch){const e=need(f,['cheque','account','reason']);if(e)return{error:e};const r=ref('RET');return{bucket:'returns',label:'Returned cheque record',ref:r,subject:f.account,statusIdx:6,finalStatus:'Returned',entry:[r,f.cheque,f.account,branch,f.reason,String(f.amount||'').trim()||'—',PENDING]}}
};
function applyChange(data,chg){const p=chg.payload;switch(chg.type){
  case 'user/create':{if(data.directory[p.id])return 'A user with that staff ID already exists.';data.directory[p.id]={name:p.name,branch:p.branch,role:p.role,groups:[],status:'Active',lastReviewed:now()};return null}
  case 'user/role':{const u=data.directory[p.uid];if(!u)return 'User not found.';if(!data.roles[p.role])return 'Role not found.';const c=sodConflict(data,effPerms(data,p.role,u.groups));if(c)return `Segregation-of-duties conflict: ${c[0]} vs ${c[1]}.`;u.role=p.role;return null}
  case 'user/groups/add':{const u=data.directory[p.uid];if(!u)return 'User not found.';if(!data.groups[p.group])return 'Group not found.';const groups=[...new Set([...(u.groups||[]),p.group])];const c=sodConflict(data,effPerms(data,u.role,groups));if(c)return `Segregation-of-duties conflict: ${c[0]} vs ${c[1]}.`;u.groups=groups;return null}
  case 'user/enable':{const u=data.directory[p.uid];if(!u)return 'User not found.';u.status='Active';return null}
  case 'role/save':{const c=sodConflict(data,new Set(p.permissions));if(c)return `A role cannot combine ${c[0]} and ${c[1]}.`;data.roles[p.name]={label:p.label,global:!!p.global,permissions:p.permissions,system:!!p.system};return null}
  case 'group/save':{const set=new Set((p.roles||[]).flatMap(r=>data.roles[r]?.permissions||[]));const c=sodConflict(data,set);if(c)return `A group cannot combine ${c[0]} and ${c[1]}.`;data.groups[p.name]={description:p.description,branch:p.branch,roles:p.roles};return null}
  case 'sod/remove':{data.sodMatrix=(data.sodMatrix||[]).filter(pair=>!((pair[0]===p.a&&pair[1]===p.b)||(pair[0]===p.b&&pair[1]===p.a)));return null}
  default:return 'Unknown change type.';
}}
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://localhost');
  if(url.pathname.startsWith('/api/')&&rateLimited(clientIp(req)))return send(res,429,{error:'Too many requests. Please slow down.'});
  if(req.method==='POST'&&url.pathname==='/api/session'){try{const body=await collect(req);const idKey=String(body.staffId||'').toLowerCase().trim();if(loginLocked(idKey))return send(res,429,{error:'Too many failed attempts. Please try again in 15 minutes.'});const uid=verifyUser(body.staffId,body.password);if(!uid){noteFail(idKey);return send(res,401,{error:'Invalid staff ID or password.'})}clearFails(idKey);const data=load();const me=principal(data,uid);if(!me)return send(res,403,{error:'This account is disabled. Contact an administrator.'});const id=crypto.randomBytes(18).toString('hex');sessions.set(id,{uid,ts:Date.now()});res.writeHead(200,{...securityHeaders,'Content-Type':'application/json','Cache-Control':'no-store','Set-Cookie':sessionCookie(id,SESSION_TTL/1000)});return res.end(JSON.stringify(statePayload(data,me)))}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/logout'){const id=cookies(req)['acb_session'];if(id)sessions.delete(id);res.writeHead(200,{...securityHeaders,'Content-Type':'application/json','Cache-Control':'no-store','Set-Cookie':sessionCookie('',0)});return res.end(JSON.stringify({ok:true}))}
  const rawSess=getSession(req);
  if(url.pathname.startsWith('/api/')&&!rawSess)return send(res,401,{error:'Not authenticated. Please sign in.'});
  const sess=rawSess?principal(load(),rawSess.uid):null;
  if(url.pathname.startsWith('/api/')&&!sess)return send(res,401,{error:'Your session is no longer valid. Please sign in again.'});
  if(req.method==='GET'&&url.pathname==='/api/state')return send(res,200,statePayload(load(),sess));
  if(req.method==='GET'&&url.pathname==='/api/customers/search'){if(!has(sess,'customers.view'))return send(res,403,{error:'You do not have permission to search customers.'});return send(res,200,{results:searchCustomers(url.searchParams.get('q')||'',25)})}
  if(req.method==='POST'&&url.pathname==='/api/customers/import'){if(!has(sess,'customers.manage'))return send(res,403,{error:'You do not have permission to import the customer database.'});let text;try{text=await collectText(req,30*1024*1024)}catch(e){return send(res,413,{error:'File exceeds the 30 MB limit or failed to upload.'})}try{const out=importCustomersCsv(text);if(out.error)return send(res,400,{error:out.error});const data=load();data.audit.unshift([now(),'Customer database imported',`${out.total} total`,sess.name,sess.role,sess.branch,`${out.inserted} new, ${out.updated} updated, ${out.skipped} skipped`]);save(data);return send(res,200,out)}catch{return send(res,400,{error:'Could not parse the uploaded file. Ensure it is a CSV export.'})}}
  if(req.method==='POST'&&url.pathname==='/api/password'){try{const body=await collect(req);if(verifyUser(sess.uid,body.currentPassword)!==sess.uid)return send(res,403,{error:'Your current password is incorrect.'});const np=String(body.newPassword||'');if(np.length<10)return send(res,400,{error:'New password must be at least 10 characters.'});if(np===String(body.currentPassword||''))return send(res,400,{error:'Choose a password different from the current one.'});setPassword(sess.uid,np);const data=load();data.audit.unshift([now(),'Password changed',sess.uid,sess.name,sess.role,sess.branch,'Self-service password update']);save(data);return send(res,200,{ok:true})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/transactions'){try{const body=await collect(req);const builder=builders[body.module];if(!builder)return send(res,400,{error:'Invalid transaction type.'});if(!has(sess,`${body.module}.create`))return send(res,403,{error:'You do not have permission to create this transaction.'});const fields=body.fields||{};const targetBranch=String(fields.branch||sess.branch||'').trim();if(!branchList.includes(targetBranch))return send(res,400,{error:'A valid branch must be selected.'});if(!sess.global&&targetBranch!==sess.branch)return send(res,403,{error:'You can only create records for your own branch.'});const built=builder(fields,targetBranch);if(built.error)return send(res,400,{error:built.error});const data=load();if(!data.approvalMeta)data.approvalMeta={};if(body.module==='request'){const ph=normPhone(fields.phone);if(ph.length<11)return send(res,400,{error:'A valid customer phone number is required.'});data.requestPhones=data.requestPhones||{};data.requestPhones[built.ref]=ph}data[built.bucket].unshift(built.entry);const queueId=ref('APR');data.approvals.unshift([queueId,built.label,built.ref,built.subject,targetBranch,sess.name,now()]);data.approvalMeta[queueId]={bucket:built.bucket,ref:built.ref,statusIdx:built.statusIdx,finalStatus:built.finalStatus,maker:sess.name,makerRole:sess.role};data.audit.unshift([now(),`${built.label} submitted`,built.ref,sess.name,sess.role,targetBranch,'Submitted for maker-checker approval']);save(data);return send(res,201,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&(url.pathname==='/api/authorizations/authorise'||url.pathname==='/api/authorizations/reject')){try{if(!has(sess,'txn.authorise'))return send(res,403,{error:'Authorisation permission required.'});const reject=url.pathname.endsWith('/reject');const body=await collect(req);const data=load();if(!data.approvalMeta)data.approvalMeta={};const idx=data.approvals.findIndex(a=>a[0]===body.ref);if(idx<0)return send(res,404,{error:'This item is no longer in the authorisation queue.'});const item=data.approvals[idx];if(!inScope(sess,item[4]))return send(res,403,{error:'This item is outside your branch scope.'});const meta=data.approvalMeta[item[0]]||{};if(meta.maker&&meta.maker===sess.name)return send(res,403,{error:'The submitting officer cannot authorise their own transaction.'});const rec=meta.bucket&&data[meta.bucket]?data[meta.bucket].find(r=>r[0]===meta.ref):null;if(rec&&typeof meta.statusIdx==='number')rec[meta.statusIdx]=reject?'Rejected':meta.finalStatus;data.approvals.splice(idx,1);delete data.approvalMeta[item[0]];data.audit.unshift([now(),reject?'Transaction rejected':'Transaction authorised',item[2],sess.name,sess.role,item[4],reject?`Rejected by checker (maker ${meta.maker||'n/a'})`:`Authorised by checker (maker ${meta.maker||'n/a'})`]);if(!reject&&rec&&meta.bucket==='issuance'){const req=(data.requests||[]).find(r=>r[0]===rec[1]);const customer=req?req[2]:rec[2];notify(data,customer,rec[2],rec[3],`Your cheque book ${rec[4]} is ready for collection at ${rec[3]}. Please bring valid photo ID.`,'SMS');data.audit.unshift([now(),'Customer alert sent',rec[0],'System','Notification',rec[3],'Cheque book ready-for-collection alert issued'])}if(!reject&&rec&&meta.bucket==='requests'){const acct=String(rec[1]),nm=rec[2],br=rec[3],ph=(data.requestPhones||{})[rec[0]]||'';const m=customers();const before=m.has(acct);upsertCustomer(m,{account:acct,name:nm,phone:ph,branch:br,status:'Active',source:'requisition'});persistCustomers();if(!before)data.audit.unshift([now(),'Customer added to database',acct,'System','Customer DB',br,`New customer ${nm} from requisition ${rec[0]}`])}save(data);return send(res,200,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/vault/push'){try{if(!has(sess,'vault.dispatch'))return send(res,403,{error:'You do not have permission to dispatch cheque stock to a branch vault.'});const body=await collect(req);const f=body.fields||{};const dest=String(f.branch||'').trim();if(!branchList.includes(dest))return send(res,400,{error:'Select a valid destination branch.'});const e=need(f,['type','start','end']);if(e)return send(res,400,{error:e});const start=parseInt(f.start,10),end=parseInt(f.end,10);if(!Number.isFinite(start)||!Number.isFinite(end))return send(res,400,{error:'Start and end serials must be numeric.'});if(end<start)return send(res,400,{error:'End serial cannot be lower than the start serial.'});const width=Math.max(String(f.start).trim().length,String(f.end).trim().length);const pad=n=>String(n).padStart(width,'0');const total=end-start+1;const data=load();if(!data.vault)data.vault=[];const r=ref('VLT');data.vault.unshift([r,dest,f.type,`${pad(start)} – ${pad(end)}`,`${total} leaves`,'Awaiting Confirmation',now()]);data.audit.unshift([now(),'Cheque stock dispatched to vault',r,sess.role,sess.role,dest,'Awaiting branch reconciliation and confirmation']);save(data);return send(res,201,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/vault/submit'){try{if(!has(sess,'vault.submit'))return send(res,403,{error:'You do not have permission to submit vault stock for authorisation.'});const body=await collect(req);const data=load();if(!data.vault)data.vault=[];if(!data.vaultMeta)data.vaultMeta={};const item=data.vault.find(v=>v[0]===body.ref&&v[5]==='Awaiting Confirmation');if(!item)return send(res,404,{error:'Batch not found or not awaiting confirmation.'});if(!inScope(sess,item[1]))return send(res,403,{error:'This batch belongs to another branch vault.'});item[5]='Pending Authorisation';data.vaultMeta[item[0]]={maker:sess.name,makerRole:sess.role,submitted:now()};data.audit.unshift([now(),'Vault acceptance submitted',item[0],sess.name,sess.role,item[1],'Hard copies reconciled; awaiting second-officer authorisation']);save(data);return send(res,200,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/vault/authorise'){try{if(!has(sess,'vault.authorise'))return send(res,403,{error:'Authorisation permission required.'});const body=await collect(req);const data=load();if(!data.vault)data.vault=[];if(!data.vaultMeta)data.vaultMeta={};const item=data.vault.find(v=>v[0]===body.ref&&v[5]==='Pending Authorisation');if(!item)return send(res,404,{error:'Batch not found or not pending authorisation.'});if(!inScope(sess,item[1]))return send(res,403,{error:'This batch belongs to another branch vault.'});const meta=data.vaultMeta[item[0]]||{};if(meta.maker&&meta.maker===sess.name)return send(res,403,{error:'The submitting officer cannot authorise their own acceptance.'});const total=String(item[4]).replace(/[^0-9]/g,'')||'0';const invRef=ref('INV');data.inventory.unshift([invRef,item[1],item[2],item[3],total,total,'Active']);item[5]='Accepted';data.audit.unshift([now(),'Vault stock authorised and accepted',item[0],sess.name,sess.role,item[1],`Authorised (maker ${meta.maker||'n/a'}); moved to inventory as ${invRef}`]);let alerted=0;(data.requests||[]).forEach(rq=>{if(rq[3]===item[1]&&rq[5]==='Authorized'){notify(data,rq[2],rq[1],item[1],`Cheque stock has arrived at ${item[1]} — your requested cheque book is being prepared for collection. We will notify you when it is ready.`,'SMS');alerted++}});if(alerted)data.audit.unshift([now(),'Customer alerts sent',invRef,'System','Notification',item[1],`${alerted} customer${alerted===1?'':'s'} notified of arriving stock`]);delete data.vaultMeta[item[0]];save(data);return send(res,200,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/vault/reject'){try{if(!has(sess,'vault.authorise'))return send(res,403,{error:'Authorisation permission required.'});const body=await collect(req);const data=load();if(!data.vault)data.vault=[];if(!data.vaultMeta)data.vaultMeta={};const item=data.vault.find(v=>v[0]===body.ref&&v[5]==='Pending Authorisation');if(!item)return send(res,404,{error:'Batch not found or not pending authorisation.'});if(!inScope(sess,item[1]))return send(res,403,{error:'This batch belongs to another branch vault.'});const meta=data.vaultMeta[item[0]]||{};item[5]='Awaiting Confirmation';data.audit.unshift([now(),'Vault acceptance rejected',item[0],sess.name,sess.role,item[1],`Returned for re-reconciliation (maker ${meta.maker||'n/a'})`]);delete data.vaultMeta[item[0]];save(data);return send(res,200,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/vault/dispatch-item'){try{if(!has(sess,'vault.dispatch'))return send(res,403,{error:'You do not have permission to dispatch itemised cheques.'});const body=await collect(req);const data=load();data.vaultItems=data.vaultItems||[];data.requestPhones=data.requestPhones||{};const reqRef=String(body.requestRef||'').trim();const rq=(data.requests||[]).find(r=>r[0]===reqRef);if(!rq)return send(res,404,{error:'Cheque book request not found.'});const phone=data.requestPhones[reqRef];if(!phone)return send(res,400,{error:'That requisition has no linked telephone number.'});const r=ref('VIT');data.vaultItems.unshift([r,rq[2],rq[1],phone,rq[3],reqRef,'Awaiting Confirmation',now()]);data.audit.unshift([now(),'Itemised cheque dispatched to vault',r,sess.name,sess.role,rq[3],`For ${rq[2]} (${reqRef})`]);save(data);return send(res,201,{data:scope(data,sess)})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(req.method==='POST'&&url.pathname==='/api/vault/receive-item'){try{if(!has(sess,'vault.submit')&&!has(sess,'vault.authorise'))return send(res,403,{error:'You do not have permission to receive vault items.'});const body=await collect(req);const data=load();data.vaultItems=data.vaultItems||[];const item=data.vaultItems.find(v=>v[0]===body.ref&&v[6]==='Awaiting Confirmation');if(!item)return send(res,404,{error:'Item not found or already received.'});if(!inScope(sess,item[4]))return send(res,403,{error:'This item belongs to another branch vault.'});item[6]='Ready for Collection';const msg=`Dear ${item[1]}, your cheque book is ready for collection at ${item[4]}, Akuapem Community Bank. Please bring a valid photo ID.`;const cfg=loadSms();const outcome=await sendSms(cfg,item[3],msg);const status=outcome.ok?'Sent':(cfg.enabled?'Failed':'Not sent');notify(data,item[1],item[2],item[4],msg,'SMS',status);data.audit.unshift([now(),'Itemised cheque received & customer alerted',item[0],sess.name,sess.role,item[4],`SMS to ${item[3]}: ${outcome.detail}`]);save(data);return send(res,200,{data:scope(data,sess),sms:{ok:outcome.ok,detail:outcome.detail}})}catch{return send(res,400,{error:'Invalid request.'})}}
  if(url.pathname.startsWith('/api/admin/')&&req.method==='POST'){const act=url.pathname.slice('/api/admin/'.length);const canManage=has(sess,'admin.manage'),canAuth=has(sess,'admin.authorise');if(!canManage&&!canAuth)return send(res,403,{error:'Administration permission required.'});let body;try{body=await collect(req)}catch{return send(res,400,{error:'Invalid request.'})}const data=load();ensureGov(data);const dir=data.directory;const bad=m=>send(res,400,{error:m});const log=(action,target,detail)=>data.adminAudit.unshift([now(),sess.name,action,target||'—',detail||'']);const done=()=>{save(data);return send(res,200,statePayload(data,principal(data,sess.uid)))};const queueChange=(type,summary,targetUid,payload)=>{const id=ref('CHG');data.adminQueue.unshift({id,type,summary,targetUid:targetUid||'',submittedBy:sess.name,submittedAt:now(),payload});log('Change submitted for authorisation',targetUid||type,summary)};
    if(['user/create','user/role','user/groups/add','user/groups/remove','user/disable','user/enable','user/recertify','role/save','role/delete','group/save','group/delete','sod/add','sod/remove','sms/save','sms/test'].includes(act)&&!canManage)return send(res,403,{error:'Manage permission required.'});
    if(act==='sms/save'){const cur=loadSms();const cfg={provider:'arkesel',senderId:String(body.senderId||'').trim(),apiKey:body.apiKey?String(body.apiKey).trim():cur.apiKey,enabled:!!body.enabled};saveSms(cfg);log('SMS gateway settings updated','SMS',`Sender "${cfg.senderId}", ${cfg.enabled?'enabled':'disabled'}`);save(data);return send(res,200,{...statePayload(data,principal(data,sess.uid))})}
    if(act==='sms/test'){const cfg=loadSms();const outcome=await sendSms(cfg,body.phone,`Test message from ${cfg.senderId||'Akuapem Community Bank'} — your SMS gateway is working.`);log('SMS test message sent','SMS',`${normPhone(body.phone)}: ${outcome.detail}`);save(data);return send(res,outcome.ok?200:400,{...statePayload(data,principal(data,sess.uid)),smsTest:outcome})}
    try{switch(act){
      case 'user/create':{const id=String(body.id||'').toLowerCase().trim();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(id))return bad('Enter a valid staff email address.');if(dir[id])return bad('A user with that staff ID already exists.');if(!String(body.name||'').trim())return bad('Enter the user name.');if(!data.roles[body.role])return bad('Select a valid role.');const branch=body.branch;if(branch!=='All Branches'&&!branchList.includes(branch))return bad('Select a valid branch.');queueChange('user/create',`Create user ${String(body.name).trim()} (${id}) as ${body.role}`,id,{id,name:String(body.name).trim(),branch,role:body.role});return done()}
      case 'user/role':{const u=dir[body.uid];if(!u)return send(res,404,{error:'User not found.'});if(!data.roles[body.role])return bad('Select a valid role.');const c=sodConflict(data,effPerms(data,body.role,u.groups));if(c)return bad(`That role would breach segregation of duties (${c[0]} vs ${c[1]}).`);queueChange('user/role',`Role ${u.role} → ${body.role} for ${u.name}`,body.uid,{uid:body.uid,role:body.role});return done()}
      case 'user/groups/add':{const u=dir[body.uid];if(!u)return send(res,404,{error:'User not found.'});if(!data.groups[body.group])return bad('Select a valid group.');const groups=[...new Set([...(u.groups||[]),body.group])];const c=sodConflict(data,effPerms(data,u.role,groups));if(c)return bad(`That group would breach segregation of duties (${c[0]} vs ${c[1]}).`);queueChange('user/groups/add',`Add ${u.name} to group ${body.group}`,body.uid,{uid:body.uid,group:body.group});return done()}
      case 'user/groups/remove':{const u=dir[body.uid];if(!u)return send(res,404,{error:'User not found.'});u.groups=(u.groups||[]).filter(g=>g!==body.group);log('Removed from group',body.uid,body.group);return done()}
      case 'user/disable':{const u=dir[body.uid];if(!u)return send(res,404,{error:'User not found.'});if(body.uid===sess.uid)return bad('You cannot disable your own account.');u.status='Disabled';killSessions(body.uid);log('User disabled',body.uid,'Access revoked; live sessions ended');return done()}
      case 'user/enable':{const u=dir[body.uid];if(!u)return send(res,404,{error:'User not found.'});queueChange('user/enable',`Re-enable ${u.name}`,body.uid,{uid:body.uid});return done()}
      case 'user/recertify':{const u=dir[body.uid];if(!u)return send(res,404,{error:'User not found.'});u.lastReviewed=now();log('Access recertified',body.uid,`Role ${u.role}`);return done()}
      case 'role/save':{const name=String(body.name||'').trim();if(!name)return bad('Enter a role name.');const perms=(body.permissions||[]).filter(x=>PERM_IDS.includes(x));const c=sodConflict(data,new Set(perms));if(c)return bad(`A role cannot combine ${c[0]} and ${c[1]} (segregation of duties).`);queueChange('role/save',`${data.roles[name]?'Update':'Create'} role ${name}`,name,{name,label:String(body.label||name).trim(),global:!!body.global,permissions:perms,system:!!data.roles[name]?.system});return done()}
      case 'role/delete':{const r=data.roles[body.name];if(!r)return send(res,404,{error:'Role not found.'});if(r.system)return bad('Built-in roles cannot be deleted.');if(Object.values(dir).some(u=>u.role===body.name)||Object.values(data.groups).some(g=>(g.roles||[]).includes(body.name)))return bad('Role is assigned to users or groups.');delete data.roles[body.name];log('Role deleted',body.name,'');return done()}
      case 'group/save':{const name=String(body.name||'').trim();if(!name)return bad('Enter a group name.');const gr=(body.roles||[]).filter(r=>data.roles[r]);const c=sodConflict(data,new Set(gr.flatMap(r=>data.roles[r].permissions)));if(c)return bad(`A group cannot combine ${c[0]} and ${c[1]}.`);const branch=body.branch||'All Branches';queueChange('group/save',`${data.groups[name]?'Update':'Create'} group ${name}`,name,{name,description:String(body.description||'').trim(),branch,roles:gr});return done()}
      case 'group/delete':{if(!data.groups[body.name])return send(res,404,{error:'Group not found.'});if(Object.values(dir).some(u=>(u.groups||[]).includes(body.name)))return bad('Group still has members.');delete data.groups[body.name];log('Group deleted',body.name,'');return done()}
      case 'sod/add':{const a=body.a,b=body.b;if(!PERM_IDS.includes(a)||!PERM_IDS.includes(b)||a===b)return bad('Choose two different permissions.');if(!(data.sodMatrix||[]).some(p=>(p[0]===a&&p[1]===b)||(p[0]===b&&p[1]===a)))data.sodMatrix.push([a,b]);log('SoD rule added',`${a} ⨂ ${b}`,'');return done()}
      case 'sod/remove':{queueChange('sod/remove',`Remove SoD rule ${body.a} ⨂ ${body.b}`,'',{a:body.a,b:body.b});return done()}
      case 'change/authorise':{if(!canAuth)return send(res,403,{error:'Authorisation permission required.'});const i=data.adminQueue.findIndex(c=>c.id===body.id);if(i<0)return send(res,404,{error:'Change not found.'});const chg=data.adminQueue[i];if(chg.submittedBy===sess.name)return send(res,403,{error:'The submitting administrator cannot authorise their own change.'});if(chg.targetUid&&chg.targetUid===sess.uid)return send(res,403,{error:'You cannot authorise a change affecting your own account.'});const err=applyChange(data,chg);if(err)return bad(err);let tempPassword=null;if(chg.type==='user/create'){tempPassword=genPassword();setPassword(chg.payload.id,tempPassword)}data.adminQueue.splice(i,1);log('Change authorised & applied',chg.targetUid||chg.type,chg.summary);save(data);const payload=statePayload(data,principal(data,sess.uid));if(tempPassword){payload.tempPassword=tempPassword;payload.tempUser=chg.payload.id}return send(res,200,payload)}
      case 'change/reject':{if(!canAuth)return send(res,403,{error:'Authorisation permission required.'});const i=data.adminQueue.findIndex(c=>c.id===body.id);if(i<0)return send(res,404,{error:'Change not found.'});const chg=data.adminQueue[i];data.adminQueue.splice(i,1);log('Change rejected',chg.targetUid||chg.type,chg.summary);return done()}
      default:return send(res,404,{error:'Unknown administration action.'});
    }}catch{return send(res,400,{error:'Invalid request.'})}
  }
  const file=url.pathname==='/'?'index.html':url.pathname.slice(1);const type=publicFiles[file];
  const fp=path.join(root,file);
  if(req.method!=='GET'||!type||!fs.existsSync(fp)){res.writeHead(404,securityHeaders);return res.end('Not found')}
  const isImg=type.startsWith('image/');res.writeHead(200,{...securityHeaders,'Content-Type':isImg?type:`${type}; charset=utf-8`,'Cache-Control':isImg?'public, max-age=86400':'no-cache'});fs.createReadStream(fp).pipe(res)});
seedUsers();customers();
const port=process.env.PORT||3000;server.listen(port,()=>console.log(`Cheque Management System running on http://localhost:${port}`));
